const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = require('./webpack.common')({
	modt: 'development',
	entry: './src/app.js',
	output: {
		path: path.join(__dirname, '../dist'),
		filename: 'index.js',
	},
	devServer: {
		port: 3000,
		watchContentBase: true,
		historyApiFallback: true,
	},

	// Add development plugins
	plugins: [
		new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
		new HtmlWebpackPlugin({
			inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
			template: 'src/index.html',
		}),
		new webpack.EnvironmentPlugin({
			NODE_ENV: 'development',
		}),
	],

	// Emit a source map for easier debugging
	// See https://webpack.js.org/configuration/devtool/#devtool
	devtool: 'source-map',

	performance: {
		hints: false,
	},
});
 