Config = {
	ExcludeDrop = {
		"Disconnected",
		"cup-leopard-triple",
		"Kicked",
		"Banned",
		"Exiting",
	},
	Settings = {
		QueueDelay = 2,
		MaxTimeBoost = 30,
		Grace = 5,
	},
	Strings = {
		Add = "Added %s (Account: %s, Identifier: %s) To Queue %s/%s (Current Players: %s)",
		Banned = "You're Banned, Appeal At https://google.com/\n\nReason: %s\nExpires: %s\nID: %s",
		PermaBanned = "Permanently Banned, Appeal At https://google.com/\n\nReason: %s\nID: %s",
		SiteBanned = "You're Banned From the Website. View Reason At https://google.com/",
		Checking = "Checking Whitelist Status",
		DatabaseWait = "Waiting For Server To Be Ready, Please Wait (%s - %s - %s)\n\nIf The Emotes Stop Changing, Please Reconnect",
		Disconnected = "%s (Account: %s, Identifier: %s) Disconnected, Starting Grace",
		Dropped = "Dropped From Server.",
		Dropping = "^8Dropping Lowest Priority Player For Privileged Player %s",
		Grace = "^5Starting Grace Timer For %s - Ends At %s^7",
		IdentifierNotLinked = "Identifier Not Linked To Any Blue Sky Account, Please Go To https://google.com/ & Link Your Account.",
		Joined = "%s (Account: %s, Identifier: %s) Joined The Server",
		Joining = "Joining Server...",
		NoAccountData = "Unable To Get Your Account Data, Please Try Again.",
		NoIdentifier = "Could Not Find Steam Identifier, Relaunch FiveM and try again. (Make Sure Steam is Open & Logged In)",
		NotReady = "The Mythic Framework server has not yet finished loading, please try again in a few minutes.",
		NotWhitelisted = "You Are Not Whitelisted For This Server - Apply Today At https://google.com/",
		PrioAdd = "Added %s (%s) To Queue %s/%s With Priority %s",
		PrioWaiting = "Waiting For Priority Player To Join Server",
		Queued = "Position %s of %s - Time In Queue: %s%s",
		Retrieving = "Retrieving Queue Information",
		Validating = "Validating Account, Please Wait...",
		ValidateSuccess = "Account Validated, Continueing Connection Process...",
		ValidateFail = "Unable to Validate Account",
		ValidateTimeout = "Link Key Expired, Please Regenerate A New Key",
		ValidateInvalid = "Inavlid Validation Code, Please Try Again",
		Waiting = "Waiting For Queue To Open - %s %s %s %s",
		WaitingSeconds = "Waiting For Queue To Open - %s %s",
		PendingRestart = "🚫 Queue Closed 🚫 Due To A Pending Restart We've Closed The Queue. Please Reconnect In A Few Minutes",
		PublicWhitelist = "You need to register an account at https://google.com/ and link your Steam account to play on this server.",
	},
	Emotes = {
		"🍕",
		"🍔",
		"🍟",
		"🌭",
		"🍿",
		"🥓",
		"🥚",
		"🍳",
		"🧇",
		"🥞",
		"🧈",
		"🍞",
		"🥐",
		"🥨",
		"🥯",
		"🥖",
		"🧀",
		"🥗",
		"🥙",
		"🥪",
		"🌮",
		"🌮",
		"🌯",
		"🥫",
		"🍖",
		"🍗",
		"🥩",
		"🍠",
		"🥟",
		"🥠",
		"🥡",
		"🍱",
		"🍘",
		"🍙",
		"🍚",
		"🍛",
		"🍜",
		"🦪",
		"🦪",
		"🍣",
		"🍤",
		"🍥",
		"🥮",
		"🍢",
		"🧆",
		"🥘",
		"🍲",
		"🍝",
		"🥣",
		"🥧",
		"🍦",
		"🍧",
		"🍨",
		"🍩",
		"🍪",
		"🎂",
		"🍰",
		"🧁",
		"🍫",
		"🍬",
		"🍭",
		"🍡",
		"🍮",
		"🍯",
		"🍼",
	},
}