_vehNames = {
    ['Albany'] = {
        'Alpha',
        'Buccaneer',
        'Cavalcade',
        'Emperor',
        'Manana',
        'Hermes',
        'Primo',
        'Washington',
    },
    ['Brute'] = {
        'Stockade',
        'Pony',
        'Camper',
        'Tipper',
    },
    ['BF'] = {
        'Surfer',
        'Bifta',
        'Injection',
    },
    ['Bravado'] = {
        'Banshee',
        'Gauntlet',
        'Buffalo',
        'Buffalo S',
        'Gresley',
        'Rat-Truck',
        'Youga',
        'Rumpo Custom',
        'Bison',
        'Paradise',
        'Duneloader',
    },
    ['Benefactor'] = {
        'Dubsta',
        'Dubsta 6x6',
        'Feltzer',
        'Glendale',
        'Panto',
        'Schafter',
        'Schafter V12',
        'Schlagen',
        'Serrano',
        'Streiter',
        'Surano',
        'Stirling',
        'XLS',
    },
    ['Cheval'] = {
        'Fugitive',
        'Surge',
        'Picador',
    },
    ['Coil'] = {
        'Brawler',
        'Raiden',
        'Voltic',
    },
    ['Canis'] = {
        'Seminole',
        'Mesa',
        'Freecrawler',
        'Kamacho',
        'Kalahari',
        'Bodhi',
    },
    ['Declasse'] = {
        'Asea',
        'Emperor',
        'Moonbeam',
        'Granger',
        'Rhapsody',
        'Sabre Turbo',
        'Stallion',
        'Tulip',
        'Vigero',
        'Impaler',
        'Premier',
        'Tampa',
        'Yosemite',
        'Tornado',
        'Tornado Cabrio',
        'Vamos',
    },
    ['Dewbauchee'] = {
        'Rapid GT',
        'Seven-70',
        'Specter',
        'Massacro',
        'Exemplar',
    },
    ['Dundreary'] = {
        'Stretch',
        'Landstalker',
    },
    ['Maibatsu'] = {
        'Penumbra',
        'Penumbra FF',
        'Mule',
    },
    ['Mammoth'] = {
        'Patriot',
    },
    ['Maxwell'] = {
        'Asbo',
        'Vagrant',
    },
    ['Gallivanter'] = {
        'Baller',
        'Baller XL',
        'Baller LE',
    },
    ['Karin'] = {
        'Futo',
        'Kuruma',
        'Sultan',
        'Sultan RS',
        'Intruder',
        'Everon',
        'Asterope',
        'BeeJay XL',
        'Rebel',
        'Dilettante',
    },
    ['Lampadati'] = {
        'Michelli GT',
        'Toros',
        'Casco',
        'Viseris',
        'Komoda',
        'Felon GT',
        'Furore GT',
    },
    ['MTL'] = {
        'Wastelander',
        'Flatbed',
        'Packer',
        'Pounder',
    },
    ['Stanley'] = {
        'Fieldmaster',
    },
    ['HVY'] = {
        'Forklift',
        'Biff',
        'Mixer',
    },
    ['Weeny'] = {
        'Issi',
        'Dynasty',
        'Issi Classic',
        'Issi Sport',
    },
    ['Willard'] = {
        'Faction',
    },
    ['Fathom'] = {
        'FQ-2',
    },
    ['Dinka'] = {
        'Blista',
        'Blista Compact',
        'Kanjo',
        'Double T',
        'Enduro',
        'Jester',
        'Jester Classic',
        'Jester RR',
    },
    ['Obey'] = {
        '9F',
        '9F Cabrio',
        'Drafter',
        'Rocoto',
        'Omnis',
        'Tailgater',
        'Tailgater S',
    },
    ['Invetero'] = {
        'Coquette',
    },
    ['Ubermacht'] = {
        'Cypher',
        'Oracle',
        'Oracle XS',
        'Rebla GTS',
        'Revolter',
        'Sentinel',
        'Sentinel Classic',
        'Sentinel XS',
        'Zion',
        'Zion Classic',
    },
    ['Pfister'] = {
        'Astron',
        'Comet',
        'Comet Retro',
        'Comet S2',
        'Growler',
        'Neon',
    },
    ['Vapid'] = {
        'Benson',
        'Blade',
        'Bobcat',
        'Bullet',
        'Caracara',
        'Chino',
        'Clique',
        'Dominator',
        'Ellie',
        'Minivan',
        'Peyote',
        'Radius',
        'Sadler',
        'Sandking XL',
        'Speedo',
        'Stanier',
    },
    ['Grotti'] = {
        'Brioso',
        'GT500',
        'Stinger',
        'Stinger GT',
        'Bestia GTS',
        'Carbonizzare',
    },
    ['Ocelot'] = {
        'Jugular',
        'Lynx',
        'Locust',
        'Pariah',
        'F620',
    },
    ['Enus'] = {
        'Paragon',
        'Cognoscenti',
        'Cognoscenti 55',
        'Windsor',
        'Cognoscenti Cabrio',
        'Stafford',
        'Windsor Drop',
        'Super Diamond',
        'Huntley S',
    },
    ['Shyster'] = {
        'Fusilade',
    },
    ['Jobuilt'] = {
        'Rubble',
        'Phantom',
        'Hauler',
    },
    ['Zirconium'] = {
        'Journey',
        'Stratum',
    },
}

_vehNamesAll = {}

for k, v in pairs(_vehNames) do
    for k2, v2 in ipairs(v) do
        table.insert(_vehNamesAll, k .. ' ' .. v2)
    end
end