-- addDoorsListToConfig({
--     {
--         id = "ferrari_gate",
--         model = -1603817716,
--         coords = vector3(-1128.03, -1587.65, 3.44),
--         locked = true,
--         special = true,
--         --autoRate = 6.0,
--         restricted = {
--             { type = 'propertyData', key = 'gang', value = 'ferrari' },
--         },
--     },

--     {
--         model = 91564889,
--         coords = vector3(-1097.36, -1606.36, 4.95),
--         locked = true,
--         autoRate = 6.0,
--         restricted = {
--             { type = 'propertyData', key = 'gang', value = 'ferrari' },
--         },
--     },
--     {
--         model = 1526539404,
--         coords = vector3(-1057.45, -1652.79, 4.97),
--         locked = true,
--         autoRate = 6.0,
--         restricted = {
--             { type = 'propertyData', key = 'gang', value = 'ferrari' },
--         },
--     },

--     {
--         model = 91564889,
--         coords = vector3(-1096.73, -1673.64, 4.84),
--         locked = true,
--         autoRate = 6.0,
--         restricted = {
--             { type = 'propertyData', key = 'gang', value = 'ferrari' },
--         },
--     },

--     {
--         model = -502195954,
--         coords = vector3(-1104.66, -1638.48, 4.68),
--         locked = true,
--         autoRate = 6.0,
--         restricted = {
--             { type = 'propertyData', key = 'gang', value = 'ferrari' },
--         },
--     },
-- })