_itemsSource["schematics_base"] = {
	{
		name = "schematic_mp5",
		label = "Schematic: MP5",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.mp5,
	},
	{
		name = "schematic_smg_ammo",
		label = "Schematic: SMG Ammo",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.smg_ammo,
	},
	{
		name = "schematic_shotgun_ammo",
		label = "Schematic: Shotgun Ammo",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.shotgun_ammo,
	},
	{
		name = "schematic_thermite",
		label = "Schematic: Thermite",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.thermite,
	},
	{
		name = "schematic_blindfold",
		label = "Schematic: Blindfold",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.blindfold,
	},
	{
		name = "schematic_green_laptop",
		label = "Schematic: Green Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.green_laptop,
	},
	{
		name = "schematic_blue_laptop",
		label = "Schematic: Blue Laptop",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.blue_laptop,
	},
}