local _ran = false

_appData = {
	{
		name = "recyclebin",
		storeLabel = "Recycle Bin",
		label = "Recycle Bin",
		icon = "folder-open",
		icon = "trash-can",
		color = "#303030",
		params = "",
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
		fake = true,
	},
	{
		name = "settings",
		storeLabel = "Settings",
		label = "Settings",
		icon = "gear",
		color = "#303030",
		params = "",
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
	},
	{
		name = "files",
		storeLabel = "Files",
		label = "Files",
		icon = "folder-open",
		color = "#D8A71E",
		params = "",
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
		fake = true,
	},
	{
		name = "internet",
		storeLabel = "Interwebz",
		label = "Interwebz",
		icon = "globe",
		color = "#1db5e7",
		params = "",
		canUninstall = false,
		store = true,
		unread = 0,
		requirements = {},
		fake = true,
	},
	{
		name = "bizwiz",
		storeLabel = "BizWiz",
		label = "BizWiz",
		icon = "business-time",
		color = "#135dd8",
		--params = ":tab?",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "teams",
		storeLabel = "Teams",
		label = "Teams",
		icon = "people-group",
		color = "#00FF8A",
		--params = ":tab?",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
	},
	{
		name = "lsunderground",
		storeLabel = "LS UNDG",
		label = "LS UNDG",
		icon = "user-secret",
		color = "#E95200",
		params = ":tab?",
		hidden = false,
		canUninstall = true,
		store = true,
		unread = 0,
		restricted = {
			state = {"ACCESS_LSUNDERGROUND", "PHONE_VPN", "RACE_DONGLE"},
		},
	},
}
