TROLLY_TYPES = {
	{ hash = `hei_prop_hei_cash_trolly_01`, empty = `hei_prop_hei_cash_trolly_03`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_cash_low_trolly_01a`, empty = `mythic_prop_diamond_empty`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_cash_low_trolly_01b`, empty = `mythic_prop_diamond_emptyb`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_cash_low_trolly_01c`, empty = `mythic_prop_diamond_emptyc`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_ch_cash_trolly_01a`, empty = `mythic_prop_diamond_empty`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_ch_cash_trolly_01b`, empty = `mythic_prop_diamond_emptyb`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_ch_cash_trolly_01c`, empty = `mythic_prop_diamond_emptyc`, hand = `hei_prop_heist_cash_pile`, type = 'cash' },
	{ hash = `ch_prop_gold_trolly_01a`, empty = `mythic_prop_diamond_empty`, hand = `ch_prop_gold_bar_01a`, type = 'gold' },
	{ hash = `ch_prop_gold_trolly_01b`, empty = `mythic_prop_diamond_emptyb`, hand = `ch_prop_gold_bar_01a`, type = 'gold' },
	{ hash = `ch_prop_gold_trolly_01c`, empty = `mythic_prop_diamond_emptyc`, hand = `ch_prop_gold_bar_01a`, type = 'gold' },
	-- { hash = `ch_prop_diamond_trolly_01a`, empty = `mythic_prop_diamond_empty`, hand = `ch_prop_vault_dimaondbox_01a`, type = 'gems' },
	-- { hash = `ch_prop_diamond_trolly_01b`, empty = `mythic_prop_diamond_emptyb`, hand = `ch_prop_vault_dimaondbox_01a`, type = 'gems' },
	-- { hash = `ch_prop_diamond_trolly_01c`, empty = `mythic_prop_diamond_emptyc`, hand = `ch_prop_vault_dimaondbox_01a`, type = 'gems' },
}