_itemsSource["containers"] = {
	{
		name = "coffee_holder",
		label = "Drinks Holder",
		description = "Open Me!",
		price = 3,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 8,
		container = 19,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "foodbag",
		label = "Carrier Bag",
		description = "Open Me!",
		price = 4,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 15,
		container = 21,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "bento_box",
		label = "Bento Box",
		description = "Open Me!",
		price = 4,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "cardboard_box",
		label = "Box",
		description = "Open Me!",
		price = 8,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 50,
		container = 22,
		--durability = (60 * 60 * 24 * 60),
		state = "ANIM_box",
	},
	{
		name = "paper_bag",
		label = "Bag",
		description = "Open Me!",
		price = 6,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "burgershot_bag",
		label = "Burgershot Bag",
		description = "Have a Murder Meal!",
		price = 20,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 10,
		container = 20,
		--durability = (60 * 60 * 24 * 30),
	},
	{
		name = "card_holder",
		label = "Card Holder",
		description = "Store Those Cards!",
		price = 3,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 2,
		container = 91,
		--durability = (60 * 60 * 24 * 30),
	},
}