--[[
    rarity = [
        0 = nothing
        1 = common,
        2 = uncommon,
        3 = rare,
        4 = epic,
        5 = labor objective (Yellow)
    ]
]]

_itemsSource["fishing"] = {
    {
		name = "fishing_rod",
		label = "Fishing Rod",
        description = "Catch the Fishies",
		price = 750,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 3.5,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 30),
	},
	{
		name = "fishing_net",
		label = "Fishing Net",
        description = "Catch all the Fishies",
		price = 3000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5.0,
        isDestroyed = true,
        durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_bait_lugworm",
		label = "Lugworm Bait",
        description = "Marine Fish Bait",
		price = 10,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 7,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.1,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_bait_worm",
		label = "Worm Bait",
        description = "Fresh Water Fish Bait",
		price = 15,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 7,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.1,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_rainbowtrout",
		label = "Rainbow Trout",
        description = "A fish found in fresh water",
		price = 150,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 2.0,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_chub",
		label = "Chub",
        description = "A fish found in fresh water",
		price = 75,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 1.5,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_grasscarp",
		label = "Grass Carp",
        description = "A fish found in fresh water",
		price = 75,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 1.0,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_kelp",
		label = "Kelp Fish",
        description = "A fish found in the ocean",
		price = 90,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 1.5,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_bass",
		label = "Bass Fish",
        description = "A fish found in the ocean",
		price = 120,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 1.5,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_rockfish",
		label = "Rock Fish",
        description = "A fish found in the ocean",
		price = 150,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 1.0,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_lobster",
		label = "Lobster",
        description = "It's a lobster",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.75,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_tuna",
		label = "Tuna",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 2.5,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_bluefintuna",
		label = "Bluefin Tuna",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 25,
		type = 4,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3.5,
		durability = (60 * 60 * 24 * 60),
	},
    {
		name = "fishing_whale",
		label = "A Whale",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 4,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 100.0,
	},
    {
		name = "fishing_dolphin",
		label = "A Dolphin",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 4,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 50.0,
	},
    {
		name = "fishing_shark",
		label = "A Dolphin",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 4,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 75.0,
	},

	{
		name = "fishing_boot",
		label = "Soggy Boot",
        description = "I think someone is missing a boot",
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = 2,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 5.0,
	},
	{
		name = "fishing_bike",
		label = "Rusty Bicycle",
        description = "I don't think this is worth anything",
		price = 500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = false,
		weight = 25.0,
	},
	{
		name = "fishing_chest",
		label = "Old Chest",
        description = "Maybe There is Treasure!",
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 50.0,
		state = "ANIM_chest",
	},
	{
		name = "fishing_oil",
		label = "Fish Oil",
        description = "Eww",
		price = 250,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = false,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "fishing_seaweed",
		label = "Seaweed",
        description = "A salty snack",
		price = 30,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.01,
		durability = (60 * 60 * 24 * 60),
	},
}