_itemsSource['vehicles'] = {
    {
        name = "repairkit",
        label = "Repair Kit",
        description = "Fixes a vehicles engine so it can be driven again.",
        price = 350,
        isUsable = true,
        isRemoved = true,
        isStackable = 4,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 7),
    },
    {
        name = "repairkitadv",
        label = "Advanced Repair Kit",
        description = "Fixes a vehicles engine and tires so it can be driven again.",
        price = 600,
        isUsable = true,
        isRemoved = true,
        isStackable = 2,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 15,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 7),
    },
    {
        name = "carclean",
        label = "Car Cleaning Kit",
        description = "Make your car squeaky clean!",
        price = 425,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 10.0,
        durability = (60 * 60 * 24 * 14),
    },
    {
        name = "carpolish",
        label = "Car Polish",
        description = "Stop your car getting dirty!",
        price = 275,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 3.5,
        durability = (60 * 60 * 24 * 14),
    },
    {
        name = "carpolish_high",
        label = "Fantastic Car Wax",
        description = "Stop your car getting dirty and keep it sqeaky clean!",
        price = 375,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 3.5,
        durability = (60 * 60 * 24 * 14),
    },


	-- Shared Vehicle Repairs Parts
	{
        name = "repair_part_electronics",
        label = "Vehicle Electronics",
        description = "Vehicle Electronic Parts",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 4.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_axle",
        label = "Axle Parts",
        description = "Vehicle Axle Parts",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 5,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 7.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },


	-- Regular Repair Parts
	{
        name = "repair_part_rad",
        label = "Radiator",
        description = "Vehicle Radiator",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 4,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_transmission",
        label = "Transmission Parts",
        description = "Vehicle Transmission",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 2,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 9.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_brakes",
        label = "Brakes",
        description = "Vehicle Brakes",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 5,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 6.9,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_clutch",
        label = "Clutch",
        description = "Vehicle Clutch",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 8,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 5.75,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_injectors",
        label = "Fuel Injectors",
        description = "Vehicle Fuel Injectors",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 20,
        type = 3,
        rarity = 1,
        closeUi = true,
        metalic = true,
        weight = 0.75,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },

	-- High Grade Repair Parts
	{
        name = "repair_part_rad_hg",
        label = "HG Radiator",
        description = "(High Grade) Vehicle Radiator",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 4,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 5.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_transmission_hg",
        label = "HG Transmission Parts",
        description = "(High Grade) Vehicle Transmission Parts",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 2,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 9.5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_brakes_hg",
        label = "HG Brakes",
        description = "(High Grade) Vehicle Brakes",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 5,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 6.9,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_clutch_hg",
        label = "HG Clutch",
        description = "(High Grade) Vehicle Clutch",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 8,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 5.75,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
	{
        name = "repair_part_injectors_hg",
        label = "HG Fuel Injectors",
        description = "(High Grade) Vehicle Fuel Injectors",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 20,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 0.75,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },

    {
        name = "upgrade_turbo",
        label = "Turbo Upgrade",
        description = "Upgrade a Vehicles to a Turbo",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_engine1",
        label = "Engine Upgrade (1)",
        description = "Upgrade a Vehicles Engine to Level 1",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_engine2",
        label = "Engine Upgrade (2)",
        description = "Upgrade a Vehicles Engine to Level 2",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_engine3",
        label = "Engine Upgrade (3)",
        description = "Upgrade a Vehicles Engine to Level 3",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_engine4",
        label = "Engine Upgrade (4)",
        description = "Upgrade a Vehicles Engine to Level 4",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_brakes1",
        label = "Brakes Upgrade (1)",
        description = "Upgrade a Vehicles Brakes to Level 1",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_brakes2",
        label = "Brakes Upgrade (2)",
        description = "Upgrade a Vehicles Brakes to Level 2",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_brakes3",
        label = "Brakes Upgrade (3)",
        description = "Upgrade a Vehicles Brakes to Level 3",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_brakes4",
        label = "Brakes Upgrade (4)",
        description = "Upgrade a Vehicles Brakes to Level 4",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_transmission1",
        label = "Transmission Upgrade (1)",
        description = "Upgrade a Vehicles Transmission to Level 1",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_transmission2",
        label = "Transmission Upgrade (2)",
        description = "Upgrade a Vehicles Transmission to Level 2",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_transmission3",
        label = "Transmission Upgrade (3)",
        description = "Upgrade a Vehicles Transmission to Level 3",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_transmission4",
        label = "Transmission Upgrade (4)",
        description = "Upgrade a Vehicles Transmission to Level 4",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_suspension1",
        label = "Suspension Upgrade (1)",
        description = "Upgrade a Vehicles Suspension to Level 1",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_suspension2",
        label = "Suspension Upgrade (2)",
        description = "Upgrade a Vehicles Suspension to Level 2",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_suspension3",
        label = "Suspension Upgrade (3)",
        description = "Upgrade a Vehicles Suspension to Level 3",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },
    {
        name = "upgrade_suspension4",
        label = "Suspension Upgrade (4)",
        description = "Upgrade a Vehicles Suspension to Level 4",
        price = 1000,
        isUsable = true,
        isRemoved = true,
        isStackable = 10,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 1.0,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 90),
    },

    {
        name = "harness",
        label = "Vehicle Harness",
        description = "Stop flying to the moon!",
        price = 1150,
        isUsable = true,
        isRemoved = false,
        isStackable = false,
        isDestroyed = true,
        type = 3,
        rarity = 2,
        closeUi = true,
        metalic = true,
        weight = 2.5,
        --durability = (60 * 60 * 24 * 14),
    },
    {
        name = "nitrous",
        label = "Nitrous Oxide",
        description = "Copium",
        price = 2000,
        isUsable = true,
        isRemoved = false,
        isStackable = 5,
        isDestroyed = true,
        type = 3,
        rarity = 3,
        closeUi = true,
        metalic = true,
        weight = 3.0,
        staticMetadata = {
            Nitrous = 100,
        }
        --durability = (60 * 60 * 24 * 30),
    },
}