_rouletteTables = {
    [0] = {
        dealerVariation = 0,
        tableVariation = 0,
        highLimit = false,
        maxBet = 20000,
    },
    [1] = {
        dealerVariation = 0,
        tableVariation = 2,
        highLimit = false,
        maxBet = 50000,
    },
    [2] = {
        dealerVariation = 0,
        tableVariation = 3,
        highLimit = true,
        maxBet = 250000,
        isVIP = true,
    },
    [3] = {
        dealerVariation = 0,
        tableVariation = 3,
        highLimit = true,
        maxBet = 500000,
        isVIP = true,
    },
}

_rouletteTickToVal = {
    [1] = "00",
    [2] = "27",
    [3] = "10",
    [4] = "25",
    [5] = "29",
    [6] = "12",
    [7] = "8",
    [8] = "19",
    [9] = "31",
    [10] = "18",
    [11] = "6",
    [12] = "21",
    [13] = "33",
    [14] = "16",
    [15] = "4",
    [16] = "23",
    [17] = "35",
    [18] = "14",
    [19] = "2",
    [20] = "0",
    [21] = "28",
    [22] = "9",
    [23] = "26",
    [24] = "30",
    [25] = "11",
    [26] = "7",
    [27] = "20",
    [28] = "32",
    [29] = "17",
    [30] = "5",
    [31] = "22",
    [32] = "34",
    [33] = "15",
    [34] = "3",
    [35] = "24",
    [36] = "36",
    [37] = "13",
    [38] = "1"
}

_rouletteGroups = {
    Red = {
        ["1"] = true,
        ["3"] = true,
        ["5"] = true,
        ["7"] = true,
        ["9"] = true,
        ["12"] = true,
        ["14"] = true,
        ["16"] = true,
        ["18"] = true,
        ["19"] = true,
        ["21"] = true,
        ["23"] = true,
        ["25"] = true,
        ["27"] = true,
        ["30"] = true,
        ["32"] = true,
        ["34"] = true,
        ["36"] = true
    },
    Black = {
        ["2"] = true,
        ["4"] = true,
        ["6"] = true,
        ["8"] = true,
        ["10"] = true,
        ["11"] = true,
        ["13"] = true,
        ["15"] = true,
        ["17"] = true,
        ["20"] = true,
        ["22"] = true,
        ["24"] = true,
        ["26"] = true,
        ["28"] = true,
        ["29"] = true,
        ["31"] = true,
        ["33"] = true,
        ["35"] = true
    },
    Even = {
        ["2"] = true,
        ["4"] = true,
        ["6"] = true,
        ["8"] = true,
        ["10"] = true,
        ["12"] = true,
        ["14"] = true,
        ["16"] = true,
        ["18"] = true,
        ["20"] = true,
        ["22"] = true,
        ["24"] = true,
        ["26"] = true,
        ["28"] = true,
        ["30"] = true,
        ["32"] = true,
        ["34"] = true,
        ["36"] = true
    },
    Odd = {
        ["1"] = true,
        ["3"] = true,
        ["5"] = true,
        ["7"] = true,
        ["9"] = true,
        ["11"] = true,
        ["13"] = true,
        ["15"] = true,
        ["17"] = true,
        ["19"] = true,
        ["21"] = true,
        ["23"] = true,
        ["25"] = true,
        ["27"] = true,
        ["29"] = true,
        ["31"] = true,
        ["33"] = true,
        ["35"] = true
    },
    Low = {
        ["1"] = true,
        ["2"] = true,
        ["3"] = true,
        ["4"] = true,
        ["5"] = true,
        ["6"] = true,
        ["7"] = true,
        ["8"] = true,
        ["9"] = true,
        ["10"] = true,
        ["11"] = true,
        ["12"] = true,
        ["13"] = true,
        ["14"] = true,
        ["15"] = true,
        ["16"] = true,
        ["17"] = true,
        ["18"] = true
    },
    High = {
        ["19"] = true,
        ["20"] = true,
        ["21"] = true,
        ["22"] = true,
        ["23"] = true,
        ["24"] = true,
        ["25"] = true,
        ["26"] = true,
        ["27"] = true,
        ["28"] = true,
        ["29"] = true,
        ["30"] = true,
        ["31"] = true,
        ["32"] = true,
        ["33"] = true,
        ["34"] = true,
        ["35"] = true,
        ["36"] = true
    },
    First12 = {
        ["1"] = true,
        ["2"] = true,
        ["3"] = true,
        ["4"] = true,
        ["5"] = true,
        ["6"] = true,
        ["7"] = true,
        ["8"] = true,
        ["9"] = true,
        ["10"] = true,
        ["11"] = true,
        ["12"] = true
    },
    Second12 = {
        ["13"] = true,
        ["14"] = true,
        ["15"] = true,
        ["16"] = true,
        ["17"] = true,
        ["18"] = true,
        ["19"] = true,
        ["20"] = true,
        ["21"] = true,
        ["22"] = true,
        ["23"] = true,
        ["24"] = true
    },
    Third12 = {
        ["25"] = true,
        ["26"] = true,
        ["27"] = true,
        ["28"] = true,
        ["29"] = true,
        ["30"] = true,
        ["31"] = true,
        ["32"] = true,
        ["33"] = true,
        ["34"] = true,
        ["35"] = true,
        ["36"] = true
    },
    TwoToOne1 = {
        ["1"] = true,
        ["4"] = true,
        ["7"] = true,
        ["10"] = true,
        ["13"] = true,
        ["16"] = true,
        ["19"] = true,
        ["22"] = true,
        ["25"] = true,
        ["28"] = true,
        ["31"] = true,
        ["34"] = true
    },
    TwoToOne2 = {
        ["2"] = true,
        ["5"] = true,
        ["8"] = true,
        ["11"] = true,
        ["14"] = true,
        ["17"] = true,
        ["20"] = true,
        ["23"] = true,
        ["26"] = true,
        ["29"] = true,
        ["32"] = true,
        ["35"] = true
    },
    TwoToOne3 = {
        ["3"] = true,
        ["6"] = true,
        ["9"] = true,
        ["12"] = true,
        ["15"] = true,
        ["18"] = true,
        ["21"] = true,
        ["24"] = true,
        ["27"] = true,
        ["30"] = true,
        ["33"] = true,
        ["36"] = true
    },
    Row1 = { -- 51
        ["1"] = true,
        ["2"] = true,
        ["3"] = true,
    },
    Row2 = { -- 52
        ["4"] = true,
        ["5"] = true,
        ["6"] = true,
    },
    Row3 = { -- 53
        ["7"] = true,
        ["8"] = true,
        ["9"] = true,
    },
    Row4 = { -- 54
        ["10"] = true,
        ["11"] = true,
        ["12"] = true,
    },
    Row5 = { -- 55
        ["13"] = true,
        ["14"] = true,
        ["15"] = true,
    },
    Row6 = { -- 56
        ["16"] = true,
        ["17"] = true,
        ["18"] = true,
    },
    Row7 = { -- 57
        ["19"] = true,
        ["20"] = true,
        ["21"] = true,
    },
    Row8 = { -- 58
        ["22"] = true,
        ["23"] = true,
        ["24"] = true,
    },
    Row9 = { -- 59
        ["25"] = true,
        ["26"] = true,
        ["27"] = true,
    },
    Row10 = { -- 60
        ["28"] = true,
        ["29"] = true,
        ["30"] = true,
    },
    Row11 = { -- 61
        ["31"] = true,
        ["32"] = true,
        ["33"] = true,
    },
    Row12 = { -- 62
        ["34"] = true,
        ["35"] = true,
        ["36"] = true,
    },
}