_itemsSource['drugs'] = {
	{
		name = "weedseed_male",
		label = "Male Marijuana Seed",
		price = 100,
		isUsable = true,
		isStackable = 500,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
	},
	{
		name = "weedseed_female",
		label = "Female Marijuana Seed",
		price = 100,
		isUsable = true,
		isStackable = 500,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
	},
	{
		name = "rolling_paper",
		label = "Rolling Paper",
		price = 20,
		isUsable = true,
		isRemoved = false,
		isStackable = 30,
		isDestroyed = true,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "plastic_wrap",
		label = "Plastic Wrap",
		price = 50,
		isUsable = false,
		isRemoved = false,
		isStackable = 5,
		isDestroyed = true,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
	},
	{
		name = "baggy",
		label = "Empty Baggy",
		price = 50,
		isUsable = false,
		isRemoved = false,
		isStackable = 100,
		isDestroyed = true,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
	},
	{
		name = "weed_baggy",
		label = "Baggy of Weed",
		price = 100,
		isUsable = true,
		isRemoved = true,
		isStackable = 100,
		isDestroyed = true,
		type = 12,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "weed_bud",
		label = "Marijuana Bud",
		price = 50,
		isUsable = true,
		isRemoved = false,
		isStackable = 100,
		isDestroyed = true,
		type = 12,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.1,
	},
	{
		name = "weed_joint",
		label = "Joint",
		price = 25,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		isDestroyed = true,
		type = 12,
		rarity = 1,
		statusChange = {
			Remove = {
				PLAYER_HUNGER = 5,
			},
		},
		drugState = {
			type = 'weed',
			duration = (60 * 30),
		},
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "weed_brick",
		label = "Brick of Weed",
		price = 10000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = true,
		type = 12,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 10,
		state = "ANIM_weed",
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "oxy",
		label = "OxyContin",
		price = 100,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		isDestroyed = true,
		type = 12,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.1,
		statusChange = {
			Remove = {
				PLAYER_THIRST = 3,
			},
		},
		drugState = {
			type = 'oxy',
			duration = (60 * 60),
		},
		animConfig = {
			time = 2800,
			pbConfig = {
				label = "Popping Oxy",
				useWhileDead = false,
				canCancel = false,
				vehicle = false,
				disarm = false,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = false,
				animation = {
					animDict = "mp_suicide",
					anim = "pill",
					flags = 50,
				}
			},
		},
	},
	{
		name = "contraband",
		label = "Mysterious Box",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 14,
		rarity = 5,
		closeUi = false,
		metalic = false,
		weight = 10,
		state = "ANIM_box",
	},
}