_itemsSource["evidence"] = {
	{
		name = "evidence-paint",
		label = "Paint Fragment",
		price = 0,
		isUsable = true,
		isStackable = false,
		type = 8,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "evidence-projectile",
		label = "Bullet Projectile",
		description = "Can be matched to the weapon it was fired from",
		price = 0,
		isUsable = true,
		isStackable = false,
		type = 8,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "evidence-casing",
		label = "Bullet Casing",
		description = "Identifies the type of ammo used",
		price = 0,
		isUsable = true,
		isStackable = false,
		type = 8,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "evidence-dna",
		label = "DNA Sample",
		price = 0,
		isUsable = true,
		isStackable = false,
		type = 8,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
}
