_itemsSource["robbery_tools"] = {
	{
		name = "electronics_kit",
		label = "Electronics Kit",
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "safecrack_kit",
		label = "Safe Cracking Kit",
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "hack_usb",
		label = "Easy Hacker 3000",
		description = "So easy, a caveman could maybe do it.",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "sequencer",
		label = "Yellow Keypad Sequencer",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "green_sequencer",
		label = "Green Keypad Sequencer",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "blue_sequencer",
		label = "Blue Keypad Sequencer",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "red_sequencer",
		label = "Red Keypad Sequencer",
		price = 25000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "thermite",
		label = "Thermite Charge",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "bobcat_charge",
		label = "Breach Charge",
		description = "Kinda like thermite, but more ... explosive",
		iconOverride = "thermite",
		price = 1000,
		isThrowable = false,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60),
		type = 7,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = "green_dongle",
		label = "USB Drive",
		state = "DONGLE_GREEN",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "blue_dongle",
		label = "USB Drive",
		state = "DONGLE_BLUE",
		price = 10000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 3,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "red_dongle",
		label = "USB Drive",
		state = "DONGLE_RED",
		price = 25000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
    {
		name = "yellow_dongle",
		label = "USB Drive",
		state = "DONGLE_YELLOW",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 3),
	},
	{
		name = "green_laptop",
		label = "Laptop",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "blue_laptop",
		label = "Laptop",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "red_laptop",
		label = "Laptop",
		price = 25000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
    {
		name = "yellow_laptop",
		label = "Laptop",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
}
