_itemsSource["robbery_tools"] = {
	{
		name = "electronics_kit",
		label = "Electronics Kit",
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = 5,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "adv_electronics_kit",
		label = "Hacking Device",
		description = "<i>Marked For Police Seizure</i>",
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = 5,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 28),
	},
	{
		name = "drill",
		label = "Drill",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "safecrack_kit",
		label = "Safe Cracking Kit",
		description = "<i>Marked For Police Seizure</i>",
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "hack_usb",
		label = "Easy Hacker 3000",
		description = "So easy, a caveman could maybe do it.",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "sequencer",
		label = "Yellow Keypad Sequencer",
		description = "<i>Marked For Police Seizure</i>",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "green_sequencer",
		label = "Green Keypad Sequencer",
		description = "<i>Marked For Police Seizure</i>",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "blue_sequencer",
		label = "Blue Keypad Sequencer",
		description = "<i>Marked For Police Seizure</i>",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "red_sequencer",
		label = "Red Keypad Sequencer",
		description = "<i>Marked For Police Seizure</i>",
		price = 25000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "thermite",
		label = "Thermite Charge",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "bobcat_charge",
		label = "Breach Charge",
		description = "Kinda like thermite, but more ... explosive",
		iconOverride = "thermite",
		price = 1000,
		isThrowable = false,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60),
		type = 7,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = "green_dongle",
		label = "USB Drive (Green)",
		description = "<i>Marked For Police Seizure</i>",
		state = "DONGLE_GREEN",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "blue_dongle",
		label = "USB Drive (Blue)",
		description = "<i>Marked For Police Seizure</i>",
		state = "DONGLE_BLUE",
		price = 10000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 3,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "purple_dongle",
		label = "USB Drive (Purple)",
		description = "<i>Marked For Police Seizure</i>",
		state = "DONGLE_PURPLE",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "red_dongle",
		label = "USB Drive (Red)",
		description = "<i>Marked For Police Seizure</i>",
		state = "DONGLE_RED",
		price = 25000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
    {
		name = "yellow_dongle",
		label = "USB Drive (Yellow)",
		description = "<i>Marked For Police Seizure</i>",
		state = "DONGLE_YELLOW",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = false,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 3),
	},
	{
		name = "green_laptop",
		label = "Laptop (Green)",
		description = "<i>Marked For Police Seizure</i>",
		price = 5000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "blue_laptop",
		label = "Laptop (Blue)",
		description = "<i>Marked For Police Seizure</i>",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "purple_laptop",
		label = "Laptop (Purple)",
		description = "<i>Marked For Police Seizure</i>",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "red_laptop",
		label = "Laptop (Red)",
		description = "<i>Marked For Police Seizure</i>",
		price = 25000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
    {
		name = "yellow_laptop",
		label = "Laptop (Yellow)",
		description = "<i>Marked For Police Seizure</i>",
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 24 * 7),
	},
    {
		name = "paleto_access_codes",
		label = "Access Codes",
		description = "<i>Marked For Police Seizure</i>",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
		durability = (60 * 60 * 4),
	},
	{
		name = "boosting_tracking_disabler",
		label = "Tracker Hacker Device",
		description = "<i>Marked For Police Seizure</i>",
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = 5,
		isDestroyed = true,
		type = 7,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 28),
	},
}
