table.insert(_defaultJobData, {
    Type = 'Government',
    LastUpdated = 1654715416,
    Id = 'police',
    Name = 'Police',
    Salary = 1200,
    SalaryTier = 1,
    Workplaces = {
        {
            Id = 'lspd',
            Name = 'Los Santos Police Department',
            Grades = {
                {
                    Id = 'chief',
                    Name = 'Chief',
                    Level = 99,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'achief',
                    Name = 'Assistant Chief',
                    Level = 90,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'dchief',
                    Name = 'Deputy Chief',
                    Level = 80,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'commander',
                    Name = 'Commander',
                    Level = 75,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'captain',
                    Name = 'Captain',
                    Level = 70,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'lieutenant',
                    Name = 'Lieutenant',
                    Level = 60,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'sergeant',
                    Name = 'Sergeant',
                    Level = 50,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'corporal',
                    Name = 'Corporal',
                    Level = 20,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'sofficer',
                    Name = 'Senior Officer',
                    Level = 15,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'officer',
                    Name = 'Officer',
                    Level = 10,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'pofficer',
                    Name = 'Probationary Officer',
                    Level = 2,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'cadet',
                    Name = 'Cadet',
                    Level = 1,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                    },
                },
            }
        },
        {
            Id = 'lscso',
            Name = 'Blaine County Sheriff\'s Office',
            Grades = {
                {
                    Id = 'sheriff',
                    Name = 'Sheriff',
                    Level = 99,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'usheriff',
                    Name = 'Undersheriff',
                    Level = 90,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'asheriff',
                    Name = 'Assistant Sheriff',
                    Level = 80,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'commander',
                    Name = 'Commander',
                    Level = 75,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'captain',
                    Name = 'Captain',
                    Level = 70,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'lieutenant',
                    Name = 'Lieutenant',
                    Level = 60,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
                {
                    Id = 'sergeant',
                    Name = 'Sergeant',
                    Level = 50,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'corporal',
                    Name = 'Corporal',
                    Level = 20,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'sdeputy',
                    Name = 'Senior Deputy',
                    Level = 15,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'deputy',
                    Name = 'Deputy',
                    Level = 10,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'pdeputy',
                    Name = 'Probationary Deputy',
                    Level = 2,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,
                    },
                },
                {
                    Id = 'cadet',
                    Name = 'Cadet',
                    Level = 1,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        JOB_STORAGE = true,
                        impound = true,
                    },
                },
            }
        },
        {
            Id = 'sasp',
            Name = 'San Andreas State Police',
            Grades = {
                {
                    Id = 'trooper',
                    Name = 'Trooper',
                    Level = 99,
                    Permissions = {
                        ems_alerts = true,
                        police_alerts = true,
                        FLEET_VEHICLES_0 = true,
                        FLEET_VEHICLES_1 = true,
                        FLEET_VEHICLES_2 = true,
                        FLEET_VEHICLES_3 = true,
                        FLEET_VEHICLES_4 = true,
                        FLEET_MANAGEMENT = true,
                        PD_HIGH_COMMAND = true,
                        PD_COMMAND = true,
                        MDT_HIRE = true,
                        MDT_FIRE = true,
                        MDT_PROMOTE = true,
                        MDT_EDIT_EMPLOYEE = true,
                        MDT_INCIDENT_REPORT_VIEW = true,
                        MDT_INCIDENT_REPORT_CREATE = true,
                        MDT_CIVILIAN_REPORT_VIEW = true,
                        MDT_CIVILIAN_REPORT_CREATE = true,
                        MDT_POLICE_DISCIPLINARY_REPORTS = true,
                        MDT_POLICE_FTO_REPORTS = true,
                        JOB_STORAGE = true,
                        impound = true,
                        impound_police = true,

                        BANK_ACCOUNT_MANAGE = true,
                        BANK_ACCOUNT_DEPOSIT = true,
                        BANK_ACCOUNT_WITHDRAW = true,
                        BANK_ACCOUNT_TRANSACTIONS = true,
                        BANK_ACCOUNT_BALANCE = true,
                    },
                },
            }
        },
    }
})