_defDmg = {
	["HEAD"] = { label = "Head", causeLimp = false, isDamaged = false, severity = 0 },
	["NECK"] = { label = "Neck", causeLimp = false, isDamaged = false, severity = 0 },
	["SPINE"] = { label = "Spine", causeLimp = true, isDamaged = false, severity = 0 },
	["UPPER_BODY"] = { label = "Upper Body", causeLimp = false, isDamaged = false, severity = 0 },
	["LOWER_BODY"] = { label = "Lower Body", causeLimp = true, isDamaged = false, severity = 0 },
	["LARM"] = { label = "Left Arm", causeLimp = false, isDamaged = false, severity = 0 },
	["LHAND"] = { label = "Left Hand", causeLimp = false, isDamaged = false, severity = 0 },
	["LFINGER"] = { label = "Left Hand Fingers", causeLimp = false, isDamaged = false, severity = 0 },
	["LLEG"] = { label = "Left Leg", causeLimp = true, isDamaged = false, severity = 0 },
	["LFOOT"] = { label = "Left Foot", causeLimp = true, isDamaged = false, severity = 0 },
	["RARM"] = { label = "Right Arm", causeLimp = false, isDamaged = false, severity = 0 },
	["RHAND"] = { label = "Right Hand", causeLimp = false, isDamaged = false, severity = 0 },
	["RFINGER"] = { label = "Right Hand Fingers", causeLimp = false, isDamaged = false, severity = 0 },
	["RLEG"] = { label = "Right Leg", causeLimp = true, isDamaged = false, severity = 0 },
	["RFOOT"] = { label = "Right Foot", causeLimp = true, isDamaged = false, severity = 0 },
}