_billboardConfig = {
    ["billboard_lshighway1"] = {
        category = "billboard",
        name = "Los Santos Freeway #1 - Gallivanter",
        originalDictionary = "ch3_rd2b_billboard01",
        originalTexture = "ch3_rd2b_billboard01",
        width = 1024,
        height = 512,
        coords = vector3(1357.440, 675.301, 92.395),
        range = 100.0,
    },
    ["billboard_lshighway2"] = {
        category = "billboard",
        name = "Los Santos Freeway #2 - Lowdown",
        originalDictionary = "ch2_03b_cg2_03b_bb",
        originalTexture = "ch2_03b_bb_lowdown",
        width = 1024,
        height = 512,
        coords = vector3(1647.589, 1324.136, 97.961),
        range = 100.0,
    },
    ["business_ferrari"] = {
        category = "ferrari",
        name = "Ferrari Pawn TVs",
        originalDictionary = "ba_prop_battle_club_screen",
        originalTexture = "script_rt_club_tv",
        width = 1024,
        height = 512,
        coords = vector3(177.605, -1318.068, 29.363),
        range = 25.0,
        job = "ferrari_pawn",
    },
    -- ["business_casino_insidetrack"] = {
    --     category = "casino",
    --     name = "Casino Inside Track",
    --     originalDictionary = "vw_vwint01_betting_screen",
    --     originalTexture = "casinoscreen_02",
    --     width = 1920,
    --     height = 1080,
    --     coords = vector3(994.775, 73.272, 69.660),
    --     range = 25.0,
    --     job = "casino",
    -- }
    ["business_gallery_01"] = {
        category = "gallery",
        name = "Art Gallery 1",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_legtrio2_d",
        width = 1024,
        height = 512,
        coords = vector3(-443.114, 28.612, 46.680),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_02"] = {
        category = "gallery",
        name = "Art Gallery 2",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_vault_painting_01j_d",
        width = 512,
        height = 512,
        coords = vector3(-420.508, 43.884, 46.231),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_03"] = {
        category = "gallery",
        name = "Art Gallery 3",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_vault_painting_01h_d",
        width = 512,
        height = 512,
        coords = vector3(-423.681, 43.900, 46.231),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_04"] = {
        category = "gallery",
        name = "Art Gallery 4",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_vault_painting_01f_d",
        width = 512,
        height = 512,
        coords = vector3(-426.748, 44.502, 46.231),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_05"] = {
        category = "gallery",
        name = "Art Gallery 5",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_vault_painting_01g_d",
        width = 512,
        height = 512,
        coords = vector3(-434.257, 45.232, 46.231),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_06"] = {
        category = "gallery",
        name = "Art Gallery 6",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_cowboy_d",
        width = 1024,
        height = 512,
        coords = vector3(-458.94, 25.44, 46.68),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_07"] = {
        category = "gallery",
        name = "Art Gallery 7",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_cluckin_d",
        width = 512,
        height = 512,
        coords = vector3(-453.496, 25.399, 47.155),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_08"] = {
        category = "gallery",
        name = "Art Gallery 8",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_vault_painting_01b_d",
        width = 512,
        height = 512,
        coords = vector3(-419.545, 42.142, 46.231),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_09"] = {
        category = "gallery",
        name = "Art Gallery 9",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_ufo2_d",
        width = 512,
        height = 512,
        coords = vector3(-452.057, 31.146, 46.680),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_10"] = {
        category = "gallery",
        name = "Art Gallery 10",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "prop_pokerscene_d",
        width = 512,
        height = 512,
        coords = vector3(-453.555, 40.368, 46.681),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_11"] = {
        category = "gallery",
        name = "Art Gallery 11",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "nutt_gallery_bridge_02",
        width = 512,
        height = 512,
        coords = vector3(-453.555, 40.368, 46.681),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_12"] = {
        category = "gallery",
        name = "Art Gallery 12",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "nutt_gallery_b6",
        width = 512,
        height = 512,
        coords = vector3(-423.939, 41.731, 52.869),
        range = 15.0,
        job = "sagma",
    },
    ["business_gallery_13"] = {
        category = "gallery",
        name = "Art Gallery 13",
        originalDictionary = "nutt_gallery_painting_txt",
        originalTexture = "nutt_gallery_b12",
        width = 512,
        height = 512,
        coords = vector3(-416.138, 41.091, 52.869),
        range = 15.0,
        job = "sagma",
    },
    ["business_dynasty"] = {
        category = "dynasty",
        name = "Dynasty 8 TV",
        originalDictionary = "prop_tv_flat_01",
        originalTexture = "script_rt_tvscreen",
        width = 1024,
        height = 512,
        coords = vector3(-719.502, 266.998, 84.131),
        range = 25.0,
        job = "realestate",
    },
    ["business_tuner"] = {
        category = "tuner",
        name = "Tuner TV",
        originalDictionary = "prop_tv_flat_michael",
        originalTexture = "script_rt_tvscreen",
        width = 1024,
        height = 512,
        coords = vector3(138.146, -3019.756, 7.041),
        range = 25.0,
        job = "tuna",
    },
}

_billboardRegex = [[((https?:\/\/(www\.)?(i\.)?imgur\.com\/[a-zA-Z\d]+)(\.png|\.jpg|\.jpeg|\.gif)?)]]