export const Zones = {
	ZONE_TORSO: 'Torso',
	ZONE_HEAD: 'Head',
	ZONE_LEFT_ARM: 'Left Arm',
	ZONE_RIGHT_ARM: 'Right ARm',
	ZONE_LEFT_LEG: 'Left Leg',
	ZONE_RIGHT_LEG: 'Right Leg',
	// ZONE_UNKNOWN: '',
	// ZONE_NONE: '',
};

export const Tattoos = [
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_000',
		HashNameMale: 'MP_Airraces_Tattoo_000_M',
		HashNameFemale: 'MP_Airraces_Tattoo_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_001',
		HashNameMale: 'MP_Airraces_Tattoo_001_M',
		HashNameFemale: 'MP_Airraces_Tattoo_001_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_002',
		HashNameMale: 'MP_Airraces_Tattoo_002_M',
		HashNameFemale: 'MP_Airraces_Tattoo_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_003',
		HashNameMale: 'MP_Airraces_Tattoo_003_M',
		HashNameFemale: 'MP_Airraces_Tattoo_003_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_004',
		HashNameMale: 'MP_Airraces_Tattoo_004_M',
		HashNameFemale: 'MP_Airraces_Tattoo_004_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_005',
		HashNameMale: 'MP_Airraces_Tattoo_005_M',
		HashNameFemale: 'MP_Airraces_Tattoo_005_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_006',
		HashNameMale: 'MP_Airraces_Tattoo_006_M',
		HashNameFemale: 'MP_Airraces_Tattoo_006_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpairraces_overlays',
		Name: 'TAT_AR_007',
		HashNameMale: 'MP_Airraces_Tattoo_007_M',
		HashNameFemale: 'MP_Airraces_Tattoo_007_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_018',
		HashNameMale: 'MP_Bea_M_Back_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_019',
		HashNameMale: 'MP_Bea_M_Chest_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_020',
		HashNameMale: 'MP_Bea_M_Chest_001',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_021',
		HashNameMale: 'MP_Bea_M_Head_000',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_022',
		HashNameMale: 'MP_Bea_M_Head_001',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_031',
		HashNameMale: 'MP_Bea_M_Head_002',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_027',
		HashNameMale: 'MP_Bea_M_Lleg_000',
		HashNameFemale: '',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_025',
		HashNameMale: 'MP_Bea_M_Rleg_000',
		HashNameFemale: '',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_026',
		HashNameMale: 'MP_Bea_M_RArm_000',
		HashNameFemale: '',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_024',
		HashNameMale: 'MP_Bea_M_LArm_000',
		HashNameFemale: '',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_017',
		HashNameMale: 'MP_Bea_M_LArm_001',
		HashNameFemale: '',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_028',
		HashNameMale: 'MP_Bea_M_Neck_000',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_029',
		HashNameMale: 'MP_Bea_M_Neck_001',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_030',
		HashNameMale: 'MP_Bea_M_RArm_001',
		HashNameFemale: '',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_023',
		HashNameMale: 'MP_Bea_M_Stom_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_032',
		HashNameMale: 'MP_Bea_M_Stom_001',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_003',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Back_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_001',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Back_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_005',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Back_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_012',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Chest_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_013',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Chest_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_000',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Chest_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_006',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_RSide_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_007',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_RLeg_000',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_015',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_RArm_001',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_008',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Neck_000',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_011',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Should_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_004',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Should_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_014',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Stom_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_009',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Stom_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_010',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_Stom_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_002',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_LArm_000',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbeach_overlays',
		Name: 'TAT_BB_016',
		HashNameMale: '',
		HashNameFemale: 'MP_Bea_F_LArm_001',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_000',
		HashNameMale: 'MP_MP_Biker_Tat_000_M',
		HashNameFemale: 'MP_MP_Biker_Tat_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_001',
		HashNameMale: 'MP_MP_Biker_Tat_001_M',
		HashNameFemale: 'MP_MP_Biker_Tat_001_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_002',
		HashNameMale: 'MP_MP_Biker_Tat_002_M',
		HashNameFemale: 'MP_MP_Biker_Tat_002_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_003',
		HashNameMale: 'MP_MP_Biker_Tat_003_M',
		HashNameFemale: 'MP_MP_Biker_Tat_003_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_004',
		HashNameMale: 'MP_MP_Biker_Tat_004_M',
		HashNameFemale: 'MP_MP_Biker_Tat_004_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_005',
		HashNameMale: 'MP_MP_Biker_Tat_005_M',
		HashNameFemale: 'MP_MP_Biker_Tat_005_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_006',
		HashNameMale: 'MP_MP_Biker_Tat_006_M',
		HashNameFemale: 'MP_MP_Biker_Tat_006_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_007',
		HashNameMale: 'MP_MP_Biker_Tat_007_M',
		HashNameFemale: 'MP_MP_Biker_Tat_007_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_008',
		HashNameMale: 'MP_MP_Biker_Tat_008_M',
		HashNameFemale: 'MP_MP_Biker_Tat_008_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_009',
		HashNameMale: 'MP_MP_Biker_Tat_009_M',
		HashNameFemale: 'MP_MP_Biker_Tat_009_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_010',
		HashNameMale: 'MP_MP_Biker_Tat_010_M',
		HashNameFemale: 'MP_MP_Biker_Tat_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_011',
		HashNameMale: 'MP_MP_Biker_Tat_011_M',
		HashNameFemale: 'MP_MP_Biker_Tat_011_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_012',
		HashNameMale: 'MP_MP_Biker_Tat_012_M',
		HashNameFemale: 'MP_MP_Biker_Tat_012_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_013',
		HashNameMale: 'MP_MP_Biker_Tat_013_M',
		HashNameFemale: 'MP_MP_Biker_Tat_013_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_014',
		HashNameMale: 'MP_MP_Biker_Tat_014_M',
		HashNameFemale: 'MP_MP_Biker_Tat_014_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_015',
		HashNameMale: 'MP_MP_Biker_Tat_015_M',
		HashNameFemale: 'MP_MP_Biker_Tat_015_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_016',
		HashNameMale: 'MP_MP_Biker_Tat_016_M',
		HashNameFemale: 'MP_MP_Biker_Tat_016_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_017',
		HashNameMale: 'MP_MP_Biker_Tat_017_M',
		HashNameFemale: 'MP_MP_Biker_Tat_017_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_018',
		HashNameMale: 'MP_MP_Biker_Tat_018_M',
		HashNameFemale: 'MP_MP_Biker_Tat_018_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_019',
		HashNameMale: 'MP_MP_Biker_Tat_019_M',
		HashNameFemale: 'MP_MP_Biker_Tat_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_020',
		HashNameMale: 'MP_MP_Biker_Tat_020_M',
		HashNameFemale: 'MP_MP_Biker_Tat_020_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_021',
		HashNameMale: 'MP_MP_Biker_Tat_021_M',
		HashNameFemale: 'MP_MP_Biker_Tat_021_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_022',
		HashNameMale: 'MP_MP_Biker_Tat_022_M',
		HashNameFemale: 'MP_MP_Biker_Tat_022_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_023',
		HashNameMale: 'MP_MP_Biker_Tat_023_M',
		HashNameFemale: 'MP_MP_Biker_Tat_023_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_024',
		HashNameMale: 'MP_MP_Biker_Tat_024_M',
		HashNameFemale: 'MP_MP_Biker_Tat_024_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_025',
		HashNameMale: 'MP_MP_Biker_Tat_025_M',
		HashNameFemale: 'MP_MP_Biker_Tat_025_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_026',
		HashNameMale: 'MP_MP_Biker_Tat_026_M',
		HashNameFemale: 'MP_MP_Biker_Tat_026_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_027',
		HashNameMale: 'MP_MP_Biker_Tat_027_M',
		HashNameFemale: 'MP_MP_Biker_Tat_027_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_028',
		HashNameMale: 'MP_MP_Biker_Tat_028_M',
		HashNameFemale: 'MP_MP_Biker_Tat_028_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_029',
		HashNameMale: 'MP_MP_Biker_Tat_029_M',
		HashNameFemale: 'MP_MP_Biker_Tat_029_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_030',
		HashNameMale: 'MP_MP_Biker_Tat_030_M',
		HashNameFemale: 'MP_MP_Biker_Tat_030_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_031',
		HashNameMale: 'MP_MP_Biker_Tat_031_M',
		HashNameFemale: 'MP_MP_Biker_Tat_031_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_032',
		HashNameMale: 'MP_MP_Biker_Tat_032_M',
		HashNameFemale: 'MP_MP_Biker_Tat_032_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_033',
		HashNameMale: 'MP_MP_Biker_Tat_033_M',
		HashNameFemale: 'MP_MP_Biker_Tat_033_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_034',
		HashNameMale: 'MP_MP_Biker_Tat_034_M',
		HashNameFemale: 'MP_MP_Biker_Tat_034_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_035',
		HashNameMale: 'MP_MP_Biker_Tat_035_M',
		HashNameFemale: 'MP_MP_Biker_Tat_035_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_036',
		HashNameMale: 'MP_MP_Biker_Tat_036_M',
		HashNameFemale: 'MP_MP_Biker_Tat_036_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_037',
		HashNameMale: 'MP_MP_Biker_Tat_037_M',
		HashNameFemale: 'MP_MP_Biker_Tat_037_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_038',
		HashNameMale: 'MP_MP_Biker_Tat_038_M',
		HashNameFemale: 'MP_MP_Biker_Tat_038_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_039',
		HashNameMale: 'MP_MP_Biker_Tat_039_M',
		HashNameFemale: 'MP_MP_Biker_Tat_039_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_040',
		HashNameMale: 'MP_MP_Biker_Tat_040_M',
		HashNameFemale: 'MP_MP_Biker_Tat_040_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_041',
		HashNameMale: 'MP_MP_Biker_Tat_041_M',
		HashNameFemale: 'MP_MP_Biker_Tat_041_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_042',
		HashNameMale: 'MP_MP_Biker_Tat_042_M',
		HashNameFemale: 'MP_MP_Biker_Tat_042_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_043',
		HashNameMale: 'MP_MP_Biker_Tat_043_M',
		HashNameFemale: 'MP_MP_Biker_Tat_043_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_044',
		HashNameMale: 'MP_MP_Biker_Tat_044_M',
		HashNameFemale: 'MP_MP_Biker_Tat_044_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_045',
		HashNameMale: 'MP_MP_Biker_Tat_045_M',
		HashNameFemale: 'MP_MP_Biker_Tat_045_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_046',
		HashNameMale: 'MP_MP_Biker_Tat_046_M',
		HashNameFemale: 'MP_MP_Biker_Tat_046_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_047',
		HashNameMale: 'MP_MP_Biker_Tat_047_M',
		HashNameFemale: 'MP_MP_Biker_Tat_047_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_048',
		HashNameMale: 'MP_MP_Biker_Tat_048_M',
		HashNameFemale: 'MP_MP_Biker_Tat_048_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_049',
		HashNameMale: 'MP_MP_Biker_Tat_049_M',
		HashNameFemale: 'MP_MP_Biker_Tat_049_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_050',
		HashNameMale: 'MP_MP_Biker_Tat_050_M',
		HashNameFemale: 'MP_MP_Biker_Tat_050_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_051',
		HashNameMale: 'MP_MP_Biker_Tat_051_M',
		HashNameFemale: 'MP_MP_Biker_Tat_051_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_052',
		HashNameMale: 'MP_MP_Biker_Tat_052_M',
		HashNameFemale: 'MP_MP_Biker_Tat_052_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_053',
		HashNameMale: 'MP_MP_Biker_Tat_053_M',
		HashNameFemale: 'MP_MP_Biker_Tat_053_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_054',
		HashNameMale: 'MP_MP_Biker_Tat_054_M',
		HashNameFemale: 'MP_MP_Biker_Tat_054_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_055',
		HashNameMale: 'MP_MP_Biker_Tat_055_M',
		HashNameFemale: 'MP_MP_Biker_Tat_055_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_056',
		HashNameMale: 'MP_MP_Biker_Tat_056_M',
		HashNameFemale: 'MP_MP_Biker_Tat_056_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_057',
		HashNameMale: 'MP_MP_Biker_Tat_057_M',
		HashNameFemale: 'MP_MP_Biker_Tat_057_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_058',
		HashNameMale: 'MP_MP_Biker_Tat_058_M',
		HashNameFemale: 'MP_MP_Biker_Tat_058_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_059',
		HashNameMale: 'MP_MP_Biker_Tat_059_M',
		HashNameFemale: 'MP_MP_Biker_Tat_059_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbiker_overlays',
		Name: 'TAT_BI_060',
		HashNameMale: 'MP_MP_Biker_Tat_060_M',
		HashNameFemale: 'MP_MP_Biker_Tat_060_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_005',
		HashNameMale: 'MP_Buis_M_Neck_000',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_006',
		HashNameMale: 'MP_Buis_M_Neck_001',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_007',
		HashNameMale: 'MP_Buis_M_Neck_002',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_008',
		HashNameMale: 'MP_Buis_M_Neck_003',
		HashNameFemale: '',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_003',
		HashNameMale: 'MP_Buis_M_LeftArm_000',
		HashNameFemale: '',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_004',
		HashNameMale: 'MP_Buis_M_LeftArm_001',
		HashNameFemale: '',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_009',
		HashNameMale: 'MP_Buis_M_RightArm_000',
		HashNameFemale: '',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_010',
		HashNameMale: 'MP_Buis_M_RightArm_001',
		HashNameFemale: '',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_011',
		HashNameMale: 'MP_Buis_M_Stomach_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_001',
		HashNameMale: 'MP_Buis_M_Chest_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_002',
		HashNameMale: 'MP_Buis_M_Chest_001',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_000',
		HashNameMale: 'MP_Buis_M_Back_000',
		HashNameFemale: '',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_002',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Chest_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_003',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Chest_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_004',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Chest_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_011',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Stom_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_012',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Stom_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_013',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Stom_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_000',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Back_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_001',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Back_001',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_007',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Neck_000',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_008',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_Neck_001',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_009',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_RArm_000',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_005',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_LArm_000',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_006',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_LLeg_000',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpbusiness_overlays',
		Name: 'TAT_BUS_F_010',
		HashNameMale: '',
		HashNameFemale: 'MP_Buis_F_RLeg_000',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_000',
		HashNameMale: 'MP_Christmas2017_Tattoo_000_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_001',
		HashNameMale: 'MP_Christmas2017_Tattoo_001_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_001_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_002',
		HashNameMale: 'MP_Christmas2017_Tattoo_002_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_003',
		HashNameMale: 'MP_Christmas2017_Tattoo_003_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_003_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_004',
		HashNameMale: 'MP_Christmas2017_Tattoo_004_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_004_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_005',
		HashNameMale: 'MP_Christmas2017_Tattoo_005_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_005_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_006',
		HashNameMale: 'MP_Christmas2017_Tattoo_006_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_006_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_007',
		HashNameMale: 'MP_Christmas2017_Tattoo_007_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_007_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_008',
		HashNameMale: 'MP_Christmas2017_Tattoo_008_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_008_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_009',
		HashNameMale: 'MP_Christmas2017_Tattoo_009_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_009_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_010',
		HashNameMale: 'MP_Christmas2017_Tattoo_010_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_011',
		HashNameMale: 'MP_Christmas2017_Tattoo_011_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_011_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_012',
		HashNameMale: 'MP_Christmas2017_Tattoo_012_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_012_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_013',
		HashNameMale: 'MP_Christmas2017_Tattoo_013_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_013_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_014',
		HashNameMale: 'MP_Christmas2017_Tattoo_014_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_014_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_015',
		HashNameMale: 'MP_Christmas2017_Tattoo_015_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_015_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_016',
		HashNameMale: 'MP_Christmas2017_Tattoo_016_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_016_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_017',
		HashNameMale: 'MP_Christmas2017_Tattoo_017_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_017_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_018',
		HashNameMale: 'MP_Christmas2017_Tattoo_018_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_018_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_019',
		HashNameMale: 'MP_Christmas2017_Tattoo_019_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_020',
		HashNameMale: 'MP_Christmas2017_Tattoo_020_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_020_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_021',
		HashNameMale: 'MP_Christmas2017_Tattoo_021_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_021_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_022',
		HashNameMale: 'MP_Christmas2017_Tattoo_022_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_022_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_023',
		HashNameMale: 'MP_Christmas2017_Tattoo_023_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_023_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_024',
		HashNameMale: 'MP_Christmas2017_Tattoo_024_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_024_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_025',
		HashNameMale: 'MP_Christmas2017_Tattoo_025_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_025_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_026',
		HashNameMale: 'MP_Christmas2017_Tattoo_026_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_026_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_027',
		HashNameMale: 'MP_Christmas2017_Tattoo_027_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_027_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_028',
		HashNameMale: 'MP_Christmas2017_Tattoo_028_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_028_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2017_overlays',
		Name: 'TAT_H27_029',
		HashNameMale: 'MP_Christmas2017_Tattoo_029_M',
		HashNameFemale: 'MP_Christmas2017_Tattoo_029_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2018_overlays',
		Name: 'TAT_AW_000',
		HashNameMale: 'MP_Christmas2018_Tat_000_M',
		HashNameFemale: 'MP_Christmas2018_Tat_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_000',
		HashNameMale: 'MP_Xmas2_M_Tat_000',
		HashNameFemale: 'MP_Xmas2_F_Tat_000',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_001',
		HashNameMale: 'MP_Xmas2_M_Tat_001',
		HashNameFemale: 'MP_Xmas2_F_Tat_001',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_002',
		HashNameMale: 'MP_Xmas2_M_Tat_002',
		HashNameFemale: 'MP_Xmas2_F_Tat_002',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_003',
		HashNameMale: 'MP_Xmas2_M_Tat_003',
		HashNameFemale: 'MP_Xmas2_F_Tat_003',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_004',
		HashNameMale: 'MP_Xmas2_M_Tat_004',
		HashNameFemale: 'MP_Xmas2_F_Tat_004',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_005',
		HashNameMale: 'MP_Xmas2_M_Tat_005',
		HashNameFemale: 'MP_Xmas2_F_Tat_005',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_006',
		HashNameMale: 'MP_Xmas2_M_Tat_006',
		HashNameFemale: 'MP_Xmas2_F_Tat_006',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_007',
		HashNameMale: 'MP_Xmas2_M_Tat_007',
		HashNameFemale: 'MP_Xmas2_F_Tat_007',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_008',
		HashNameMale: 'MP_Xmas2_M_Tat_008',
		HashNameFemale: 'MP_Xmas2_F_Tat_008',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_009',
		HashNameMale: 'MP_Xmas2_M_Tat_009',
		HashNameFemale: 'MP_Xmas2_F_Tat_009',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_010',
		HashNameMale: 'MP_Xmas2_M_Tat_010',
		HashNameFemale: 'MP_Xmas2_F_Tat_010',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_011',
		HashNameMale: 'MP_Xmas2_M_Tat_011',
		HashNameFemale: 'MP_Xmas2_F_Tat_011',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_012',
		HashNameMale: 'MP_Xmas2_M_Tat_012',
		HashNameFemale: 'MP_Xmas2_F_Tat_012',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_013',
		HashNameMale: 'MP_Xmas2_M_Tat_013',
		HashNameFemale: 'MP_Xmas2_F_Tat_013',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_014',
		HashNameMale: 'MP_Xmas2_M_Tat_014',
		HashNameFemale: 'MP_Xmas2_F_Tat_014',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_015',
		HashNameMale: 'MP_Xmas2_M_Tat_015',
		HashNameFemale: 'MP_Xmas2_F_Tat_015',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_016',
		HashNameMale: 'MP_Xmas2_M_Tat_016',
		HashNameFemale: 'MP_Xmas2_F_Tat_016',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_017',
		HashNameMale: 'MP_Xmas2_M_Tat_017',
		HashNameFemale: 'MP_Xmas2_F_Tat_017',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_018',
		HashNameMale: 'MP_Xmas2_M_Tat_018',
		HashNameFemale: 'MP_Xmas2_F_Tat_018',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_019',
		HashNameMale: 'MP_Xmas2_M_Tat_019',
		HashNameFemale: 'MP_Xmas2_F_Tat_019',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_020',
		HashNameMale: 'MP_Xmas2_M_Tat_020',
		HashNameFemale: 'MP_Xmas2_F_Tat_020',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_021',
		HashNameMale: 'MP_Xmas2_M_Tat_021',
		HashNameFemale: 'MP_Xmas2_F_Tat_021',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_022',
		HashNameMale: 'MP_Xmas2_M_Tat_022',
		HashNameFemale: 'MP_Xmas2_F_Tat_022',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_023',
		HashNameMale: 'MP_Xmas2_M_Tat_023',
		HashNameFemale: 'MP_Xmas2_F_Tat_023',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_024',
		HashNameMale: 'MP_Xmas2_M_Tat_024',
		HashNameFemale: 'MP_Xmas2_F_Tat_024',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_025',
		HashNameMale: 'MP_Xmas2_M_Tat_025',
		HashNameFemale: 'MP_Xmas2_F_Tat_025',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_026',
		HashNameMale: 'MP_Xmas2_M_Tat_026',
		HashNameFemale: 'MP_Xmas2_F_Tat_026',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_027',
		HashNameMale: 'MP_Xmas2_M_Tat_027',
		HashNameFemale: 'MP_Xmas2_F_Tat_027',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_028',
		HashNameMale: 'MP_Xmas2_M_Tat_028',
		HashNameFemale: 'MP_Xmas2_F_Tat_028',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpchristmas2_overlays',
		Name: 'TAT_X2_029',
		HashNameMale: 'MP_Xmas2_M_Tat_029',
		HashNameFemale: 'MP_Xmas2_F_Tat_029',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_000',
		HashNameMale: 'MP_Gunrunning_Tattoo_000_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_001',
		HashNameMale: 'MP_Gunrunning_Tattoo_001_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_001_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_002',
		HashNameMale: 'MP_Gunrunning_Tattoo_002_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_002_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_003',
		HashNameMale: 'MP_Gunrunning_Tattoo_003_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_003_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_004',
		HashNameMale: 'MP_Gunrunning_Tattoo_004_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_004_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_005',
		HashNameMale: 'MP_Gunrunning_Tattoo_005_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_005_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_006',
		HashNameMale: 'MP_Gunrunning_Tattoo_006_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_006_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_007',
		HashNameMale: 'MP_Gunrunning_Tattoo_007_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_007_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_008',
		HashNameMale: 'MP_Gunrunning_Tattoo_008_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_008_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_009',
		HashNameMale: 'MP_Gunrunning_Tattoo_009_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_009_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_010',
		HashNameMale: 'MP_Gunrunning_Tattoo_010_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_011',
		HashNameMale: 'MP_Gunrunning_Tattoo_011_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_011_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_012',
		HashNameMale: 'MP_Gunrunning_Tattoo_012_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_012_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_013',
		HashNameMale: 'MP_Gunrunning_Tattoo_013_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_013_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_014',
		HashNameMale: 'MP_Gunrunning_Tattoo_014_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_014_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_015',
		HashNameMale: 'MP_Gunrunning_Tattoo_015_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_015_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_016',
		HashNameMale: 'MP_Gunrunning_Tattoo_016_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_016_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_017',
		HashNameMale: 'MP_Gunrunning_Tattoo_017_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_017_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_018',
		HashNameMale: 'MP_Gunrunning_Tattoo_018_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_018_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_019',
		HashNameMale: 'MP_Gunrunning_Tattoo_019_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_020',
		HashNameMale: 'MP_Gunrunning_Tattoo_020_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_020_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_021',
		HashNameMale: 'MP_Gunrunning_Tattoo_021_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_021_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_022',
		HashNameMale: 'MP_Gunrunning_Tattoo_022_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_022_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_023',
		HashNameMale: 'MP_Gunrunning_Tattoo_023_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_023_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_024',
		HashNameMale: 'MP_Gunrunning_Tattoo_024_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_024_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_025',
		HashNameMale: 'MP_Gunrunning_Tattoo_025_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_025_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_026',
		HashNameMale: 'MP_Gunrunning_Tattoo_026_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_026_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_027',
		HashNameMale: 'MP_Gunrunning_Tattoo_027_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_027_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_028',
		HashNameMale: 'MP_Gunrunning_Tattoo_028_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_028_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_029',
		HashNameMale: 'MP_Gunrunning_Tattoo_029_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_029_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpgunrunning_overlays',
		Name: 'TAT_GR_030',
		HashNameMale: 'MP_Gunrunning_Tattoo_030_M',
		HashNameFemale: 'MP_Gunrunning_Tattoo_030_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_000',
		HashNameMale: 'FM_Hip_M_Tat_000',
		HashNameFemale: 'FM_Hip_F_Tat_000',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_001',
		HashNameMale: 'FM_Hip_M_Tat_001',
		HashNameFemale: 'FM_Hip_F_Tat_001',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_002',
		HashNameMale: 'FM_Hip_M_Tat_002',
		HashNameFemale: 'FM_Hip_F_Tat_002',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_003',
		HashNameMale: 'FM_Hip_M_Tat_003',
		HashNameFemale: 'FM_Hip_F_Tat_003',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_004',
		HashNameMale: 'FM_Hip_M_Tat_004',
		HashNameFemale: 'FM_Hip_F_Tat_004',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_005',
		HashNameMale: 'FM_Hip_M_Tat_005',
		HashNameFemale: 'FM_Hip_F_Tat_005',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_006',
		HashNameMale: 'FM_Hip_M_Tat_006',
		HashNameFemale: 'FM_Hip_F_Tat_006',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_007',
		HashNameMale: 'FM_Hip_M_Tat_007',
		HashNameFemale: 'FM_Hip_F_Tat_007',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_008',
		HashNameMale: 'FM_Hip_M_Tat_008',
		HashNameFemale: 'FM_Hip_F_Tat_008',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_009',
		HashNameMale: 'FM_Hip_M_Tat_009',
		HashNameFemale: 'FM_Hip_F_Tat_009',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_010',
		HashNameMale: 'FM_Hip_M_Tat_010',
		HashNameFemale: 'FM_Hip_F_Tat_010',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_011',
		HashNameMale: 'FM_Hip_M_Tat_011',
		HashNameFemale: 'FM_Hip_F_Tat_011',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_012',
		HashNameMale: 'FM_Hip_M_Tat_012',
		HashNameFemale: 'FM_Hip_F_Tat_012',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_013',
		HashNameMale: 'FM_Hip_M_Tat_013',
		HashNameFemale: 'FM_Hip_F_Tat_013',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_014',
		HashNameMale: 'FM_Hip_M_Tat_014',
		HashNameFemale: 'FM_Hip_F_Tat_014',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_015',
		HashNameMale: 'FM_Hip_M_Tat_015',
		HashNameFemale: 'FM_Hip_F_Tat_015',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_016',
		HashNameMale: 'FM_Hip_M_Tat_016',
		HashNameFemale: 'FM_Hip_F_Tat_016',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_017',
		HashNameMale: 'FM_Hip_M_Tat_017',
		HashNameFemale: 'FM_Hip_F_Tat_017',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_018',
		HashNameMale: 'FM_Hip_M_Tat_018',
		HashNameFemale: 'FM_Hip_F_Tat_018',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_019',
		HashNameMale: 'FM_Hip_M_Tat_019',
		HashNameFemale: 'FM_Hip_F_Tat_019',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_020',
		HashNameMale: 'FM_Hip_M_Tat_020',
		HashNameFemale: 'FM_Hip_F_Tat_020',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_021',
		HashNameMale: 'FM_Hip_M_Tat_021',
		HashNameFemale: 'FM_Hip_F_Tat_021',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_022',
		HashNameMale: 'FM_Hip_M_Tat_022',
		HashNameFemale: 'FM_Hip_F_Tat_022',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_023',
		HashNameMale: 'FM_Hip_M_Tat_023',
		HashNameFemale: 'FM_Hip_F_Tat_023',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_024',
		HashNameMale: 'FM_Hip_M_Tat_024',
		HashNameFemale: 'FM_Hip_F_Tat_024',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_025',
		HashNameMale: 'FM_Hip_M_Tat_025',
		HashNameFemale: 'FM_Hip_F_Tat_025',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_026',
		HashNameMale: 'FM_Hip_M_Tat_026',
		HashNameFemale: 'FM_Hip_F_Tat_026',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_027',
		HashNameMale: 'FM_Hip_M_Tat_027',
		HashNameFemale: 'FM_Hip_F_Tat_027',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_028',
		HashNameMale: 'FM_Hip_M_Tat_028',
		HashNameFemale: 'FM_Hip_F_Tat_028',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_029',
		HashNameMale: 'FM_Hip_M_Tat_029',
		HashNameFemale: 'FM_Hip_F_Tat_029',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_030',
		HashNameMale: 'FM_Hip_M_Tat_030',
		HashNameFemale: 'FM_Hip_F_Tat_030',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_031',
		HashNameMale: 'FM_Hip_M_Tat_031',
		HashNameFemale: 'FM_Hip_F_Tat_031',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_032',
		HashNameMale: 'FM_Hip_M_Tat_032',
		HashNameFemale: 'FM_Hip_F_Tat_032',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_033',
		HashNameMale: 'FM_Hip_M_Tat_033',
		HashNameFemale: 'FM_Hip_F_Tat_033',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_034',
		HashNameMale: 'FM_Hip_M_Tat_034',
		HashNameFemale: 'FM_Hip_F_Tat_034',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_035',
		HashNameMale: 'FM_Hip_M_Tat_035',
		HashNameFemale: 'FM_Hip_F_Tat_035',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_036',
		HashNameMale: 'FM_Hip_M_Tat_036',
		HashNameFemale: 'FM_Hip_F_Tat_036',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_037',
		HashNameMale: 'FM_Hip_M_Tat_037',
		HashNameFemale: 'FM_Hip_F_Tat_037',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_038',
		HashNameMale: 'FM_Hip_M_Tat_038',
		HashNameFemale: 'FM_Hip_F_Tat_038',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_039',
		HashNameMale: 'FM_Hip_M_Tat_039',
		HashNameFemale: 'FM_Hip_F_Tat_039',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_040',
		HashNameMale: 'FM_Hip_M_Tat_040',
		HashNameFemale: 'FM_Hip_F_Tat_040',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_041',
		HashNameMale: 'FM_Hip_M_Tat_041',
		HashNameFemale: 'FM_Hip_F_Tat_041',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_042',
		HashNameMale: 'FM_Hip_M_Tat_042',
		HashNameFemale: 'FM_Hip_F_Tat_042',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_043',
		HashNameMale: 'FM_Hip_M_Tat_043',
		HashNameFemale: 'FM_Hip_F_Tat_043',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_044',
		HashNameMale: 'FM_Hip_M_Tat_044',
		HashNameFemale: 'FM_Hip_F_Tat_044',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_045',
		HashNameMale: 'FM_Hip_M_Tat_045',
		HashNameFemale: 'FM_Hip_F_Tat_045',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_046',
		HashNameMale: 'FM_Hip_M_Tat_046',
		HashNameFemale: 'FM_Hip_F_Tat_046',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_047',
		HashNameMale: 'FM_Hip_M_Tat_047',
		HashNameFemale: 'FM_Hip_F_Tat_047',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mphipster_overlays',
		Name: 'TAT_HP_048',
		HashNameMale: 'FM_Hip_M_Tat_048',
		HashNameFemale: 'FM_Hip_F_Tat_048',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_000',
		HashNameMale: 'MP_MP_ImportExport_Tat_000_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_001',
		HashNameMale: 'MP_MP_ImportExport_Tat_001_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_001_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_002',
		HashNameMale: 'MP_MP_ImportExport_Tat_002_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_003',
		HashNameMale: 'MP_MP_ImportExport_Tat_003_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_003_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_004',
		HashNameMale: 'MP_MP_ImportExport_Tat_004_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_004_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_005',
		HashNameMale: 'MP_MP_ImportExport_Tat_005_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_005_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_006',
		HashNameMale: 'MP_MP_ImportExport_Tat_006_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_006_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_007',
		HashNameMale: 'MP_MP_ImportExport_Tat_007_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_007_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_008',
		HashNameMale: 'MP_MP_ImportExport_Tat_008_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_008_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_009',
		HashNameMale: 'MP_MP_ImportExport_Tat_009_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_009_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_010',
		HashNameMale: 'MP_MP_ImportExport_Tat_010_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpimportexport_overlays',
		Name: 'TAT_IE_011',
		HashNameMale: 'MP_MP_ImportExport_Tat_011_M',
		HashNameFemale: 'MP_MP_ImportExport_Tat_011_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_000',
		HashNameMale: 'MP_LR_Tat_000_M',
		HashNameFemale: 'MP_LR_Tat_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_003',
		HashNameMale: 'MP_LR_Tat_003_M',
		HashNameFemale: 'MP_LR_Tat_003_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_006',
		HashNameMale: 'MP_LR_Tat_006_M',
		HashNameFemale: 'MP_LR_Tat_006_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_008',
		HashNameMale: 'MP_LR_Tat_008_M',
		HashNameFemale: 'MP_LR_Tat_008_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_011',
		HashNameMale: 'MP_LR_Tat_011_M',
		HashNameFemale: 'MP_LR_Tat_011_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_012',
		HashNameMale: 'MP_LR_Tat_012_M',
		HashNameFemale: 'MP_LR_Tat_012_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_016',
		HashNameMale: 'MP_LR_Tat_016_M',
		HashNameFemale: 'MP_LR_Tat_016_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_018',
		HashNameMale: 'MP_LR_Tat_018_M',
		HashNameFemale: 'MP_LR_Tat_018_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_019',
		HashNameMale: 'MP_LR_Tat_019_M',
		HashNameFemale: 'MP_LR_Tat_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_022',
		HashNameMale: 'MP_LR_Tat_022_M',
		HashNameFemale: 'MP_LR_Tat_022_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_028',
		HashNameMale: 'MP_LR_Tat_028_M',
		HashNameFemale: 'MP_LR_Tat_028_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_029',
		HashNameMale: 'MP_LR_Tat_029_M',
		HashNameFemale: 'MP_LR_Tat_029_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_030',
		HashNameMale: 'MP_LR_Tat_030_M',
		HashNameFemale: 'MP_LR_Tat_030_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_031',
		HashNameMale: 'MP_LR_Tat_031_M',
		HashNameFemale: 'MP_LR_Tat_031_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_032',
		HashNameMale: 'MP_LR_Tat_032_M',
		HashNameFemale: 'MP_LR_Tat_032_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider2_overlays',
		Name: 'TAT_S2_035',
		HashNameMale: 'MP_LR_Tat_035_M',
		HashNameFemale: 'MP_LR_Tat_035_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_001',
		HashNameMale: 'MP_LR_Tat_001_M',
		HashNameFemale: 'MP_LR_Tat_001_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_002',
		HashNameMale: 'MP_LR_Tat_002_M',
		HashNameFemale: 'MP_LR_Tat_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_004',
		HashNameMale: 'MP_LR_Tat_004_M',
		HashNameFemale: 'MP_LR_Tat_004_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_005',
		HashNameMale: 'MP_LR_Tat_005_M',
		HashNameFemale: 'MP_LR_Tat_005_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_007',
		HashNameMale: 'MP_LR_Tat_007_M',
		HashNameFemale: 'MP_LR_Tat_007_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_009',
		HashNameMale: 'MP_LR_Tat_009_M',
		HashNameFemale: 'MP_LR_Tat_009_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_010',
		HashNameMale: 'MP_LR_Tat_010_M',
		HashNameFemale: 'MP_LR_Tat_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_013',
		HashNameMale: 'MP_LR_Tat_013_M',
		HashNameFemale: 'MP_LR_Tat_013_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_014',
		HashNameMale: 'MP_LR_Tat_014_M',
		HashNameFemale: 'MP_LR_Tat_014_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_015',
		HashNameMale: 'MP_LR_Tat_015_M',
		HashNameFemale: 'MP_LR_Tat_015_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_017',
		HashNameMale: 'MP_LR_Tat_017_M',
		HashNameFemale: 'MP_LR_Tat_017_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_020',
		HashNameMale: 'MP_LR_Tat_020_M',
		HashNameFemale: 'MP_LR_Tat_020_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_021',
		HashNameMale: 'MP_LR_Tat_021_M',
		HashNameFemale: 'MP_LR_Tat_021_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_023',
		HashNameMale: 'MP_LR_Tat_023_M',
		HashNameFemale: 'MP_LR_Tat_023_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_026',
		HashNameMale: 'MP_LR_Tat_026_M',
		HashNameFemale: 'MP_LR_Tat_026_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_027',
		HashNameMale: 'MP_LR_Tat_027_M',
		HashNameFemale: 'MP_LR_Tat_027_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mplowrider_overlays',
		Name: 'TAT_S1_033',
		HashNameMale: 'MP_LR_Tat_033_M',
		HashNameFemale: 'MP_LR_Tat_033_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_002',
		HashNameMale: 'MP_LUXE_TAT_002_M',
		HashNameFemale: 'MP_LUXE_TAT_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_005',
		HashNameMale: 'MP_LUXE_TAT_005_M',
		HashNameFemale: 'MP_LUXE_TAT_005_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_010',
		HashNameMale: 'MP_LUXE_TAT_010_M',
		HashNameFemale: 'MP_LUXE_TAT_010_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_011',
		HashNameMale: 'MP_LUXE_TAT_011_M',
		HashNameFemale: 'MP_LUXE_TAT_011_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_012',
		HashNameMale: 'MP_LUXE_TAT_012_M',
		HashNameFemale: 'MP_LUXE_TAT_012_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_016',
		HashNameMale: 'MP_LUXE_TAT_016_M',
		HashNameFemale: 'MP_LUXE_TAT_016_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_017',
		HashNameMale: 'MP_LUXE_TAT_017_M',
		HashNameFemale: 'MP_LUXE_TAT_017_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_018',
		HashNameMale: 'MP_LUXE_TAT_018_M',
		HashNameFemale: 'MP_LUXE_TAT_018_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_022',
		HashNameMale: 'MP_LUXE_TAT_022_M',
		HashNameFemale: 'MP_LUXE_TAT_022_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_023',
		HashNameMale: 'MP_LUXE_TAT_023_M',
		HashNameFemale: 'MP_LUXE_TAT_023_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_025',
		HashNameMale: 'MP_LUXE_TAT_025_M',
		HashNameFemale: 'MP_LUXE_TAT_025_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_026',
		HashNameMale: 'MP_LUXE_TAT_026_M',
		HashNameFemale: 'MP_LUXE_TAT_026_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_027',
		HashNameMale: 'MP_LUXE_TAT_027_M',
		HashNameFemale: 'MP_LUXE_TAT_027_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_028',
		HashNameMale: 'MP_LUXE_TAT_028_M',
		HashNameFemale: 'MP_LUXE_TAT_028_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_029',
		HashNameMale: 'MP_LUXE_TAT_029_M',
		HashNameFemale: 'MP_LUXE_TAT_029_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_030',
		HashNameMale: 'MP_LUXE_TAT_030_M',
		HashNameFemale: 'MP_LUXE_TAT_030_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe2_overlays',
		Name: 'TAT_L2_031',
		HashNameMale: 'MP_LUXE_TAT_031_M',
		HashNameFemale: 'MP_LUXE_TAT_031_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_000',
		HashNameMale: 'MP_LUXE_TAT_000_M',
		HashNameFemale: 'MP_LUXE_TAT_000_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_001',
		HashNameMale: 'MP_LUXE_TAT_001_M',
		HashNameFemale: 'MP_LUXE_TAT_001_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_003',
		HashNameMale: 'MP_LUXE_TAT_003_M',
		HashNameFemale: 'MP_LUXE_TAT_003_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_004',
		HashNameMale: 'MP_LUXE_TAT_004_M',
		HashNameFemale: 'MP_LUXE_TAT_004_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_006',
		HashNameMale: 'MP_LUXE_TAT_006_M',
		HashNameFemale: 'MP_LUXE_TAT_006_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_007',
		HashNameMale: 'MP_LUXE_TAT_007_M',
		HashNameFemale: 'MP_LUXE_TAT_007_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_008',
		HashNameMale: 'MP_LUXE_TAT_008_M',
		HashNameFemale: 'MP_LUXE_TAT_008_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_009',
		HashNameMale: 'MP_LUXE_TAT_009_M',
		HashNameFemale: 'MP_LUXE_TAT_009_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_013',
		HashNameMale: 'MP_LUXE_TAT_013_M',
		HashNameFemale: 'MP_LUXE_TAT_013_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_014',
		HashNameMale: 'MP_LUXE_TAT_014_M',
		HashNameFemale: 'MP_LUXE_TAT_014_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_015',
		HashNameMale: 'MP_LUXE_TAT_015_M',
		HashNameFemale: 'MP_LUXE_TAT_015_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_019',
		HashNameMale: 'MP_LUXE_TAT_019_M',
		HashNameFemale: 'MP_LUXE_TAT_019_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_020',
		HashNameMale: 'MP_LUXE_TAT_020_M',
		HashNameFemale: 'MP_LUXE_TAT_020_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_021',
		HashNameMale: 'MP_LUXE_TAT_021_M',
		HashNameFemale: 'MP_LUXE_TAT_021_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpluxe_overlays',
		Name: 'TAT_LX_024',
		HashNameMale: 'MP_LUXE_TAT_024_M',
		HashNameFemale: 'MP_LUXE_TAT_024_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_000',
		HashNameMale: 'MP_Smuggler_Tattoo_000_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_000_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_001',
		HashNameMale: 'MP_Smuggler_Tattoo_001_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_001_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_002',
		HashNameMale: 'MP_Smuggler_Tattoo_002_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_002_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_003',
		HashNameMale: 'MP_Smuggler_Tattoo_003_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_003_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_004',
		HashNameMale: 'MP_Smuggler_Tattoo_004_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_004_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_005',
		HashNameMale: 'MP_Smuggler_Tattoo_005_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_005_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_006',
		HashNameMale: 'MP_Smuggler_Tattoo_006_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_006_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_007',
		HashNameMale: 'MP_Smuggler_Tattoo_007_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_007_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_008',
		HashNameMale: 'MP_Smuggler_Tattoo_008_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_008_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_009',
		HashNameMale: 'MP_Smuggler_Tattoo_009_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_009_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_010',
		HashNameMale: 'MP_Smuggler_Tattoo_010_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_010_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_011',
		HashNameMale: 'MP_Smuggler_Tattoo_011_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_011_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_012',
		HashNameMale: 'MP_Smuggler_Tattoo_012_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_012_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_013',
		HashNameMale: 'MP_Smuggler_Tattoo_013_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_013_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_014',
		HashNameMale: 'MP_Smuggler_Tattoo_014_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_014_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_015',
		HashNameMale: 'MP_Smuggler_Tattoo_015_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_015_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_016',
		HashNameMale: 'MP_Smuggler_Tattoo_016_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_016_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_017',
		HashNameMale: 'MP_Smuggler_Tattoo_017_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_017_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_018',
		HashNameMale: 'MP_Smuggler_Tattoo_018_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_018_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_019',
		HashNameMale: 'MP_Smuggler_Tattoo_019_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_020',
		HashNameMale: 'MP_Smuggler_Tattoo_020_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_020_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_021',
		HashNameMale: 'MP_Smuggler_Tattoo_021_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_021_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_022',
		HashNameMale: 'MP_Smuggler_Tattoo_022_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_022_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_023',
		HashNameMale: 'MP_Smuggler_Tattoo_023_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_023_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_024',
		HashNameMale: 'MP_Smuggler_Tattoo_024_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_024_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpsmuggler_overlays',
		Name: 'TAT_SM_025',
		HashNameMale: 'MP_Smuggler_Tattoo_025_M',
		HashNameFemale: 'MP_Smuggler_Tattoo_025_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_000',
		HashNameMale: 'MP_MP_Stunt_Tat_000_M',
		HashNameFemale: 'MP_MP_Stunt_Tat_000_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_001',
		HashNameMale: 'MP_MP_Stunt_tat_001_M',
		HashNameFemale: 'MP_MP_Stunt_tat_001_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_002',
		HashNameMale: 'MP_MP_Stunt_tat_002_M',
		HashNameFemale: 'MP_MP_Stunt_tat_002_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_003',
		HashNameMale: 'MP_MP_Stunt_tat_003_M',
		HashNameFemale: 'MP_MP_Stunt_tat_003_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_004',
		HashNameMale: 'MP_MP_Stunt_tat_004_M',
		HashNameFemale: 'MP_MP_Stunt_tat_004_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_005',
		HashNameMale: 'MP_MP_Stunt_tat_005_M',
		HashNameFemale: 'MP_MP_Stunt_tat_005_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_006',
		HashNameMale: 'MP_MP_Stunt_tat_006_M',
		HashNameFemale: 'MP_MP_Stunt_tat_006_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_007',
		HashNameMale: 'MP_MP_Stunt_tat_007_M',
		HashNameFemale: 'MP_MP_Stunt_tat_007_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_008',
		HashNameMale: 'MP_MP_Stunt_tat_008_M',
		HashNameFemale: 'MP_MP_Stunt_tat_008_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_009',
		HashNameMale: 'MP_MP_Stunt_tat_009_M',
		HashNameFemale: 'MP_MP_Stunt_tat_009_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_010',
		HashNameMale: 'MP_MP_Stunt_tat_010_M',
		HashNameFemale: 'MP_MP_Stunt_tat_010_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_011',
		HashNameMale: 'MP_MP_Stunt_tat_011_M',
		HashNameFemale: 'MP_MP_Stunt_tat_011_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_012',
		HashNameMale: 'MP_MP_Stunt_tat_012_M',
		HashNameFemale: 'MP_MP_Stunt_tat_012_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_013',
		HashNameMale: 'MP_MP_Stunt_tat_013_M',
		HashNameFemale: 'MP_MP_Stunt_tat_013_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_014',
		HashNameMale: 'MP_MP_Stunt_tat_014_M',
		HashNameFemale: 'MP_MP_Stunt_tat_014_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_015',
		HashNameMale: 'MP_MP_Stunt_tat_015_M',
		HashNameFemale: 'MP_MP_Stunt_tat_015_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_016',
		HashNameMale: 'MP_MP_Stunt_tat_016_M',
		HashNameFemale: 'MP_MP_Stunt_tat_016_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_017',
		HashNameMale: 'MP_MP_Stunt_tat_017_M',
		HashNameFemale: 'MP_MP_Stunt_tat_017_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_018',
		HashNameMale: 'MP_MP_Stunt_tat_018_M',
		HashNameFemale: 'MP_MP_Stunt_tat_018_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_019',
		HashNameMale: 'MP_MP_Stunt_tat_019_M',
		HashNameFemale: 'MP_MP_Stunt_tat_019_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_020',
		HashNameMale: 'MP_MP_Stunt_tat_020_M',
		HashNameFemale: 'MP_MP_Stunt_tat_020_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_021',
		HashNameMale: 'MP_MP_Stunt_tat_021_M',
		HashNameFemale: 'MP_MP_Stunt_tat_021_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_022',
		HashNameMale: 'MP_MP_Stunt_tat_022_M',
		HashNameFemale: 'MP_MP_Stunt_tat_022_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_023',
		HashNameMale: 'MP_MP_Stunt_tat_023_M',
		HashNameFemale: 'MP_MP_Stunt_tat_023_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_024',
		HashNameMale: 'MP_MP_Stunt_tat_024_M',
		HashNameFemale: 'MP_MP_Stunt_tat_024_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_025',
		HashNameMale: 'MP_MP_Stunt_tat_025_M',
		HashNameFemale: 'MP_MP_Stunt_tat_025_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_026',
		HashNameMale: 'MP_MP_Stunt_tat_026_M',
		HashNameFemale: 'MP_MP_Stunt_tat_026_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_027',
		HashNameMale: 'MP_MP_Stunt_tat_027_M',
		HashNameFemale: 'MP_MP_Stunt_tat_027_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_028',
		HashNameMale: 'MP_MP_Stunt_tat_028_M',
		HashNameFemale: 'MP_MP_Stunt_tat_028_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_029',
		HashNameMale: 'MP_MP_Stunt_tat_029_M',
		HashNameFemale: 'MP_MP_Stunt_tat_029_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_030',
		HashNameMale: 'MP_MP_Stunt_tat_030_M',
		HashNameFemale: 'MP_MP_Stunt_tat_030_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_031',
		HashNameMale: 'MP_MP_Stunt_tat_031_M',
		HashNameFemale: 'MP_MP_Stunt_tat_031_F',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_032',
		HashNameMale: 'MP_MP_Stunt_tat_032_M',
		HashNameFemale: 'MP_MP_Stunt_tat_032_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_033',
		HashNameMale: 'MP_MP_Stunt_tat_033_M',
		HashNameFemale: 'MP_MP_Stunt_tat_033_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_034',
		HashNameMale: 'MP_MP_Stunt_tat_034_M',
		HashNameFemale: 'MP_MP_Stunt_tat_034_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_035',
		HashNameMale: 'MP_MP_Stunt_tat_035_M',
		HashNameFemale: 'MP_MP_Stunt_tat_035_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_036',
		HashNameMale: 'MP_MP_Stunt_tat_036_M',
		HashNameFemale: 'MP_MP_Stunt_tat_036_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_037',
		HashNameMale: 'MP_MP_Stunt_tat_037_M',
		HashNameFemale: 'MP_MP_Stunt_tat_037_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_038',
		HashNameMale: 'MP_MP_Stunt_tat_038_M',
		HashNameFemale: 'MP_MP_Stunt_tat_038_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_039',
		HashNameMale: 'MP_MP_Stunt_tat_039_M',
		HashNameFemale: 'MP_MP_Stunt_tat_039_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_040',
		HashNameMale: 'MP_MP_Stunt_tat_040_M',
		HashNameFemale: 'MP_MP_Stunt_tat_040_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_041',
		HashNameMale: 'MP_MP_Stunt_tat_041_M',
		HashNameFemale: 'MP_MP_Stunt_tat_041_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_042',
		HashNameMale: 'MP_MP_Stunt_tat_042_M',
		HashNameFemale: 'MP_MP_Stunt_tat_042_F',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_043',
		HashNameMale: 'MP_MP_Stunt_tat_043_M',
		HashNameFemale: 'MP_MP_Stunt_tat_043_F',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_044',
		HashNameMale: 'MP_MP_Stunt_tat_044_M',
		HashNameFemale: 'MP_MP_Stunt_tat_044_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_045',
		HashNameMale: 'MP_MP_Stunt_tat_045_M',
		HashNameFemale: 'MP_MP_Stunt_tat_045_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_046',
		HashNameMale: 'MP_MP_Stunt_tat_046_M',
		HashNameFemale: 'MP_MP_Stunt_tat_046_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_047',
		HashNameMale: 'MP_MP_Stunt_tat_047_M',
		HashNameFemale: 'MP_MP_Stunt_tat_047_F',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_048',
		HashNameMale: 'MP_MP_Stunt_tat_048_M',
		HashNameFemale: 'MP_MP_Stunt_tat_048_F',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'mpstunt_overlays',
		Name: 'TAT_ST_049',
		HashNameMale: 'MP_MP_Stunt_tat_049_M',
		HashNameFemale: 'MP_MP_Stunt_tat_049_F',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_008',
		HashNameMale: 'FM_Tat_Award_M_000',
		HashNameFemale: 'FM_Tat_Award_F_000',
		Zone: 'ZONE_HEAD',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_009',
		HashNameMale: 'FM_Tat_Award_M_001',
		HashNameFemale: 'FM_Tat_Award_F_001',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_010',
		HashNameMale: 'FM_Tat_Award_M_002',
		HashNameFemale: 'FM_Tat_Award_F_002',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_011',
		HashNameMale: 'FM_Tat_Award_M_003',
		HashNameFemale: 'FM_Tat_Award_F_003',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_012',
		HashNameMale: 'FM_Tat_Award_M_004',
		HashNameFemale: 'FM_Tat_Award_F_004',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_013',
		HashNameMale: 'FM_Tat_Award_M_005',
		HashNameFemale: 'FM_Tat_Award_F_005',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_014',
		HashNameMale: 'FM_Tat_Award_M_006',
		HashNameFemale: 'FM_Tat_Award_F_006',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_015',
		HashNameMale: 'FM_Tat_Award_M_007',
		HashNameFemale: 'FM_Tat_Award_F_007',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_016',
		HashNameMale: 'FM_Tat_Award_M_008',
		HashNameFemale: 'FM_Tat_Award_F_008',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_017',
		HashNameMale: 'FM_Tat_Award_M_009',
		HashNameFemale: 'FM_Tat_Award_F_009',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_018',
		HashNameMale: 'FM_Tat_Award_M_010',
		HashNameFemale: 'FM_Tat_Award_F_010',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_019',
		HashNameMale: 'FM_Tat_Award_M_011',
		HashNameFemale: 'FM_Tat_Award_F_011',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_020',
		HashNameMale: 'FM_Tat_Award_M_012',
		HashNameFemale: 'FM_Tat_Award_F_012',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_021',
		HashNameMale: 'FM_Tat_Award_M_013',
		HashNameFemale: 'FM_Tat_Award_F_013',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_022',
		HashNameMale: 'FM_Tat_Award_M_014',
		HashNameFemale: 'FM_Tat_Award_F_014',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_023',
		HashNameMale: 'FM_Tat_Award_M_015',
		HashNameFemale: 'FM_Tat_Award_F_015',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_024',
		HashNameMale: 'FM_Tat_Award_M_016',
		HashNameFemale: 'FM_Tat_Award_F_016',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_025',
		HashNameMale: 'FM_Tat_Award_M_017',
		HashNameFemale: 'FM_Tat_Award_F_017',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_026',
		HashNameMale: 'FM_Tat_Award_M_018',
		HashNameFemale: 'FM_Tat_Award_F_018',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_027',
		HashNameMale: 'FM_Tat_Award_M_019',
		HashNameFemale: 'FM_Tat_Award_F_019',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_204',
		HashNameMale: 'FM_Tat_M_000',
		HashNameFemale: 'FM_Tat_F_000',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_205',
		HashNameMale: 'FM_Tat_M_001',
		HashNameFemale: 'FM_Tat_F_001',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_209',
		HashNameMale: 'FM_Tat_M_002',
		HashNameFemale: 'FM_Tat_F_002',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_206',
		HashNameMale: 'FM_Tat_M_003',
		HashNameFemale: 'FM_Tat_F_003',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_219',
		HashNameMale: 'FM_Tat_M_004',
		HashNameFemale: 'FM_Tat_F_004',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_201',
		HashNameMale: 'FM_Tat_M_005',
		HashNameFemale: 'FM_Tat_F_005',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_202',
		HashNameMale: 'FM_Tat_M_006',
		HashNameFemale: 'FM_Tat_F_006',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_210',
		HashNameMale: 'FM_Tat_M_007',
		HashNameFemale: 'FM_Tat_F_007',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_211',
		HashNameMale: 'FM_Tat_M_008',
		HashNameFemale: 'FM_Tat_F_008',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_213',
		HashNameMale: 'FM_Tat_M_009',
		HashNameFemale: 'FM_Tat_F_009',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_218',
		HashNameMale: 'FM_Tat_M_010',
		HashNameFemale: 'FM_Tat_F_010',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_214',
		HashNameMale: 'FM_Tat_M_011',
		HashNameFemale: 'FM_Tat_F_011',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_220',
		HashNameMale: 'FM_Tat_M_012',
		HashNameFemale: 'FM_Tat_F_012',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_215',
		HashNameMale: 'FM_Tat_M_013',
		HashNameFemale: 'FM_Tat_F_013',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_207',
		HashNameMale: 'FM_Tat_M_014',
		HashNameFemale: 'FM_Tat_F_014',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_203',
		HashNameMale: 'FM_Tat_M_015',
		HashNameFemale: 'FM_Tat_F_015',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_216',
		HashNameMale: 'FM_Tat_M_016',
		HashNameFemale: 'FM_Tat_F_016',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_212',
		HashNameMale: 'FM_Tat_M_017',
		HashNameFemale: 'FM_Tat_F_017',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_208',
		HashNameMale: 'FM_Tat_M_018',
		HashNameFemale: 'FM_Tat_F_018',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_217',
		HashNameMale: 'FM_Tat_M_019',
		HashNameFemale: 'FM_Tat_F_019',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_221',
		HashNameMale: 'FM_Tat_M_020',
		HashNameFemale: 'FM_Tat_F_020',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_222',
		HashNameMale: 'FM_Tat_M_021',
		HashNameFemale: 'FM_Tat_F_021',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_223',
		HashNameMale: 'FM_Tat_M_022',
		HashNameFemale: 'FM_Tat_F_022',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_224',
		HashNameMale: 'FM_Tat_M_023',
		HashNameFemale: 'FM_Tat_F_023',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_225',
		HashNameMale: 'FM_Tat_M_024',
		HashNameFemale: 'FM_Tat_F_024',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_226',
		HashNameMale: 'FM_Tat_M_025',
		HashNameFemale: 'FM_Tat_F_025',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_227',
		HashNameMale: 'FM_Tat_M_026',
		HashNameFemale: 'FM_Tat_F_026',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_228',
		HashNameMale: 'FM_Tat_M_027',
		HashNameFemale: 'FM_Tat_F_027',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_229',
		HashNameMale: 'FM_Tat_M_028',
		HashNameFemale: 'FM_Tat_F_028',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_230',
		HashNameMale: 'FM_Tat_M_029',
		HashNameFemale: 'FM_Tat_F_029',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_231',
		HashNameMale: 'FM_Tat_M_030',
		HashNameFemale: 'FM_Tat_F_030',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_232',
		HashNameMale: 'FM_Tat_M_031',
		HashNameFemale: 'FM_Tat_F_031',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_233',
		HashNameMale: 'FM_Tat_M_032',
		HashNameFemale: 'FM_Tat_F_032',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_234',
		HashNameMale: 'FM_Tat_M_033',
		HashNameFemale: 'FM_Tat_F_033',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_235',
		HashNameMale: 'FM_Tat_M_034',
		HashNameFemale: 'FM_Tat_F_034',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_236',
		HashNameMale: 'FM_Tat_M_035',
		HashNameFemale: 'FM_Tat_F_035',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_237',
		HashNameMale: 'FM_Tat_M_036',
		HashNameFemale: 'FM_Tat_F_036',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_238',
		HashNameMale: 'FM_Tat_M_037',
		HashNameFemale: 'FM_Tat_F_037',
		Zone: 'ZONE_LEFT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_239',
		HashNameMale: 'FM_Tat_M_038',
		HashNameFemale: 'FM_Tat_F_038',
		Zone: 'ZONE_RIGHT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_240',
		HashNameMale: 'FM_Tat_M_039',
		HashNameFemale: 'FM_Tat_F_039',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_241',
		HashNameMale: 'FM_Tat_M_040',
		HashNameFemale: 'FM_Tat_F_040',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_242',
		HashNameMale: 'FM_Tat_M_041',
		HashNameFemale: 'FM_Tat_F_041',
		Zone: 'ZONE_LEFT_ARM',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_243',
		HashNameMale: 'FM_Tat_M_042',
		HashNameFemale: 'FM_Tat_F_042',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_244',
		HashNameMale: 'FM_Tat_M_043',
		HashNameFemale: 'FM_Tat_F_043',
		Zone: 'ZONE_RIGHT_LEG',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_245',
		HashNameMale: 'FM_Tat_M_044',
		HashNameFemale: 'FM_Tat_F_044',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_246',
		HashNameMale: 'FM_Tat_M_045',
		HashNameFemale: 'FM_Tat_F_045',
		Zone: 'ZONE_TORSO',
	},
	{
		Collection: 'multiplayer_overlays',
		Name: 'TAT_FM_247',
		HashNameMale: 'FM_Tat_M_047',
		HashNameFemale: 'FM_Tat_F_047',
		Zone: 'ZONE_RIGHT_ARM',
	},
];
