local repairPartRecipes = {
	["repair_part_electronics"] = {
		result = { name = "repair_part_electronics", count = 10 },
		items = {
			{ name = "electronic_parts", count = 5 },
			{ name = "plastic", count = 4 },
			{ name = "rubber", count = 1 },
			{ name = "copperwire", count = 8 },
		},
		time = 3500,
	},
	["repair_part_axle"] = {
		result = { name = "repair_part_axle", count = 5 },
		items = {
			{ name = "ironbar", count = 4 },
		},
		time = 5000,
	},
	["repair_part_injectors"] = {
		result = { name = "repair_part_injectors", count = 20 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "glue", count = 1 },
		},
		time = 4500,
	},
	["repair_part_clutch"] = {
		result = { name = "repair_part_clutch", count = 8 },
		items = {
			{ name = "ironbar", count = 6 },
			{ name = "rubber", count = 1 },
		},
		time = 5000,
	},
	["repair_part_brakes"] = {
		result = { name = "repair_part_brakes", count = 5 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "glue", count = 1 },
		},
		time = 4500,
	},
	["repair_part_transmission"] = {
		result = { name = "repair_part_transmission", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 1 },
			{ name = "plastic", count = 1 },
		},
		time = 3500,
	},
	["repair_part_rad"] = {
		result = { name = "repair_part_rad", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "rubber", count = 1 },
			{ name = "glue", count = 1 },
		},
		time = 2000,
	},

	-- High Grade
	["repair_part_injectors_hg"] = {
		result = { name = "repair_part_injectors_hg", count = 20 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "heavy_glue", count = 1 },
		},
		time = 11000,
	},
	["repair_part_clutch_hg"] = {
		result = { name = "repair_part_clutch_hg", count = 8 },
		items = {
			{ name = "ironbar", count = 8 },
			{ name = "rubber", count = 2 },
		},
		time = 13000,
	},
	["repair_part_brakes_hg"] = {
		result = { name = "repair_part_brakes_hg", count = 5 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "heavy_glue", count = 1 },
		},
		time = 9000,
	},
	["repair_part_transmission_hg"] = {
		result = { name = "repair_part_transmission_hg", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 1 },
			{ name = "plastic", count = 1 },
			{ name = "copperwire", count = 1 },
		},
		time = 9000,
	},
	["repair_part_rad_hg"] = {
		result = { name = "repair_part_rad_hg", count = 2 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "rubber", count = 1 },
			{ name = "glue", count = 1 },
		},
		time = 6000,
	},
	["lockpick"] = {
		result = { name = "lockpick", count = 2 },
		items = {
			{ name = "ironbar", count = 1 },
		},
		time = 5000,
	},
	["adv_lockpick"] = {
		result = { name = "adv_lockpick", count = 1 },
		items = {
			{ name = "ironbar", count = 5 },
		},
		time = 5000,
	},
	["fakeplates"] = {
		result = { name = "fakeplates", count = 2 },
		items = {
			{ name = "plastic", count = 1 },
			{ name = "scrapmetal", count = 1 },
		},
		time = 8000,
	},
	["repairkit"] = {
		result = { name = "repairkit", count = 4 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "glue", count = 1 },
			{ name = "plastic", count = 2 },
			{ name = "copperwire", count = 4 },
			{ name = "rubber", count = 2 },
		},
		time = 3500,
	},
	["repairkitadv"] = {
		result = { name = "repairkitadv", count = 4 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "heavy_glue", count = 1 },
			{ name = "plastic", count = 3 },
			{ name = "copperwire", count = 4 },
			{ name = "rubber", count = 4 },
		},
		time = 5500,
	},
	["carclean"] = {
		result = { name = "carclean", count = 4 },
		items = {
			{ name = "water", count = 1 },
			{ name = "plastic", count = 4 },
		},
		time = 5500,
	},
	["upgrade_turbo"] = {
		result = { name = "upgrade_turbo", count = 1 },
		items = {
			{ name = "ironbar", count = 4 },
			{ name = "copperwire", count = 100 },
			{ name = "electronic_parts", count = 45 },
			{ name = "rubber", count = 100 },
			{ name = "plastic", count = 100 },
			{ name = "goldbar", count = 3 },
			{ name = "silverbar", count = 3 },
			{ name = "heavy_glue", count = 50 },
		},
		time = 2000,
	},
	["upgrade_engine1"] = {
		result = { name = "upgrade_engine1", count = 1 },
		items = {
			{ name = "ironbar", count = 1 },
			{ name = "copperwire", count = 30 },
			{ name = "electronic_parts", count = 10 },
			{ name = "rubber", count = 45 },
			{ name = "silverbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_engine2"] = {
		result = { name = "upgrade_engine2", count = 1 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "copperwire", count = 50 },
			{ name = "electronic_parts", count = 15 },
			{ name = "rubber", count = 60 },
			{ name = "silverbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_engine3"] = {
		result = { name = "upgrade_engine3", count = 1 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "copperwire", count = 70 },
			{ name = "electronic_parts", count = 20 },
			{ name = "rubber", count = 80 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_engine4"] = {
		result = { name = "upgrade_engine4", count = 1 },
		items = {
			{ name = "ironbar", count = 4 },
			{ name = "copperwire", count = 90 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 100 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_brakes1"] = {
		result = { name = "upgrade_brakes1", count = 1 },
		items = {
			{ name = "ironbar", count = 1 },
			{ name = "electronic_parts", count = 10 },
			{ name = "rubber", count = 45 },
			{ name = "glue", count = 20 },
			{ name = "silverbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_brakes2"] = {
		result = { name = "upgrade_brakes2", count = 1 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "electronic_parts", count = 15 },
			{ name = "rubber", count = 60 },
			{ name = "glue", count = 30 },
			{ name = "silverbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_brakes3"] = {
		result = { name = "upgrade_brakes3", count = 1 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 20 },
			{ name = "rubber", count = 80 },
			{ name = "glue", count = 40 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_brakes4"] = {
		result = { name = "upgrade_brakes4", count = 1 },
		items = {
			{ name = "ironbar", count = 4 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 100 },
			{ name = "glue", count = 50 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_transmission1"] = {
		result = { name = "upgrade_transmission1", count = 1 },
		items = {
			{ name = "ironbar", count = 1 },
			{ name = "electronic_parts", count = 10 },
			{ name = "rubber", count = 15 },
			{ name = "plastic", count = 20 },
			{ name = "heavy_glue", count = 3 },
			{ name = "silverbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_transmission2"] = {
		result = { name = "upgrade_transmission2", count = 1 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "electronic_parts", count = 15 },
			{ name = "rubber", count = 30 },
			{ name = "plastic", count = 30 },
			{ name = "heavy_glue", count = 6 },
			{ name = "silverbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_transmission3"] = {
		result = { name = "upgrade_transmission3", count = 1 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "electronic_parts", count = 20 },
			{ name = "rubber", count = 45 },
			{ name = "plastic", count = 40 },
			{ name = "heavy_glue", count = 9 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_transmission4"] = {
		result = { name = "upgrade_transmission4", count = 1 },
		items = {
			{ name = "ironbar", count = 4 },
			{ name = "electronic_parts", count = 25 },
			{ name = "rubber", count = 60 },
			{ name = "plastic", count = 50 },
			{ name = "heavy_glue", count = 12 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_suspension1"] = {
		result = { name = "upgrade_suspension1", count = 1 },
		items = {
			{ name = "ironbar", count = 1 },
			{ name = "copperwire", count = 20 },
			{ name = "rubber", count = 10 },
			{ name = "plastic", count = 10 },
			{ name = "glue", count = 15 },
			{ name = "silverbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_suspension2"] = {
		result = { name = "upgrade_suspension2", count = 1 },
		items = {
			{ name = "ironbar", count = 2 },
			{ name = "copperwire", count = 30 },
			{ name = "rubber", count = 20 },
			{ name = "plastic", count = 25 },
			{ name = "glue", count = 18 },
			{ name = "silverbar", count = 3 },
		},
		time = 2000,
	},
	["upgrade_suspension3"] = {
		result = { name = "upgrade_suspension3", count = 1 },
		items = {
			{ name = "ironbar", count = 3 },
			{ name = "copperwire", count = 40 },
			{ name = "rubber", count = 30 },
			{ name = "plastic", count = 40 },
			{ name = "glue", count = 21 },
			{ name = "goldbar", count = 1 },
		},
		time = 2000,
	},
	["upgrade_suspension4"] = {
		result = { name = "upgrade_suspension4", count = 1 },
		items = {
			{ name = "ironbar", count = 4 },
			{ name = "copperwire", count = 50 },
			{ name = "rubber", count = 40 },
			{ name = "plastic", count = 55 },
			{ name = "glue", count = 24 },
			{ name = "goldbar", count = 3 },
		},
		time = 2000,
	},
}

_mechanicShopStorageCrafting = {
	{
		job = "redline",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-584.07, -939.57, 23.89),
						l = 1.0,
						w = 3.8,
						options = {
							heading = 270,
							--debugPoly=true,
							minZ = 23.29,
							maxZ = 24.89,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-589.19, -926.07, 28.14),
						l = 1.0,
						w = 2.0,
						options = {
							heading = 270,
							--debugPoly=true,
							minZ = 27.54,
							maxZ = 29.14,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "redline-parts-storage-1",
				type = "box",
				coords = vector3(-593.45, -933.6, 28.14),
				width = 12.6,
				length = 6.6,
				options = {
					heading = 270,
					--debugPoly=true,
					minZ = 27.14,
					maxZ = 31.14,
				},
				data = {
					business = "redline",
					inventory = {
						invType = 32,
						owner = "redline-parts-storage-1",
					},
				},
			},
			{
				id = "redline-parts-storage-2",
				type = "box",
				coords = vector3(-586.19, -931.62, 23.96),
				width = 5.6,
				length = 3.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 22.96,
					maxZ = 25.76,
				},
				data = {
					business = "redline",
					inventory = {
						invType = 47,
						owner = "redline-parts-storage-2",
					},
				},
			},
			{
				id = "redline-parts-storage-3",
				type = "box",
				coords = vector3(-585.15, -917.51, 23.96),
				width = 5.0,
				length = 3.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 22.96,
					maxZ = 25.76,
				},
				data = {
					business = "redline",
					inventory = {
						invType = 47,
						owner = "redline-parts-storage-3",
					},
				},
			},
			{
				id = "redline-parts-storage-4",
				type = "box",
				coords = vector3(-578.07, -911.8, 23.89),
				width = 1.8,
				length = 1.8,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 22.89,
					maxZ = 25.29,
				},
				data = {
					business = "redline",
					inventory = {
						invType = 47,
						owner = "redline-parts-storage-4",
					},
				},
			},
			{
				id = "redline-parts-storage-5",
				type = "box",
				coords = vector3(-585.85, -924.58, 23.89),
				width = 3.8,
				length = 5.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 22.89,
					maxZ = 25.49,
				},
				data = {
					business = "redline",
					inventory = {
						invType = 47,
						owner = "redline-parts-storage-5",
					},
				},
			},
		},
	},
	{
		job = "tuna",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(133.37, -3051.24, 7.04),
						w = 1.8,
						l = 11.8,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 6.04,
							maxZ = 8.24,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_turbo,
					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
				},
			},
		},
		partStorage = {
			{
				id = "tuner-parts-storage-1",
				type = "box",
				coords = vector3(128.58, -3011.16, 7.04),
				width = 8.2,
				length = 6.8,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 6.04,
					maxZ = 9.04,
				},
				data = {
					business = "tuna",
					inventory = {
						invType = 49,
						owner = "tuner-parts-storage-1",
					},
				},
			},
			{
				id = "tuner-parts-storage-2",
				type = "box",
				coords = vector3(121.19, -3028.03, 7.04),
				width = 3.0,
				length = 4.0,
				options = {
					heading = 270,
					--debugPoly=true,
					minZ = 6.04,
					maxZ = 10.84,
				},
				data = {
					business = "tuna",
					inventory = {
						invType = 49,
						owner = "tuner-parts-storage-2",
					},
				},
			},
			{
				id = "tuner-parts-storage-3",
				type = "box",
				coords = vector3(129.55, -3031.51, 7.04),
				length = 2.0,
				width = 2.0,
				options = {
					heading = 345,
					--debugPoly=true,
					minZ = 6.04,
					maxZ = 8.24,
				},
				data = {
					business = "tuna",
					inventory = {
						invType = 50,
						owner = "tuner-parts-storage-3",
					},
				},
			},
		},
	},
	{
		job = "tirenutz",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-57.5, -1325.07, 29.27),
						w = 4.2,
						l = 1.0,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 28.27,
							maxZ = 31.07,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "nutz-parts-storage-1",
				type = "box",
				coords = vector3(-58.01, -1328.92, 29.27),
				width = 2.0,
				length = 2.8,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 28.27,
					maxZ = 31.07,
				},
				data = {
					business = "tirenutz",
					inventory = {
						invType = 71,
						owner = "nutz-parts-storage-1",
					},
				},
			},
			{
				id = "nutz-parts-storage-2",
				type = "box",
				coords = vector3(-59.78, -1336.95, 26.85),
				width = 2.0,
				length = 2.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.85,
					maxZ = 27.65,
				},
				data = {
					business = "tirenutz",
					inventory = {
						invType = 71,
						owner = "nutz-parts-storage-2",
					},
				},
			},
		},
	},
	{
		job = "hayes",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-1421.67, -456.38, 35.91),
						w = 3.8,
						l = 1.0,
						options = {
							heading = 302,
							--debugPoly=true,
							minZ = 34.91,
							maxZ = 37.31,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "hayes-parts-storage-1",
				type = "box",
				coords = vector3(-1418.77, -454.4, 35.91),
				width = 3.0,
				length = 1.2,
				options = {
					heading = 32,
					--debugPoly=true,
					minZ = 34.91,
					maxZ = 38.51,
				},
				data = {
					business = "hayes",
					inventory = {
						invType = 72,
						owner = "hayes-parts-storage-1",
					},
				},
			},
			{
				id = "hayes-parts-storage-2",
				type = "box",
				coords = vector3(-1407.85, -447.14, 35.91),
				width = 2.0,
				length = 4.4,
				options = {
					heading = 300,
					--debugPoly=true,
					minZ = 34.91,
					maxZ = 38.51,
				},
				data = {
					business = "hayes",
					inventory = {
						invType = 72,
						owner = "hayes-parts-storage-2",
					},
				},
			},
		},
	},

	{
		job = "atomic",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(476.67, -1876.93, 26.09),
						w = 1.2,
						l = 4.0,
						options = {
							heading = 25,
							--debugPoly=true,
							minZ = 25.09,
							maxZ = 28.09,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "atomic-parts-storage-1",
				type = "box",
				coords = vector3(470.12, -1887.23, 26.09),
				width = 3.8,
				length = 1.2,
				options = {
					heading = 25,
					--debugPoly=true,
					minZ = 25.09,
					maxZ = 28.29,
				},
				data = {
					business = "atomic",
					inventory = {
						invType = 73,
						owner = "atomic-parts-storage-1",
					},
				},
			},
			{
				id = "atomic-parts-storage-2",
				type = "box",
				coords = vector3(471.88, -1879.14, 26.25),
				width = 2.0,
				length = 5.4,
				options = {
					heading = 295,
					--debugPoly=true,
					minZ = 25.25,
					maxZ = 28.25,
				},
				data = {
					business = "atomic",
					inventory = {
						invType = 73,
						owner = "atomic-parts-storage-2",
					},
				},
			},
		},
	},
	{
		job = "harmony",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(1176.15, 2635.21, 37.75),
						w = 3.8,
						l = 1.4,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 36.75,
							maxZ = 39.55,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "harmony-parts-storage-1",
				type = "box",
				coords = vector3(1172.47, 2635.59, 37.8),
				width = 2.0,
				length = 2.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 36.8,
					maxZ = 40.8,
				},
				data = {
					business = "harmony",
					inventory = {
						invType = 92,
						owner = "harmony-parts-storage-1",
					},
				},
			},
			{
				id = "harmony-parts-storage-2",
				type = "box",
				coords = vector3(1184.63, 2639.38, 37.75),
				width = 5.0,
				length = 1.4,
				options = {
					heading = 270,
					--debugPoly=true,
					minZ = 36.75,
					maxZ = 40.15,
				},
				data = {
					business = "harmony",
					inventory = {
						invType = 92,
						owner = "harmony-parts-storage-2",
					},
				},
			},
		},
	},
	{
		job = "blackline",
		partCrafting = {
			-- {
			--     label = "Make Parts",
			--     targeting = {
			--         actionString = "Crafting",
			--         icon = "toolbox",
			--         poly = {
			--             coords = vector3(1176.15, 2635.21, 37.75),
			--             w = 3.8,
			--             l = 1.4,
			--             options = {
			--                 heading = 0,
			--                 --debugPoly=true,
			--                 minZ = 36.75,
			--                 maxZ = 39.55
			--             },
			--         },
			--     },
			--     recipes = {
			--         repairPartRecipes.repair_part_electronics,
			--         repairPartRecipes.repair_part_axle,
			--         repairPartRecipes.repair_part_injectors,
			--         repairPartRecipes.repair_part_clutch,
			--         repairPartRecipes.repair_part_brakes,
			--         repairPartRecipes.repair_part_transmission,
			--         repairPartRecipes.repair_part_rad,
			--         repairPartRecipes.repair_part_injectors_hg,
			--         repairPartRecipes.repair_part_clutch_hg,
			--         repairPartRecipes.repair_part_brakes_hg,
			--         repairPartRecipes.repair_part_transmission_hg,
			--         repairPartRecipes.repair_part_rad_hg,
			--         repairPartRecipes.lockpick,
			--         repairPartRecipes.adv_lockpick,
			--         repairPartRecipes.repairkit,
			--         repairPartRecipes.repairkitadv,
			--         repairPartRecipes.carclean,
			--     },
			-- },
		},
		partStorage = {},
	},
	{
		job = "autoexotics",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(546.56, -166.06, 54.49),
						w = 1.4,
						l = 4.0,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 53.49,
							maxZ = 55.89,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "autoexotics-parts-storage-1",
				type = "box",
				coords = vector3(538.39, -165.97, 54.49),
				length = 2.4,
				width = 4.6,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 53.49,
					maxZ = 56.49,
				},
				data = {
					business = "autoexotics",
					inventory = {
						invType = 106,
						owner = "autoexotics-parts-storage-1",
					},
				},
			},
			{
				id = "autoexotics-parts-storage-2",
				type = "box",
				coords = vector3(547.15, -184.39, 54.49),
				width = 2,
				length = 2,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 53.49,
					maxZ = 55.69,
				},
				data = {
					business = "autoexotics",
					inventory = {
						invType = 107,
						owner = "autoexotics-parts-storage-2",
					},
				},
			},
			{
				id = "autoexotics-parts-storage-3",
				type = "box",
				coords = vector3(540.32, -170.26, 54.49),
				width = 1.4,
				length = 1.4,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 53.49,
					maxZ = 55.89,
				},
				data = {
					business = "autoexotics",
					inventory = {
						invType = 107,
						owner = "autoexotics-parts-storage-3",
					},
				},
			},
			{
				id = "autoexotics-parts-storage-4",
				type = "box",
				coords = vector3(550.87, -193.9, 54.49),
				width = 1.4,
				length = 1.4,
				options = {
					heading = 29,
					--debugPoly=true,
					minZ = 53.29,
					maxZ = 56.29,
				},
				data = {
					business = "autoexotics",
					inventory = {
						invType = 107,
						owner = "autoexotics-parts-storage-4",
					},
				},
			},
		},
	},
	{
		job = "ottos",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(833.46, -823.82, 26.33),
						w = 1.6,
						l = 4.0,
						options = {
							heading = 0,
							--debugPoly=true,
							minZ = 25.73,
							maxZ = 27.33,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "ottos-parts-storage-1",
				type = "box",
				coords = vector3(839.73, -827.07, 26.33),
				length = 2.0,
				width = 3.6,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 24.93,
					maxZ = 28.93,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 119,
						owner = "ottos-parts-storage-1",
					},
				},
			},
			{
				id = "ottos-parts-storage-2",
				type = "box",
				coords = vector3(836.24, -819.44, 26.33),
				length = 2.2,
				width = 1.4,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.33,
					maxZ = 28.13,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 120,
						owner = "ottos-parts-storage-2",
					},
				},
			},
			{
				id = "ottos-parts-storage-3",
				type = "box",
				coords = vector3(835.906, -814.128, 26.350),
				length = 2.2,
				width = 1.4,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.33,
					maxZ = 28.13,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 120,
						owner = "ottos-parts-storage-3",
					},
				},
			},
			{
				id = "ottos-parts-storage-4",
				type = "box",
				coords = vector3(836.32, -808.23, 26.35),
				length = 1.6,
				width = 1.4,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.35,
					maxZ = 28.15,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 120,
						owner = "ottos-parts-storage-4",
					},
				},
			},
			{
				id = "ottos-parts-storage-5",
				type = "box",
				coords = vector3(833.637, -803.283, 26.333),
				length = 1.4,
				width = 2.2,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.33,
					maxZ = 28.13,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 120,
						owner = "ottos-parts-storage-5",
					},
				},
			},
			{
				id = "ottos-parts-storage-6",
				type = "box",
				coords = vector3(826.2, -826.02, 26.33),
				length = 1.0,
				width = 1.0,
				options = {
					heading = 0,
					--debugPoly=true,
					minZ = 25.33,
					maxZ = 27.53,
				},
				data = {
					business = "ottos",
					inventory = {
						invType = 120,
						owner = "ottos-parts-storage-6",
					},
				},
			},
		},
	},
	{
		job = "dreamworks",
		partCrafting = {
			{
				label = "Make Parts",
				targeting = {
					actionString = "Crafting",
					icon = "toolbox",
					poly = {
						coords = vector3(-726.39, -1505.64, 5.06),
						w = 1.0,
						l = 5.0,
						options = {
							heading = 293,
							--debugPoly=true,
							minZ = 4.06,
							maxZ = 6.66,
						},
					},
				},
				recipes = {
					repairPartRecipes.repair_part_electronics,
					repairPartRecipes.repair_part_axle,
					repairPartRecipes.repair_part_injectors,
					repairPartRecipes.repair_part_clutch,
					repairPartRecipes.repair_part_brakes,
					repairPartRecipes.repair_part_transmission,
					repairPartRecipes.repair_part_rad,
					repairPartRecipes.repair_part_injectors_hg,
					repairPartRecipes.repair_part_clutch_hg,
					repairPartRecipes.repair_part_brakes_hg,
					repairPartRecipes.repair_part_transmission_hg,
					repairPartRecipes.repair_part_rad_hg,
					repairPartRecipes.lockpick,
					repairPartRecipes.adv_lockpick,
					repairPartRecipes.repairkit,
					repairPartRecipes.repairkitadv,
					repairPartRecipes.carclean,

					repairPartRecipes.upgrade_engine1,
					repairPartRecipes.upgrade_engine2,
					repairPartRecipes.upgrade_engine3,
					repairPartRecipes.upgrade_engine4,
					repairPartRecipes.upgrade_brakes1,
					repairPartRecipes.upgrade_brakes2,
					repairPartRecipes.upgrade_brakes3,
					repairPartRecipes.upgrade_brakes4,
					repairPartRecipes.upgrade_transmission1,
					repairPartRecipes.upgrade_transmission2,
					repairPartRecipes.upgrade_transmission3,
					repairPartRecipes.upgrade_transmission4,
					repairPartRecipes.upgrade_suspension1,
					repairPartRecipes.upgrade_suspension2,
					repairPartRecipes.upgrade_suspension3,
					repairPartRecipes.upgrade_suspension4,
					repairPartRecipes.upgrade_turbo,
				},
			},
		},
		partStorage = {
			{
				id = "dreamworks-parts-storage-1",
				type = "box",
				coords = vector3(-755.39, -1516.27, 5.06),
				length = 2.0,
				width = 2.6,
				options = {
					heading = 23,
					--debugPoly=true,
					minZ = 4.06,
					maxZ = 6.86,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 122,
						owner = "dreamworks-parts-storage-1",
					},
				},
			},
			{
				id = "dreamworks-parts-storage-2",
				type = "box",
				coords = vector3(-764.27, -1522.74, 5.06),
				length = 1.6,
				width = 2.4,
				options = {
					heading = 293,
					--debugPoly=true,
					minZ = 4.06,
					maxZ = 6.26,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 123,
						owner = "dreamworks-parts-storage-2",
					},
				},
			},
			{
				id = "dreamworks-parts-storage-3",
				type = "box",
				coords = vector3(-751.32, -1530.63, 5.06),
				length = 1.6,
				width = 3.2,
				options = {
					heading = 203,
					--debugPoly=true,
					minZ = 4.06,
					maxZ = 6.26,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 123,
						owner = "dreamworks-parts-storage-3",
					},
				},
			},
			{
				id = "dreamworks-parts-storage-4",
				type = "box",
				coords = vector3(-722.64, -1518.13, 5.06),
				length = 1.6,
				width = 3.2,
				options = {
					heading = 288,
					--debugPoly=true,
					minZ = 4.06,
					maxZ = 6.26,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 123,
						owner = "dreamworks-parts-storage-4",
					},
				},
			},
			{
				id = "dreamworks-parts-storage-5",
				type = "box",
				coords = vector3(-724.27, -1511.46, 5.06),
				length = 1.6,
				width = 3.2,
				options = {
					heading = 293,
					--debugPoly=true,
					minZ = 4.06,
					maxZ = 6.26,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 123,
						owner = "dreamworks-parts-storage-5",
					},
				},
			},
			{
				id = "dreamworks-parts-storage-6",
				type = "box",
				coords = vector3(-728.77, -1504.35, 5.08),
				length = 1.6,
				width = 1.2,
				options = {
					heading = 153,
					--debugPoly=true,
					minZ = 4.08,
					maxZ = 6.28,
				},
				data = {
					business = "dreamworks",
					inventory = {
						invType = 123,
						owner = "dreamworks-parts-storage-6",
					},
				},
			},
		},
	},
}
