_itemsSource["ammo"] = {
	{
		name = "AMMO_SMG",
		ammoType = "AMMO_SMG",
		label = "SMG Ammo",
		bulletCount = 60,
		price = 300,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.9,
	},
	{
		name = "AMMO_STUNGUN",
		ammoType = "AMMO_STUNGUN",
		label = "Taser Ammo",
		bulletCount = 12,
		price = 3,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = "AMMO_PISTOL",
		ammoType = "AMMO_PISTOL",
		label = "Pistol Ammo",
		bulletCount = 30,
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.75,
	},
	{
		name = "AMMO_PISTOL_PD",
		ammoType = "AMMO_PISTOL",
		label = "PD Pistol Ammo",
		iconOverride = "AMMO_PISTOL",
		bulletCount = 34,
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.75,
	},
	{
		name = "AMMO_SMG_PD",
		ammoType = "AMMO_SMG",
		qualification = "PD_SMG",
		label = "PD SMG Ammo",
		iconOverride = "AMMO_SMG",
		bulletCount = 60,
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = "AMMO_RIFLE_PD",
		ammoType = "AMMO_RIFLE",
		iconOverride = "AMMO_RIFLE",
		label = "PD Rifle Ammo",
		qualification = "PD_AR",
		bulletCount = 60,
		price = 10,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1.0,
	},
	{
		name = "AMMO_SHOTGUN_PD",
		ammoType = "AMMO_SHOTGUN",
		qualification = "PD_BEANBAG",
		iconOverride = "AMMO_SHOTGUN",
		label = "PD Shotgun Ammo",
		bulletCount = 12,
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = "AMMO_SHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		label = "Shotgun Ammo",
		bulletCount = 12,
		price = 30,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = "AMMO_RIFLE",
		ammoType = "AMMO_RIFLE",
		label = "Rifle Ammo",
		bulletCount = 60,
		price = 25,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1.0,
	},
	{
		name = "AMMO_SNIPER",
		ammoType = "AMMO_SNIPER",
		label = "Hunting Rifle Ammo",
		bulletCount = 10,
		price = 250,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
		type = 9,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 1.0,
	},
}
