_itemsSource["medical"] = {
	{
		name = "traumakit",
		label = "Trauma Kit",
		description = "Needed to treat serious trauma in the field",
		price = 500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "medicalkit",
		label = "Medical Kit",
		description = "Used to treat patients. Only usable by Doctors",
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "ifak",
		label = "IFAK",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = 5,
		type = 1,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "ifak",
			time = 15000,
			pbConfig = {
				label = "Using IFAK",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
	},
	{
		name = "firstaid",
		label = "First Aid Kit",
		price = 250,
		isUsable = true,
		isRemoved = false,
		isStackable = 5,
		type = 1,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 5,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "firstaid",
			time = 11000,
			pbConfig = {
				label = "Using First Aid Kit",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
	},
	{
		name = "tourniquet",
		label = "Tourniquet",
		price = 150,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 1,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "bandage",
			time = 5000,
			pbConfig = {
				label = "Applying Tourniquet",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "bandage",
		label = "Bandage",
		price = 50,
		isUsable = true,
		isRemoved = false,
		isStackable = 30,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "bandage",
			dictName = "ifak",
			time = 2000,
			pbConfig = {
				label = "Bandaging",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		weight = 0.25,
	},
	{
		name = "gauze",
		label = "Gauze",
		price = 10,
		isUsable = true,
		isRemoved = false,
		isStackable = 30,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "bandage",
			dictName = "gauze",
			time = 2000,
			pbConfig = {
				label = "Packing Wound",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		weight = 0.1,
	},
	{
		name = "morphine",
		label = "Morphine",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = 3,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "bandage",
			dictName = "morphine",
			time = 8000,
			pbConfig = {
				label = "Administering Morphine",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				disableMovement = true,
				disableCarMovement = true,
				disableMouse = false,
				disableCombat = true,
			},
		},
		weight = 1,
	},
}
