_itemsSource["tools"] = {
	{
		name = "lockpick",
		label = "Lockpick",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = 50,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "adv_lockpick",
		label = "Advanced Lockpick",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = 20,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 28),
	},
	{
		name = "lockpick_pd",
		label = "PD Lockpick",
		description = "Only Usable By Police",
		iconOverride = "lockpick",
		imitate = "lockpick",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		useRestrict = {
			job = {
				id = "police",
				duty = true,
			},
		}
	},
	{
		name = "screwdriver",
		label = "Screwdriver",
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.4,
		durability = (60 * 60 * 24 * 3),
	},
	{
		name = "racing_crappy",
		label = "Homemade Phone Dongle",
		description = "Its a really shitty dongly boi",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "RACE_DONGLE",
		weight = 1,
		durability = (60 * 60 * 12),
	},
	{
		name = "racedongle",
		label = "Phone Dongle",
		description = "Its a dongly boi",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "RACE_DONGLE",
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "vpn",
		label = "VPN",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		state = "PHONE_VPN",
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "pickaxe",
		label = "Pickaxe",
		price = 0,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 4.0,
		durability = (60 * 60 * 24 * 1),
	},
	{
		name = "pdhandcuffs",
		label = "PD Handcuffs",
		price = 25,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "handcuffs",
		label = "Handcuffs",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "fluffyhandcuffs",
		label = "Fluffy Handcuffs",
		price = 600,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "spikes",
		label = "Spike Strips",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12.5,
		durability = (60 * 60 * 24 * 7),
	},
	{
		name = "binoculars",
		label = "Binoculars",
		price = 90,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "camera",
		label = "Camera",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 1,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 2.5,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "gps_tracker",
		label = "GPS Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "bobcat_tracker",
		label = "GPS Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "fleeca_tracker",
		label = "GPS Tracker",
		price = 15000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 1,
		durability = (60 * 60 * 24 * 21),
	},
	{
		name = "meth_table",
		label = "Meth Table",
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 0.5,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "parachute",
		label = "Parachute",
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 3,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
}
