_itemsSource["alcohol"] = {
	{
		name = "wine_bottle",
		label = "Bottle of Wine",
		price = 300,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		type = 1,
		rarity = 2,
		closeUi = true,
		weight = 0.5,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 150),
	},
	{
		name = "wine_glass",
		label = "Glass of Wine",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 2,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "beer",
		label = "Beer",
		price = 100,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "whiskey",
		label = "Whiskey",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.3,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "rum",
		label = "Rum",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.3,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "whiskey_glass",
		label = "Glass of Whiskey",
		price = 20,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "tequila",
		label = "Tequila",
		price = 220,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.3,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "tequila_shot",
		label = "Shot of Tequila",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "tequila_sunrise",
		label = "Tequila Sunrise",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "vodka",
		label = "Vodka",
		price = 150,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.3,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 60),
	},
	{
		name = "vodka_shot",
		label = "Shot of Vodka",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},

	{
		name = "jaeger_bomb",
		label = "Jägerbomb",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
    {
		name = "pina_colada",
		label = "Pina Colada",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "raspberry_mimosa",
		label = "Raspberry Mimosa",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "bloody_mary",
		label = "Bloody Mary",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "diamond_drink",
		label = "The Diamond Cocktail",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "pint_mcdougles",
		label = "McDougle's Stout",
		description = "McDougle's Irish Stout™",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.1,
		metalic = false,
		durability = (60 * 60 * 24 * 7),
	},
}