_itemsSource["burgershot"] = {
	{
		name = "burgershot_cup",
		label = "BS Cup",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.05,
	},
	{
		name = "bun",
		label = "Hamburger Bun",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "patty",
		label = "Hamburger Patty",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.2,
	},
	{
		name = "burger",
		label = "The Bleeder",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 70,
			},
		},
		animConfig = {
			anim = "bshot_bleeder",
			time = 12000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "burgershot_drink",
		label = "Burger Shot Drink",
		price = 10,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_THIRST = 75,
			},
			Remove = {
				PLAYER_HUNGER = 0,
			},
		},
		animConfig = {
			anim = "bshot_drink",
			time = 12000,
			pbConfig = {
				label = "Drinking",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "double_shot_burger",
		label = "Double Shot",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		animConfig = {
			anim = "bshot_doubleshot",
			time = 12000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "prickly_burger",
		label = "The Prickly",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		animConfig = {
			anim = "bshot_prickly",
			time = 12000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "the_simply_burger",
		label = "Simply Burger",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 80,
			},
		},
		animConfig = {
			anim = "bshot_simply",
			time = 12000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "tacos",
		label = "Taco",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		animConfig = {
			anim = "bshot_tacos",
			time = 12000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "burgershot_fries",
		label = "Fries",
		price = 15,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 60,
			},
		},
		animConfig = {
			anim = "bshot_fries",
			time = 10000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "heartstopper",
		label = "Heart Stopper",
		price = 65,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
			Ignore = {
				PLAYER_STRESS = 12,
			},
		},
		animConfig = {
			anim = "bshot_heartstopper",
			time = 15000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "meteorite_icecream",
		label = "Meteorite Ice Cream",
		price = 65,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 50,
				PLAYER_THIRST = 50,
			},
			Ignore = {
				PLAYER_STRESS = 20,
			},
		},
		animConfig = {
			anim = "bshot_icecream",
			time = 15000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		energyModifier = {
			modifier = 1.1,
			duration = 2, -- not seconds?
			cooldown = 60, -- seconds
			skipScreenEffects = true,
		}
	},
	{
		name = "orangotang_icecream",
		label = "Orangotang Ice Cream",
		price = 65,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 50,
				PLAYER_THIRST = 50,
			},
			Ignore = {
				PLAYER_STRESS = 20,
			},
		},
		animConfig = {
			anim = "bshot_icecream2",
			time = 15000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		energyModifier = {
			modifier = 1.1,
			duration = 2, -- not seconds?
			cooldown = 60, -- seconds
			skipScreenEffects = true,
		}
	},
	{
		name = "goat_cheese_wrap",
		label = "Goat Cheese Wrap",
		price = 65,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		stressTicks = { "1", "2", "3", "4", "5" },
		animConfig = {
			anim = "bshot_wrap1",
			time = 15000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "chicken_wrap",
		label = "Chicken Wrap",
		price = 65,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		stressTicks = { "1", "2", "3", "4", "5" },
		animConfig = {
			anim = "bshot_wrap2",
			time = 15000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "mocha_shake",
		label = "Mocha Shake",
		description = "Go Crazy",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Shake",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 50,
				PLAYER_HUNGER = 10,
			},
		},
		progressModifier = {
			modifier = 60,
			min = 3,
			max = 6,
		}
	},
}