_itemsSource["uwu_cafe"] = {
    {
		name = "choclate_pancakes",
		label = "Chocolate Pancakes",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		animConfig = {
			anim = "eat",
			time = 10000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "apple_crumble",
		label = "Apple Crumble",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 100,
			},
		},
		animConfig = {
			anim = "eat",
			time = 10000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "cat_donut",
		label = "Cat Donut",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 40,
			},
			Ignore = {
				PLAYER_STRESS = 10,
			},
		},
		animConfig = {
			anim = "donut",
			time = 9000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "cat_cupcake",
		label = "Cat Cupcake",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 40,
			},
			Ignore = {
				PLAYER_STRESS = 10,
			},
		},
		animConfig = {
			anim = "donut",
			time = 9000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
    {
		name = "homemade_cookie",
		label = "Homemade Cookie",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 50,
			},
		},
		animConfig = {
			anim = "eat",
			time = 5000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},


    {
		name = "fruit_explosion",
		label = "Fruit Explosion",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_THIRST = 100,
				PLAYER_HUNGER = 30,
			},
		},
		animConfig = {
			anim = "cup",
			time = 5000,
			pbConfig = {
				label = "Drinking",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		energyModifier = {
			modifier = 1.2,
			duration = 4, -- not seconds?
			cooldown = 30, -- seconds
            skipScreenEffects = true,
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},



    {
		name = "booba_tea",
		label = "Bobba Tea",
		price = 125,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Tea",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 100,
			},
		},
		progressModifier = {
			modifier = 60,
			min = 2,
			max = 4,
		}
	},
	{
		name = "green_tea",
		label = "Green Tea",
		price = 125,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Tea",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 75,
			},
			Remove = {
				PLAYER_DRUNK = 10,
			}
		},
		stressTicks = { "5", "4", "3", "2", "1" },
		progressModifier = {
			modifier = 50,
			min = 1,
			max = 2,
		}
	},


    {
		name = "iced_coffee",
		label = "Iced Coffee",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Coffee",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 25,
			},
		},
		progressModifier = {
			modifier = 75,
			min = 8,
			max = 12,
		}
	},
	{
		name = "matcha_latte",
		label = "Matcha Latte",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Latte",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 50,
			},
		},
		progressModifier = {
			modifier = 60,
			min = 3,
			max = 6,
		}
	},
	{
		name = "pumpkinspiced_latte",
		label = "Pumpkin Spice Latte",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Coffee",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 25,
			},
		},
		progressModifier = {
			modifier = 60,
			min = 3,
			max = 6,
		}
	},
	{
		name = "cat_tuccino",
		label = "Cat Tuccino",
		price = 200,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
		animConfig = {
			anim = "coffee",
			time = 7500,
			pbConfig = {
				label = "Drinking Coffee",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		statusChange = {
			Add = {
				PLAYER_THIRST = 15,
			},
		},
		progressModifier = {
			modifier = 40,
			min = 6,
			max = 10,
		}
	},

    {
		name = "frozen_yoghurt",
		label = "Frozen Yoghurt",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 40,
				PLAYER_THIRST = 10,
			},
		},
		animConfig = {
			anim = "cup",
			time = 9000,
			pbConfig = {
				label = "Eating",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		energyModifier = {
			modifier = 1.1,
			duration = 6, -- not seconds?
			cooldown = 60, -- seconds
			skipScreenEffects = true,
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},
	{
		name = "fresh_lemonade",
		label = "Fresh Lemonade",
		price = 240,
		isUsable = true,
		isRemoved = true,
		isStackable = 15,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.25,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 5,
				PLAYER_THIRST = 40,
			},
		},
		animConfig = {
			anim = "cup",
			time = 9000,
			pbConfig = {
				label = "Drinking",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement =    false,
				disableMouse = false,
				disableCombat = true,
			},
		},
		energyModifier = {
			modifier = 1.15,
			duration = 6, -- not seconds?
			cooldown = 60, -- seconds
			skipScreenEffects = true,
		},
		metalic = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 5),
	},

	{
		name = "uwu_prize_box",
		label = "UwU Mystery Box",
		description = "Collect all the different bears! UwU",
		price = 0,
		isUsable = true,
		isRemoved = true,
		closeUi = true,
		isStackable = 100,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
		animConfig = {
			anim = "mindblown",
			time = 3000,
			pbConfig = {
				label = "Opening UwU Mystery Box",
				useWhileDead = false,
				canCancel = true,
				vehicle = false,
				disarm = true,
				ignoreModifier = true,
				disableMovement = false,
				disableCarMovement = false,
				disableMouse = false,
				disableCombat = true,
			},
		},
	},

	{
		name = "uwu_prize_b1",
		label = "UwU Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b2",
		label = "UwU Rainbow Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b3",
		label = "UwU Sun Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b4",
		label = "UwU Flower Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 1,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b5",
		label = "UwU Tree Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 2,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b6",
		label = "UwU Heart Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 2,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b7",
		label = "UwU Moon Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 3,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b8",
		label = "UwU Rain Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 3,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b9",
		label = "UwU Star Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 4,
		closeUi = true,
		weight = 0.0,
	},
	{
		name = "uwu_prize_b10",
		label = "UwU Snow Bear",
		description = "UwU Cafe Collectable",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 1000,
		type = 5,
		rarity = 4,
		closeUi = true,
		weight = 0.0,
	},
}