_itemsSource["food_ingredients"] = {
    {
		name = "tomato",
		label = "Tomato",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.15,
	},
	{
		name = "raspberry",
		label = "Raspberry",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.05,
	},
	{
		name = "potato",
		label = "Potato",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.25,
	},
	{
		name = "orange",
		label = "Orange",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "lettuce",
		label = "Lettuce",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.3,
	},
	{
		name = "cucumber",
		label = "Cucumber",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.15,
	},
	{
		name = "peas",
		label = "Peas",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.15,
	},
	{
		name = "pickle",
		label = "Pickle",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "pineapple",
		label = "Pineapple",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.5,
	},
	{
		name = "chicken",
		label = "Chicken",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "beef",
		label = "Beef",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "pork",
		label = "Pork",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "venison",
		label = "Venison",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "rabbit",
		label = "Rabbit",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "unk_meat",
		label = "Meat",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
	{
		name = "dough",
		label = "Dough",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.15,
	},
	{
		name = "loaf",
		label = "Bread Loaf",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.50,
	},
	{
		name = "icing",
		label = "Icing",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.30,
	},
	{
		name = "sugar",
		label = "Bag of Sugar",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 40,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 1.0,
	},
	{
		name = "flour",
		label = "Bag of Flour",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 60,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.8,
	},
	{
		name = "rice",
		label = "Bag of Rice",
		price = 5,
		isUsable = false,
		isRemoved = false,
		isStackable = 60,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.8,
	},
	{
		name = "milk_can",
		label = "Milk Canister",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 1.5,
	},
	{
		name = "keg",
		label = "Keg of Irish Stout",
		description = "McDougle's Irish Stout™",
		price = 150,
		isUsable = false,
		isRemoved = false,
		isStackable = 5,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 1.5,
	},
	{
		name = "coconut_milk",
		label = "Coconut Milk",
		price = 3,
		isUsable = false,
		isRemoved = false,
		isStackable = 100,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 1.0,
	},
	{
		name = "cheese",
		label = "Bag of Cheese",
		price = 4,
		isUsable = false,
		isRemoved = false,
		isStackable = 50,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.30,
	},
	{
		name = "tea_leaf",
		label = "Tea Leaf",
		price = 1,
		isUsable = false,
		isRemoved = false,
		isStackable = 500,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.01,
	},
	{
		name = "plastic_cup",
		label = "Plastic Cup",
		price = 5,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.05,
	},
	{
		name = "coffee_beans",
		label = "Coffee Beans",
		price = 7,
		isUsable = false,
		isRemoved = false,
		isStackable = 300,
		type = 1,
		rarity = 1,
		closeUi = false,
		metalic = false,
		isDestroyed = true,
		weight = 0.1,
	},
    {
		name = "jaeger",
		label = "Jägermeister",
		price = 150,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		type = 1,
		rarity = 1,
		closeUi = true,
		weight = 0.3,
		metalic = false,
		isDestroyed = true,
	},
    {
		name = "raspberry_liqueur",
		label = "Raspberry Liqueur",
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 30,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.05,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "sparkling_wine",
		label = "Sparkling Wine",
		price = 5,
		isUsable = true,
		isRemoved = true,
		isStackable = 30,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.05,
		metalic = false,
		isDestroyed = true,
	},
    {
		name = "peach_juice",
		label = "Peach Juice",
		price = 2,
		isUsable = true,
		isRemoved = true,
		isStackable = 50,
		type = 4,
		rarity = 1,
		closeUi = true,
		weight = 0.05,
		metalic = false,
		isDestroyed = true,
	},
	{
		name = "eggs",
		label = "Eggs",
		price = 2,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		isDestroyed = true,
		weight = 0.15,
	},
}