BOOSTING_VEHICLE_CONFIG = {
    D = {
        length = {
            min = 2,
            max = 4,
        },
        peds = {
            min = 1,
            max = 3,
            difficult = 1
        },
        tracker = false,
        vehicles = {
            {
                vehicle = "hermes",
                make = "Albany",
                model = "Hermes",
                priceBase = 7,
            },
            {
                vehicle = "asea",
                make = "Declasse",
                model = "Asea",
                priceBase = 6,
            },
            {
                vehicle = "emperor",
                make = "Declasse",
                model = "Emperor",
                priceBase = 6,
            },
            {
                vehicle = "regina",
                make = "Dundreary",
                model = "Regina",
                priceBase = 6,
            },
            {
                vehicle = "minivan",
                make = "Vapid",
                model = "Minivan",
                priceBase = 6,
            },
            {
                vehicle = "paradise",
                make = "Bravado",
                model = "Paradise",
                priceBase = 6,
            },
            {
                vehicle = "pony",
                make = "Brute",
                model = "Pony",
                priceBase = 6,
            },
            {
                vehicle = "speedo",
                make = "Vapid",
                model = "Speedo",
                priceBase = 6,
            },
            {
                vehicle = "kalahari",
                make = "Canis",
                model = "Kalahari",
                priceBase = 6,
            },
            {
                vehicle = "gburrito",
                make = "Declasse",
                model = "Burrito G",
                priceBase = 6,
            },
            {
                vehicle = "dilettante",
                make = "Karin",
                model = "Dilettante",
                priceBase = 6,
            },
            {
                vehicle = "rancherxl",
                make = "Declasse",
                model = "Rancher XL",
                priceBase = 6,
            },
            {
                vehicle = "sadler",
                make = "Vapid",
                model = "Sadler",
                priceBase = 6,
            },
            {
                vehicle = "sandking2",
                make = "Vapid",
                model = "Sandking",
                priceBase = 6,
            },
            {
                vehicle = "sandking",
                make = "Vapid",
                model = "Sandking XL",
                priceBase = 6,
            },
            {
                vehicle = "surfer",
                make = "BF",
                model = "Surfer",
                priceBase = 6,
            },
            {
                vehicle = "virgo2",
                make = "Albany",
                model = "Virgo Custom",
                priceBase = 7,
            },
            {
                vehicle = "virgo3",
                make = "Albany",
                model = "Virgo Classic",
                priceBase = 7,
            },
            {
                vehicle = "voodoo2",
                make = "Declasse",
                model = "Voodoo",
                priceBase = 6,
            },
            {
                vehicle = "manana",
                make = "Albany",
                model = "Manana",
                priceBase = 6,
            },
            {
                vehicle = "peyote",
                make = "Vapid",
                model = "Peyote",
                priceBase = 7,
            },
            {
                vehicle = "tornado",
                make = "Declasse",
                model = "Tornado",
                priceBase = 6,
            },
            {
                vehicle = "tornado5",
                make = "Declasse",
                model = "Tornado Custom",
                priceBase = 6,
            },
            {
                vehicle = "pigalle",
                make = "Lampadati",
                model = "Pigalle",
                priceBase = 6,
            },
            {
                vehicle = "youga2",
                make = "Bravado",
                model = "Youga Classic",
                priceBase = 6,
            },
        },
        rareVehicles = {
            {
                vehicle = "romero",
                make = "Chariot",
                model = "Romero",
                priceBase = 6,
            },
            {
                vehicle = "rumpo",
                make = "Bravado",
                model = "Rumpo",
                priceBase = 6,
            },
            {
                vehicle = "camper",
                make = "Brute",
                model = "Camper",
                priceBase = 6,
            },
            {
                vehicle = "blazer",
                make = "Nagasaki",
                model = "Blazer",
                priceBase = 7,
            },
            {
                vehicle = "bodhi2",
                make = "Canis",
                model = "Bodhi",
                priceBase = 6,
            },
            {
                vehicle = "dloader",
                make = "Bravado",
                model = "Duneloader",
                priceBase = 6,
            },
            {
                vehicle = "dynasty",
                make = "Weeny",
                model = "Dynasty",
                priceBase = 6,
            },
            {
                vehicle = "hustler",
                make = "Vapid",
                model = "Hustler",
                priceBase = 9,
            },
            {
                vehicle = "voodoo",
                make = "Declasse",
                model = "Voodoo Custom",
                priceBase = 9,
            },
            {
                vehicle = "tornado4",
                make = "Declasse",
                model = "Tornado",
                priceBase = 9,
            },
            {
                vehicle = "journey",
                make = "Zirconium",
                model = "Journey",
                priceBase = 9,
            },
        }
    },
    C = {
        length = {
            min = 2,
            max = 4,
        },
        peds = {
            min = 2,
            max = 5,
            difficult = 2
        },
        tracker = false,
        vehicles = {
            {
                vehicle = "blista2",
                make = "Dinka",
                model = "Blista Compact",
                priceBase = 13,
            },
            {
                vehicle = "asterope",
                make = "Karin",
                model = "Asterope",
                priceBase = 13,
            },
            {
                vehicle = "ingot",
                make = "Vulcar",
                model = "Ingot",
                priceBase = 13,
            },
            {
                vehicle = "primo",
                make = "Albany",
                model = "Primo",
                priceBase = 13,
            },
            {
                vehicle = "stanier",
                make = "Vapid",
                model = "Stanier",
                priceBase = 13,
            },
            {
                vehicle = "taxi",
                make = "Vapid",
                model = "Taxi",
                priceBase = 13,
            },
            {
                vehicle = "warrener",
                make = "Vulcar",
                model = "Warrener",
                priceBase = 13,
            },
            {
                vehicle = "washington",
                make = "Albany",
                model = "Washington",
                priceBase = 13,
            },
            {
                vehicle = "issi2",
                make = "Weeny",
                model = "Issi",
                priceBase = 13,
            },
            {
                vehicle = "panto",
                make = "Benefactor",
                model = "Panto",
                priceBase = 13,
            },
            {
                vehicle = "rhapsody",
                make = "Declasse",
                model = "Rhapsody",
                priceBase = 13,
            },
            {
                vehicle = "baller",
                make = "Gallivanter",
                model = "Baller",
                priceBase = 13,
            },
            {
                vehicle = "baller2",
                make = "Gallivanter",
                model = "Baller",
                priceBase = 14,
            },
            {
                vehicle = "bjxl",
                make = "Karin",
                model = "BeeJay XL",
                priceBase = 13,
            },
            {
                vehicle = "cavalcade",
                make = "Albany",
                model = "Cavalcade",
                priceBase = 13,
            },
            {
                vehicle = "cavalcade2",
                make = "Albany",
                model = "Cavalcade",
                priceBase = 15,
            },
            {
                vehicle = "fq2",
                make = "Fathom",
                model = "FQ-2",
                priceBase = 15,
            },
            {
                vehicle = "granger",
                make = "Declasse",
                model = "Granger",
                priceBase = 14,
            },
            {
                vehicle = "habanero",
                make = "Emperor",
                model = "Habanero",
                priceBase = 14,
            },
            {
                vehicle = "landstalker",
                make = "Dundreary",
                model = "Landstalker",
                priceBase = 14,
            },
            {
                vehicle = "patriot",
                make = "Mammoth",
                model = "Patriot",
                priceBase = 14,
            },
            {
                vehicle = "radi",
                make = "Vapid",
                model = "Radius",
                priceBase = 14,
            },
            {
                vehicle = "seminole",
                make = "Canis",
                model = "Seminole",
                priceBase = 14,
            },
            {
                vehicle = "youga",
                make = "Bravado",
                model = "Youga",
                priceBase = 14,
            },
            {
                vehicle = "caracara2",
                make = "Vapid",
                model = "Caracara",
                priceBase = 14,
            },
            {
                vehicle = "caracara2",
                make = "Vapid",
                model = "Caracara",
                priceBase = 14,
            },
            {
                vehicle = "mesa",
                make = "Canis",
                model = "Mesa",
                priceBase = 14,
            },
            {
                vehicle = "mesa",
                make = "Canis",
                model = "Mesa",
                priceBase = 14,
            },
            {
                vehicle = "kamacho",
                make = "Canis",
                model = "Kamacho",
                priceBase = 16,
            },
            {
                vehicle = "rebel",
                make = "Karin",
                model = "Rebel",
                priceBase = 15,
            },
            {
                vehicle = "rebel2",
                make = "Karin",
                model = "Rebel",
                priceBase = 15,
            },
            {
                vehicle = "guardian",
                make = "Vapid",
                model = "Guardian",
                priceBase = 17,
            },
            {
                vehicle = "bison",
                make = "Bravado",
                model = "Bison",
                priceBase = 15,
            },
            {
                vehicle = "bobcatxl",
                make = "Vapid",
                model = "Bobcat XL",
                priceBase = 16,
            },
            {
                vehicle = "riata",
                make = "Vapid",
                model = "Riata",
                priceBase = 17,
            },
            {
                vehicle = "glendale",
                make = "Benefactor",
                model = "Glendale",
                priceBase = 14,
            },
            {
                vehicle = "chino",
                make = "Vapid",
                model = "Chino",
                priceBase = 14,
            },
            {
                vehicle = "moonbeam",
                make = "Declasse",
                model = "Moonbeam",
                priceBase = 14,
            },
            {
                vehicle = "ratloader",
                make = "Bravado",
                model = "Rat-Loader",
                priceBase = 14,
            },
        },
        rareVehicles = {
            {
                vehicle = "primo2",
                make = "Albany",
                model = "Primo Custom",
                priceBase = 15,
            },
            {
                vehicle = "stretch",
                make = "Dundreary",
                model = "Stretch",
                priceBase = 15,
            },
            {
                vehicle = "patriot2",
                make = "Mammoth",
                model = "Patriot WCR",
                priceBase = 16,
            },            
            {
                vehicle = "contender",
                make = "Vapid",
                model = "Contender",
                priceBase = 16,
            },
            {
                vehicle = "rumpo3",
                make = "Bravado",
                model = "Rumpo Custom",
                priceBase = 16,
            },
            {
                vehicle = "streiter",
                make = "Benefactor",
                model = "Streiter",
                priceBase = 16,
            },
            {
                vehicle = "mesa3",
                make = "Canis",
                model = "Mesa Lifted",
                priceBase = 16,
            },
            {
                vehicle = "comet4",
                make = "Pfister",
                model = "Comet Safari",
                priceBase = 18,
            },
            {
                vehicle = "bifta",
                make = "BF",
                model = "Bifta",
                priceBase = 18,
            },
            {
                vehicle = "brawler",
                make = "Coil",
                model = "Brawler",
                priceBase = 19,
            },
            {
                vehicle = "dubsta3",
                make = "Benefactor",
                model = "Dubsta 6x6",
                priceBase = 17,
            },
            {
                vehicle = "dune",
                make = "BF",
                model = "Dune Buggy",
                priceBase = 14,
            },
            {
                vehicle = "freecrawler",
                make = "Canis",
                model = "Freecrawler",
                priceBase = 17,
            },
            {
                vehicle = "bfinjection",
                make = "BF",
                model = "Injection",
                priceBase = 18,
            },
            {
                vehicle = "fagaloa",
                make = "Vulcar",
                model = "Fagaloa",
                priceBase = 17,
            },
            {
                vehicle = "issi3",
                make = "Weeny",
                model = "Issi Classic",
                priceBase = 17,
            },
            {
                vehicle = "faction3",
                make = "Willard",
                model = "Faction Donk",
                priceBase = 17,
            },
            {
                vehicle = "faction3",
                make = "Willard",
                model = "Faction Donk",
                priceBase = 17,
            },
            {
                vehicle = "btype",
                make = "Albany",
                model = "Roosevelt",
                priceBase = 17,
            },
            {
                vehicle = "btype3",
                make = "Albany",
                model = "Roosevelt Valor",
                priceBase = 18,
            },
            {
                vehicle = "ztype",
                make = "Truffade",
                model = "Z-Type",
                priceBase = 19,
            },
        }
    },
    B = {
        length = {
            min = 4,
            max = 6,
        },
        peds = {
            min = 4,
            max = 6,
            difficult = 3
        },
        tracker = {
            chance = 35,
            min = 4,
            max = 6,
        },
        vehicles = {
            {
                vehicle = "komoda",
                make = "Lampadati",
                model = "Komoda",
                priceBase = 24,
            },
            {
                vehicle = "vstr",
                make = "Albany",
                model = "VSTR",
                priceBase = 25,
            },
            {
                vehicle = "blista",
                make = "Dinka",
                model = "Blista",
                priceBase = 23,
            },
            {
                vehicle = "sugoi",
                make = "Dinka",
                model = "Sugoi",
                priceBase = 23,
            },
            {
                vehicle = "prairie",
                make = "Bollokon",
                model = "Prairie",
                priceBase = 23,
            },
            {
                vehicle = "savestra",
                make = "Annis",
                model = "Savestra",
                priceBase = 23,
            },
            {
                vehicle = "sentinel",
                make = "Ubermacht",
                model = "Sentinel",
                priceBase = 23,
            },
            {
                vehicle = "sentinel2",
                make = "Ubermacht",
                model = "Sentinel XS",
                priceBase = 23,
            },
            {
                vehicle = "zion2",
                make = "Ubermacht",
                model = "Zion",
                priceBase = 23,
            },
            {
                vehicle = "zion3",
                make = "Ubermacht",
                model = "Zion Classic",
                priceBase = 23,
            },
            {
                vehicle = "buffalo2",
                make = "Bravado",
                model = "Buffalo S",
                priceBase = 23,
            },
            {
                vehicle = "fusilade",
                make = "Shyster",
                model = "Fusilade",
                priceBase = 23,
            },
            {
                vehicle = "futo",
                make = "Karin",
                model = "Futo",
                priceBase = 23,
            },
            {
                vehicle = "sultan",
                make = "Karin",
                model = "Sultan",
                priceBase = 23,
            },
            {
                vehicle = "sultan2",
                make = "Karin",
                model = "Sultan Classic",
                priceBase = 24,
            },
            {
                vehicle = "schafter2",
                make = "Ubermacht",
                model = "Schafter",
                priceBase = 24,
            },
            {
                vehicle = "fugitive",
                make = "Cheval",
                model = "Fugitive",
                priceBase = 24,
            },
            {
                vehicle = "intruder",
                make = "Karin",
                model = "Intruder",
                priceBase = 22,
            },
            {
                vehicle = "premier",
                make = "Declasse",
                model = "Premier",
                priceBase = 22,
            },
            {
                vehicle = "stratum",
                make = "Zirconium",
                model = "Stratum",
                priceBase = 25,
            },
            {
                vehicle = "tailgater",
                make = "Obey",
                model = "Tailgater",
                priceBase = 23,
            },
            {
                vehicle = "exemplar",
                make = "Dewbauchee",
                model = "Exemplar",
                priceBase = 23,
            },
            {
                vehicle = "Jackal",
                make = "Ocelot",
                model = "Jackal",
                priceBase = 23,
            },
            {
                vehicle = "oracle",
                make = "Ubermacht",
                model = "Oracle",
                priceBase = 23,
            },
            {
                vehicle = "oracle2",
                make = "Ubermacht",
                model = "Oracle XS",
                priceBase = 24,
            },
            {
                vehicle = "felon",
                make = "Lampadati",
                model = "Felon",
                priceBase = 23,
            },
            {
                vehicle = "surge",
                make = "Cheval",
                model = "Surge",
                priceBase = 23,
            },
            {
                vehicle = "rebla",
                make = "Ubermacht",
                model = "Rebla",
                priceBase = 23,
            },
            {
                vehicle = "novak",
                make = "Lampadati",
                model = "Novak",
                priceBase = 23,
            },
            {
                vehicle = "baller3",
                make = "Gallivanter",
                model = "Baller LE",
                priceBase = 23,
            },
            {
                vehicle = "dubsta",
                make = "Benefactor",
                model = "Dubsta",
                priceBase = 23,
            },
            {
                vehicle = "gresley",
                make = "Bravado",
                model = "Gresley",
                priceBase = 23,
            },
            {
                vehicle = "huntley",
                make = "Enus",
                model = "Huntley S",
                priceBase = 23,
            },
            {
                vehicle = "rocoto",
                make = "Obey",
                model = "Rocoto",
                priceBase = 23,
            },
            {
                vehicle = "serrano",
                make = "Benefactor",
                model = "Serrano",
                priceBase = 23,
            },
            {
                vehicle = "xls",
                make = "Benefactor",
                model = "XLS",
                priceBase = 23,
            },
            {
                vehicle = "cheburek",
                make = "Rune",
                model = "Cheburek",
                priceBase = 24,
            },
            {
                vehicle = "buccaneer",
                make = "Albany",
                model = "Buccaneer",
                priceBase = 24,
            },
            {
                vehicle = "buccaneer2",
                make = "Albany",
                model = "Buccaneer Custom",
                priceBase = 24,
            },
            {
                vehicle = "buccaneer2",
                make = "Albany",
                model = "Buccaneer Custom",
                priceBase = 24,
            },
            {
                vehicle = "faction",
                make = "Willard",
                model = "Faction",
                priceBase = 24,
            },
            {
                vehicle = "impaler",
                make = "Declasse",
                model = "Impaler",
                priceBase = 24,
            },
            {
                vehicle = "nightshade",
                make = "Imponte",
                model = "Nightshade",
                priceBase = 24,
            },
            {
                vehicle = "picador",
                make = "Cheval",
                model = "Picador",
                priceBase = 24,
            },
            {
                vehicle = "picador",
                make = "Cheval",
                model = "Picador",
                priceBase = 24,
            },
            {
                vehicle = "stalion",
                make = "Declasse",
                model = "Stallion",
                priceBase = 25,
            },
            {
                vehicle = "tulip",
                make = "Declasse",
                model = "Tulip",
                priceBase = 25,
            },
            {
                vehicle = "vigero",
                make = "Declasse",
                model = "Vigero",
                priceBase = 25,
            },
            {
                vehicle = "virgo",
                make = "Albany",
                model = "Virgo",
                priceBase = 25,
            },
            {
                vehicle = "virgo",
                make = "Albany",
                model = "Virgo",
                priceBase = 25,
            },
            {
                vehicle = "casco",
                make = "Lampadati",
                model = "Casco",
                priceBase = 22,
            },
            {
                vehicle = "coquette2",
                make = "Invetero",
                model = "Coquette Classic",
                priceBase = 26,
            },
            {
                vehicle = "coquette3",
                make = "Invetero",
                model = "Coquette Blackfin",
                priceBase = 26,
            },
            {
                vehicle = "viseris",
                make = "Lampadati",
                model = "Viseris",
                priceBase = 23,
            },
            {
                vehicle = "rapidgt3",
                make = "Dewbauchee",
                model = "Rapid GT Classic",
                priceBase = 24,
            },
        },
        rareVehicles = {
            {
                vehicle = "windsor2",
                make = "Enus",
                model = "Windsor Drop",
                priceBase = 28,
            },
            {
                vehicle = "revolter",
                make = "Ubermacht",
                model = "Revolter",
                priceBase = 26,
            },
            {
                vehicle = "schafter4",
                make = "Ubermacht",
                model = "Schafter V12",
                priceBase = 26,
            },
            {
                vehicle = "sentinel3",
                make = "Ubermacht",
                model = "Sentinel Classic",
                priceBase = 26,
            },
            {
                vehicle = "cognoscenti",
                make = "Enus",
                model = "Cognoscenti",
                priceBase = 27,
            },
            {
                vehicle = "superd",
                make = "Enus",
                model = "Super Diamond",
                priceBase = 27,
            },
            {
                vehicle = "superd",
                make = "Enus",
                model = "Super Diamond",
                priceBase = 27,
            },
            {
                vehicle = "raiden",
                make = "Coil",
                model = "Raiden",
                priceBase = 28,
            },
            {
                vehicle = "issi7",
                make = "Weeny",
                model = "Issi Sport",
                priceBase = 28,
            },
            {
                vehicle = "flashgt",
                make = "Vapid",
                model = "Flash GT",
                priceBase = 28,
            },
            {
                vehicle = "omnis",
                make = "Obey",
                model = "Omnis",
                priceBase = 28,
            },
            {
                vehicle = "tropos",
                make = "Lampadati",
                model = "Tropos Rallye",
                priceBase = 28,
            },
            {
                vehicle = "michelli",
                make = "Lampadati",
                model = "Michelli GT",
                priceBase = 28,
            },
            {
                vehicle = "retinue2",
                make = "Vapid",
                model = "Retinue MkII",
                priceBase = 28,
            },
            {
                vehicle = "outlaw",
                make = "Nagasaki",
                model = "Outlaw",
                priceBase = 28,
            },
            {
                vehicle = "slamvan2",
                make = "Vapid",
                model = "Slamvan",
                priceBase = 28,
            },
            {
                vehicle = "clique",
                make = "Vapid",
                model = "Clique",
                priceBase = 28,
            },
            {
                vehicle = "faction2",
                make = "Willard",
                model = "Faction Custom",
                priceBase = 25,
            },
            {
                vehicle = "faction2",
                make = "Willard",
                model = "Faction Custom",
                priceBase = 25,
            },
            {
                vehicle = "ratloader2",
                make = "Bravado",
                model = "Rat-Truck",
                priceBase = 25,
            },
            {
                vehicle = "sabregt2",
                make = "Declasse",
                model = "Sabre Turbo Custom",
                priceBase = 28,
            },
            {
                vehicle = "feltzer3",
                make = "Benefactor",
                model = "Stirling GT",
                priceBase = 30,
            },
            {
                vehicle = "mamba",
                make = "Declasse",
                model = "Mamba",
                priceBase = 23,
            },
            {
                vehicle = "stingergt",
                make = "Grotti",
                model = "Stinger GT",
                priceBase = 23,
            },
        }
    },
    A = {
        length = {
            min = 4,
            max = 6,
        },
        peds = {
            min = 4,
            max = 6,
            difficult = 3
        },
        tracker = {
            chance = 100,
            min = 8,
            max = 10,
        },
        vehicles = {
            {
                vehicle = "banshee",
                make = "Bravado",
                model = "Banshee",
                priceBase = 42,
            },
            {
                vehicle = "coquette",
                make = "Invetero",
                model = "Coquette",
                priceBase = 39,
            },
            {
                vehicle = "ninef",
                make = "Obey",
                model = "9F",
                priceBase = 42,
            },
            {
                vehicle = "drafter",
                make = "Obey",
                model = "Drafter",
                priceBase = 48,
            },
            {
                vehicle = "alpha",
                make = "Albany",
                model = "Alpha",
                priceBase = 37,
            },
            {
                vehicle = "bestiagts",
                make = "Grotti",
                model = "Bestia GTS",
                priceBase = 42,
            },
            {
                vehicle = "carbonizzare",
                make = "Grotti",
                model = "Carbonizzare",
                priceBase = 42,
            },
            {
                vehicle = "comet2",
                make = "Pfister",
                model = "Comet",
                priceBase = 42,
            },
            {
                vehicle = "kanjo",
                make = "Dinka",
                model = "Kanjo",
                priceBase = 42,
            },
            {
                vehicle = "feltzer2",
                make = "Benefactor",
                model = "Feltzer",
                priceBase = 42,
            },
            {
                vehicle = "furoregt",
                make = "Lampadati",
                model = "Furore GT",
                priceBase = 42,
            },
            {
                vehicle = "jester",
                make = "Dinka",
                model = "Jester",
                priceBase = 42,
            },
            {
                vehicle = "jugular",
                make = "Ocelot",
                model = "Jugular",
                priceBase = 42,
            },
            {
                vehicle = "lynx",
                make = "Ocelot",
                model = "Lynx",
                priceBase = 42,
            },
            {
                vehicle = "locust",
                make = "Ocelot",
                model = "Locust",
                priceBase = 42,
            },
            -- {
            --     vehicle = "massacro",
            --     make = "Dewbauchee",
            --     model = "Massacro",
            --     priceBase = 42,
            -- },
            {
                vehicle = "pariah",
                make = "Ocelot",
                model = "Pariah",
                priceBase = 42,
            },
            {
                vehicle = "penumbra",
                make = "Maibatsu",
                model = "Penumbra",
                priceBase = 42,
            },
            {
                vehicle = "rapidgt",
                make = "Dewbauchee",
                model = "Rapid GT",
                priceBase = 42,
            },
            {
                vehicle = "schwarzer",
                make = "Benefactor",
                model = "Schwartzer",
                priceBase = 42,
            },
            {
                vehicle = "surano",
                make = "Benefactor",
                model = "Surano",
                priceBase = 42,
            },
            {
                vehicle = "z190",
                make = "Karin",
                model = "190z",
                priceBase = 42,
            },
            {
                vehicle = "cogcabrio",
                make = "Enus",
                model = "Cognoscenti Cabrio",
                priceBase = 42,
            },
            {
                vehicle = "f620",
                make = "Ocelot",
                model = "F620",
                priceBase = 42,
            },
            {
                vehicle = "felon2",
                make = "Lampadati",
                model = "Felon GT",
                priceBase = 42,
            },
            {
                vehicle = "zion",
                make = "Ubermacht",
                model = "Zion",
                priceBase = 42,
            },
            {
                vehicle = "paragon",
                make = "Enus",
                model = "Paragon",
                priceBase = 42,
            },
            {
                vehicle = "windsor",
                make = "Enus",
                model = "Windsor",
                priceBase = 42,
            },
            {
                vehicle = "brioso",
                make = "Grotti",
                model = "Brioso",
                priceBase = 42,
            },
            {
                vehicle = "voltic",
                make = "Coil",
                model = "Voltic",
                priceBase = 42,
            },
            {
                vehicle = "dominator",
                make = "Vapid",
                model = "Dominator",
                priceBase = 42,
            },
            {
                vehicle = "dominator3",
                make = "Vapid",
                model = "Dominator GTX",
                priceBase = 42,
            },
            {
                vehicle = "gauntlet",
                make = "Bravado",
                model = "Gauntlet",
                priceBase = 42,
            },
            {
                vehicle = "stafford",
                make = "Enus",
                model = "Stafford",
                priceBase = 42,
            },
            {
                vehicle = "blade",
                make = "Vapid",
                model = "Blade",
                priceBase = 42,
            },
            {
                vehicle = "ruiner",
                make = "Imponte",
                model = "Ruiner",
                priceBase = 42,
            },
            {
                vehicle = "sabregt",
                make = "Declasse",
                model = "Sabre Turbo",
                priceBase = 42,
            },
            {
                vehicle = "tampa",
                make = "Declasse",
                model = "Tampa",
                priceBase = 42,
            },
        },
        rareVehicles = {
            {
                vehicle = "ellie",
                make = "Vapid",
                model = "Ellie",
                priceBase = 42,
            },
            {
                vehicle = "slamvan",
                make = "Vapid",
                model = "Slamvan",
                priceBase = 42,
            },
            {
                vehicle = "slamvan3",
                make = "Vapid",
                model = "Slamvan Custom",
                priceBase = 42,
            },
            {
                vehicle = "yosemite",
                make = "Declasse",
                model = "Yosemite",
                priceBase = 42,
            },
            {
                vehicle = "tornado6",
                make = "Declasse",
                model = "Tornado Rat",
                priceBase = 42,
            },
            {
                vehicle = "dukes",
                make = "Imponte",
                model = "Dukes",
                priceBase = 42,
            },
            {
                vehicle = "vamos",
                make = "Declasse",
                model = "Vamos",
                priceBase = 42,
            },
            {
                vehicle = "seven70",
                make = "Dewbauchee",
                model = "Seven-70",
                priceBase = 42,
            },
            {
                vehicle = "specter",
                make = "Dewbauchee",
                model = "Specter",
                priceBase = 42,
            },
            {
                vehicle = "specter2",
                make = "Dewbauchee",
                model = "Specter Custom",
                priceBase = 42,
            },
            {
                vehicle = "comet5",
                make = "Pfister",
                model = "Comet SR",
                priceBase = 49,
            },
            {
                vehicle = "comet3",
                make = "Pfister",
                model = "Comet Retro",
                priceBase = 42,
            },
            {
                vehicle = "ruston",
                make = "Hijak",
                model = "Ruston",
                priceBase = 42,
            },
            {
                vehicle = "elegy2",
                make = "Annis",
                model = "Elegy RH8",
                priceBase = 42,
            },
            {
                vehicle = "jester3",
                make = "Dinka",
                model = "Jester Retro",
                priceBase = 42,
            },
        }
    },
    ["A+"] = {
        length = {
            min = 4,
            max = 6,
        },
        peds = {
            min = 6,
            max = 8,
            difficult = 4
        },
        tracker = {
            chance = 100,
            min = 8,
            max = 12,
        },
        vehicles = {
            {
                vehicle = "banshee",
                make = "Bravado",
                model = "Banshee",
                priceBase = 42,
            },
            {
                vehicle = "coquette",
                make = "Invetero",
                model = "Coquette",
                priceBase = 39,
            },
            {
                vehicle = "ninef",
                make = "Obey",
                model = "9F",
                priceBase = 42,
            },
            {
                vehicle = "drafter",
                make = "Obey",
                model = "Drafter",
                priceBase = 48,
            },
            {
                vehicle = "alpha",
                make = "Albany",
                model = "Alpha",
                priceBase = 37,
            },
            {
                vehicle = "bestiagts",
                make = "Grotti",
                model = "Bestia GTS",
                priceBase = 42,
            },
            {
                vehicle = "carbonizzare",
                make = "Grotti",
                model = "Carbonizzare",
                priceBase = 42,
            },
            {
                vehicle = "comet2",
                make = "Pfister",
                model = "Comet",
                priceBase = 42,
            },
            {
                vehicle = "kanjo",
                make = "Dinka",
                model = "Kanjo",
                priceBase = 42,
            },
            {
                vehicle = "feltzer2",
                make = "Benefactor",
                model = "Feltzer",
                priceBase = 42,
            },
            {
                vehicle = "furoregt",
                make = "Lampadati",
                model = "Furore GT",
                priceBase = 42,
            },
            {
                vehicle = "jester",
                make = "Dinka",
                model = "Jester",
                priceBase = 42,
            },
            {
                vehicle = "jugular",
                make = "Ocelot",
                model = "Jugular",
                priceBase = 42,
            },
            {
                vehicle = "lynx",
                make = "Ocelot",
                model = "Lynx",
                priceBase = 42,
            },
            {
                vehicle = "locust",
                make = "Ocelot",
                model = "Locust",
                priceBase = 42,
            },
            -- {
            --     vehicle = "massacro",
            --     make = "Dewbauchee",
            --     model = "Massacro",
            --     priceBase = 42,
            -- },
            {
                vehicle = "pariah",
                make = "Ocelot",
                model = "Pariah",
                priceBase = 42,
            },
            {
                vehicle = "penumbra",
                make = "Maibatsu",
                model = "Penumbra",
                priceBase = 42,
            },
            {
                vehicle = "rapidgt",
                make = "Dewbauchee",
                model = "Rapid GT",
                priceBase = 42,
            },
            {
                vehicle = "schwarzer",
                make = "Benefactor",
                model = "Schwartzer",
                priceBase = 42,
            },
            {
                vehicle = "surano",
                make = "Benefactor",
                model = "Surano",
                priceBase = 42,
            },
            {
                vehicle = "z190",
                make = "Karin",
                model = "190z",
                priceBase = 42,
            },
            {
                vehicle = "cogcabrio",
                make = "Enus",
                model = "Cognoscenti Cabrio",
                priceBase = 42,
            },
            {
                vehicle = "f620",
                make = "Ocelot",
                model = "F620",
                priceBase = 42,
            },
            {
                vehicle = "felon2",
                make = "Lampadati",
                model = "Felon GT",
                priceBase = 42,
            },
            {
                vehicle = "zion",
                make = "Ubermacht",
                model = "Zion",
                priceBase = 42,
            },
            {
                vehicle = "paragon",
                make = "Enus",
                model = "Paragon",
                priceBase = 42,
            },
            {
                vehicle = "windsor",
                make = "Enus",
                model = "Windsor",
                priceBase = 42,
            },
            {
                vehicle = "brioso",
                make = "Grotti",
                model = "Brioso",
                priceBase = 42,
            },
            {
                vehicle = "voltic",
                make = "Coil",
                model = "Voltic",
                priceBase = 42,
            },
            {
                vehicle = "dominator",
                make = "Vapid",
                model = "Dominator",
                priceBase = 42,
            },
            {
                vehicle = "dominator3",
                make = "Vapid",
                model = "Dominator GTX",
                priceBase = 42,
            },
            {
                vehicle = "gauntlet",
                make = "Bravado",
                model = "Gauntlet",
                priceBase = 42,
            },
            {
                vehicle = "stafford",
                make = "Enus",
                model = "Stafford",
                priceBase = 42,
            },
            {
                vehicle = "blade",
                make = "Vapid",
                model = "Blade",
                priceBase = 42,
            },
            {
                vehicle = "ruiner",
                make = "Imponte",
                model = "Ruiner",
                priceBase = 42,
            },
            {
                vehicle = "sabregt",
                make = "Declasse",
                model = "Sabre Turbo",
                priceBase = 42,
            },
            {
                vehicle = "tampa",
                make = "Declasse",
                model = "Tampa",
                priceBase = 42,
            },
        },
        rareVehicles = {
            {
                vehicle = "penumbra2",
                make = "Maibatsu",
                model = "Penumbra FF",
                priceBase = 42,
            },
            {
                vehicle = "buffalo4h",
                make = "Bravado",
                model = "Buffalo STX",
                priceBase = 42,
            },
            {
                vehicle = "draftgpr",
                make = "Obey",
                model = "Drafter GPR",
                priceBase = 42,
            },
            {
                vehicle = "paradrop",
                make = "Enus",
                model = "Paragon Drop",
                priceBase = 42,
            },
            {
                vehicle = "paragonxr",
                make = "Enus",
                model = "Paragon XR",
                priceBase = 42,
            },
            {
                vehicle = "stratumc",
                make = "Zirconium",
                model = "Stratum WB",
                priceBase = 42,
            },
            {
                vehicle = "rmod4ringer7",
                make = "Obey",
                model = "RST",
                priceBase = 42,
            },
            {
                vehicle = "rmodm2g87",
                make = "Ubermacht",
                model = "M2 G",
                priceBase = 42,
            },
            {
                vehicle = "rmodm2g87",
                make = "Ubermacht",
                model = "M2G",
                priceBase = 42,
            },
            {
                vehicle = "rmodm3touring",
                make = "Ubermacht",
                model = "M3T",
                priceBase = 42,
            },
            {
                vehicle = "rmodramtrx",
                make = "Bravado",
                model = "T-Rex",
                priceBase = 42,
            },
            {
                vehicle = "rmodlc500",
                make = "Emperor",
                model = "LC500",
                priceBase = 42,
            },

        }
    },
    ["S+"] = {
        length = {
            min = 6,
            max = 8,
        },
        peds = {
            min = 8,
            max = 10,
            difficult = 5
        },
        tracker = {
            chance = 100,
            min = 12,
            max = 15,
        },
        vehicles = {
            {
                vehicle = "tenf2",
                make = "Obey",
                model = "10F Widebody",
                priceBase = 70,
            },
            {
                vehicle = "vigero2",
                make = "Declasse",
                model = "Vigero ZX",
                priceBase = 70,
            },
            {
                vehicle = "gauntlet6str",
                make = "Bravado",
                model = "Gauntlet 6STR",
                priceBase = 70,
            },
            {
                vehicle = "jestgpr",
                make = "Dinka",
                model = "Jester GPR",
                priceBase = 70,
            },
            {
                vehicle = "nexus",
                make = "Dinka",
                model = "Nexus",
                priceBase = 70,
            },
            {
                vehicle = "rmodchargerw",
                make = "Bravado",
                model = "RatPack",
                priceBase = 70,
            },
            {
                vehicle = "rmodchargerw",
                make = "Bravado",
                model = "RatPack",
                priceBase = 70,
            },
            {
                vehicle = "rmodm4csl",
                make = "Ubermacht",
                model = "M4CS",
                priceBase = 70,
            },
            {
                vehicle = "rmodpanamera",
                make = "Pfister",
                model = "Pandora",
                priceBase = 70,
            },
            {
                vehicle = "rmodsl65",
                make = "Benefactor",
                model = "SL65",
                priceBase = 70,
            },
            {
                vehicle = "rmodlc500lb",
                make = "Emperor",
                model = "LS500LB",
                priceBase = 70,
            },

        },
        rareVehicles = {
            {
                vehicle = "sunrise1",
                make = "Maibatsu",
                model = "Sunrise",
                priceBase = 70,
            },
            {
                vehicle = "sultanrsv8",
                make = "Karin",
                model = "Sultan RSV8",
                priceBase = 70,
            },
            {
                vehicle = "gtr",
                make = "Elegy",
                model = "R35 GTR",
                priceBase = 70,
            },
            {
                vehicle = "rmodsupravaris",
                make = "Dinka",
                model = "2JV",
                priceBase = 70,
            },
            {
                vehicle = "rmodrx7",
                make = "Annis",
                model = "X7",
                priceBase = 70,
            },
            {
                vehicle = "rmodgtr32",
                make = "Elegy",
                model = "GT32",
                priceBase = 70,
            },

        }
    }
}

