_itemsSource["weapons_bobcat"] = {
	{
		name = "BOBCAT_57",
		label = "Five Seven",
		weapon = "WEAPON_57",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_57",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = "BOBCAT_SNSPISTOL",
		label = "SNS Pistol",
		weapon = "WEAPON_SNSPISTOL",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_SNSPISTOL",
		requiresLicense = true,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "BOBCAT_COMBATPISTOL",
		label = "Combat Pistol",
		weapon = "WEAPON_COMBATPISTOL",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_COMBATPISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = "BOBCAT_DOUBLEACTION",
		label = "Double Action Revolver",
		weapon = "WEAPON_DOUBLEACTION",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_DOUBLEACTION",
		requiresLicense = true,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = "BOBCAT_PISTOL50",
		label = "Desert Eagle",
		weapon = "WEAPON_PISTOL50",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_PISTOL50",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = "BOBCAT_REVOLVER",
		label = "Revolver",
		weapon = "WEAPON_REVOLVER",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_REVOLVER",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 10,
		gun = true,
	},
	{
		name = "BOBCAT_SMG_MK2",
		label = "SIG MPX",
		weapon = "WEAPON_SMG_MK2",
		ammoType = "AMMO_SMG",
		iconOverride = "WEAPON_SMG_MK2",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "BOBCAT_SAWNOFFSHOTGUN",
		label = "Sawnoff Shotgun",
		weapon = "WEAPON_SAWNOFFSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_SAWNOFFSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "BOBCAT_PUMPSHOTGUN",
		label = "Pump Shotgun",
		weapon = "WEAPON_PUMPSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_PUMPSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "BOBCAT_DBSHOTGUN",
		label = "Double Barrel Shotgun",
		weapon = "WEAPON_DBSHOTGUN",
		ammoType = "AMMO_SHOTGUN",
		iconOverride = "WEAPON_DBSHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
}
