_sceneBackgrounds = {
    { name = 'Sleek', sprite = 'TallFive' },
    { name = 'Sleek 2', sprite = 'TallTen' },
    { name = 'Sleek 3', sprite = 'TallFifteen' },
    { name = 'Simple', sprite = 'Background' },
    { name = 'Blood', sprite = 'Blood' },
    { name = 'Blood 2', sprite = 'Blood2' },
    { name = 'Blood 3', sprite = 'Blood3' },
    { name = 'Blood 4', sprite = 'Blood4' },
    { name = 'Blood 5', sprite = 'Blood5' },
    { name = 'Brush', sprite = 'Brush' },
    { name = 'Chain', sprite = 'Chain' },
    { name = 'Metal', sprite = 'Metal' },
    { name = 'Metal 2', sprite = 'Metal2' },
    { name = 'Gradient', sprite = 'Gradient1' },
    { name = 'Gradient 2', sprite = 'Gradient2' },
    { name = 'Gradient 3', sprite = 'Gradient3' },
    { name = 'Gradient 4', sprite = 'Gradient4' },
    { name = 'Noise', sprite = 'Noise' },
    { name = 'Note', sprite = 'Note' },
    { name = 'Note 2', sprite = 'Note2' },
    { name = 'Note 3', sprite = 'Note3' },
    { name = 'Note 4', sprite = 'Note4' },
    { name = 'Note 5', sprite = 'Note5' },
    { name = 'Note 6', sprite = 'Note6' },
    { name = 'Spray', sprite = 'Spray' },
}