Config = {}

Config.DrawDistance = 10

Config.Tattoos = {
	["mpbusiness_overlays"] = {
		"MP_Buis_M_Neck_000",
		"MP_Buis_M_Neck_001",
		"MP_Buis_M_Neck_002",
		"MP_Buis_M_Neck_003",
		"MP_Buis_M_LeftArm_000",
		"MP_Buis_M_LeftArm_001",
		"MP_Buis_M_RightArm_000",
		"MP_Buis_M_RightArm_001",
		"MP_Buis_M_Stomach_000",
		"MP_Buis_M_Chest_000",
		"MP_Buis_M_Chest_001",
		"MP_Buis_M_Back_000",
		"MP_Buis_F_Chest_000",
		"MP_Buis_F_Chest_001",
		"MP_Buis_F_Chest_002",
		"MP_Buis_F_Stom_000",
		"MP_Buis_F_Stom_001",
		"MP_Buis_F_Stom_002",
		"MP_Buis_F_Back_000",
		"MP_Buis_F_Back_001",
		"MP_Buis_F_Neck_000",
		"MP_Buis_F_Neck_001",
		"MP_Buis_F_RArm_000",
		"MP_Buis_F_LArm_000",
		"MP_Buis_F_LLeg_000",
		"MP_Buis_F_RLeg_000",
	},

	["mphipster_overlays"] = {
		"FM_Hip_M_Tat_000",
		"FM_Hip_M_Tat_001",
		"FM_Hip_M_Tat_002",
		"FM_Hip_M_Tat_003",
		"FM_Hip_M_Tat_004",
		"FM_Hip_M_Tat_005",
		"FM_Hip_M_Tat_006",
		"FM_Hip_M_Tat_007",
		"FM_Hip_M_Tat_008",
		"FM_Hip_M_Tat_009",
		"FM_Hip_M_Tat_010",
		"FM_Hip_M_Tat_011",
		"FM_Hip_M_Tat_012",
		"FM_Hip_M_Tat_013",
		"FM_Hip_M_Tat_014",
		"FM_Hip_M_Tat_015",
		"FM_Hip_M_Tat_016",
		"FM_Hip_M_Tat_017",
		"FM_Hip_M_Tat_018",
		"FM_Hip_M_Tat_019",
		"FM_Hip_M_Tat_020",
		"FM_Hip_M_Tat_021",
		"FM_Hip_M_Tat_022",
		"FM_Hip_M_Tat_023",
		"FM_Hip_M_Tat_024",
		"FM_Hip_M_Tat_025",
		"FM_Hip_M_Tat_026",
		"FM_Hip_M_Tat_027",
		"FM_Hip_M_Tat_028",
		"FM_Hip_M_Tat_029",
		"FM_Hip_M_Tat_030",
		"FM_Hip_M_Tat_031",
		"FM_Hip_M_Tat_032",
		"FM_Hip_M_Tat_033",
		"FM_Hip_M_Tat_034",
		"FM_Hip_M_Tat_035",
		"FM_Hip_M_Tat_036",
		"FM_Hip_M_Tat_037",
		"FM_Hip_M_Tat_038",
		"FM_Hip_M_Tat_039",
		"FM_Hip_M_Tat_040",
		"FM_Hip_M_Tat_041",
		"FM_Hip_M_Tat_042",
		"FM_Hip_M_Tat_043",
		"FM_Hip_M_Tat_044",
		"FM_Hip_M_Tat_045",
		"FM_Hip_M_Tat_046",
		"FM_Hip_M_Tat_047",
		"FM_Hip_M_Tat_048",
	},

	["mpbiker_overlays"] = {
		"MP_MP_Biker_Tat_000_M",
		"MP_MP_Biker_Tat_001_M",
		"MP_MP_Biker_Tat_002_M",
		"MP_MP_Biker_Tat_003_M",
		"MP_MP_Biker_Tat_004_M",
		"MP_MP_Biker_Tat_005_M",
		"MP_MP_Biker_Tat_006_M",
		"MP_MP_Biker_Tat_007_M",
		"MP_MP_Biker_Tat_008_M",
		"MP_MP_Biker_Tat_009_M",
		"MP_MP_Biker_Tat_010_M",
		"MP_MP_Biker_Tat_011_M",
		"MP_MP_Biker_Tat_012_M",
		"MP_MP_Biker_Tat_013_M",
		"MP_MP_Biker_Tat_014_M",
		"MP_MP_Biker_Tat_015_M",
		"MP_MP_Biker_Tat_016_M",
		"MP_MP_Biker_Tat_017_M",
		"MP_MP_Biker_Tat_018_M",
		"MP_MP_Biker_Tat_019_M",
		"MP_MP_Biker_Tat_020_M",
		"MP_MP_Biker_Tat_021_M",
		"MP_MP_Biker_Tat_022_M",
		"MP_MP_Biker_Tat_023_M",
		"MP_MP_Biker_Tat_024_M",
		"MP_MP_Biker_Tat_025_M",
		"MP_MP_Biker_Tat_026_M",
		"MP_MP_Biker_Tat_027_M",
		"MP_MP_Biker_Tat_028_M",
		"MP_MP_Biker_Tat_029_M",
		"MP_MP_Biker_Tat_030_M",
		"MP_MP_Biker_Tat_031_M",
		"MP_MP_Biker_Tat_032_M",
		"MP_MP_Biker_Tat_033_M",
		"MP_MP_Biker_Tat_034_M",
		"MP_MP_Biker_Tat_035_M",
		"MP_MP_Biker_Tat_036_M",
		"MP_MP_Biker_Tat_037_M",
		"MP_MP_Biker_Tat_038_M",
		"MP_MP_Biker_Tat_039_M",
		"MP_MP_Biker_Tat_040_M",
		"MP_MP_Biker_Tat_041_M",
		"MP_MP_Biker_Tat_042_M",
		"MP_MP_Biker_Tat_043_M",
		"MP_MP_Biker_Tat_044_M",
		"MP_MP_Biker_Tat_045_M",
		"MP_MP_Biker_Tat_046_M",
		"MP_MP_Biker_Tat_047_M",
		"MP_MP_Biker_Tat_048_M",
		"MP_MP_Biker_Tat_049_M",
		"MP_MP_Biker_Tat_050_M",
		"MP_MP_Biker_Tat_051_M",
		"MP_MP_Biker_Tat_052_M",
		"MP_MP_Biker_Tat_053_M",
		"MP_MP_Biker_Tat_054_M",
		"MP_MP_Biker_Tat_055_M",
		"MP_MP_Biker_Tat_056_M",
		"MP_MP_Biker_Tat_057_M",
		"MP_MP_Biker_Tat_058_M",
		"MP_MP_Biker_Tat_059_M",
		"MP_MP_Biker_Tat_060_M",
	},

	["mpairraces_overlays"] = {
		"MP_Airraces_Tattoo_000_M",
		"MP_Airraces_Tattoo_001_M",
		"MP_Airraces_Tattoo_002_M",
		"MP_Airraces_Tattoo_003_M",
		"MP_Airraces_Tattoo_004_M",
		"MP_Airraces_Tattoo_005_M",
		"MP_Airraces_Tattoo_006_M",
		"MP_Airraces_Tattoo_007_M",
	},

	["mpbeach_overlays"] = {
		"MP_Bea_M_Back_000",
		"MP_Bea_M_Chest_000",
		"MP_Bea_M_Chest_001",
		"MP_Bea_M_Head_000",
		"MP_Bea_M_Head_001",
		"MP_Bea_M_Head_002",
		"MP_Bea_M_Lleg_000",
		"MP_Bea_M_Rleg_000",
		"MP_Bea_M_RArm_000",
		"MP_Bea_M_Head_000",
		"MP_Bea_M_LArm_000",
		"MP_Bea_M_LArm_001",
		"MP_Bea_M_Neck_000",
		"MP_Bea_M_Neck_001",
		"MP_Bea_M_RArm_001",
		"MP_Bea_M_Stom_000",
		"MP_Bea_M_Stom_001",
	},

	["mpchristmas2_overlays"] = {
		"MP_Xmas2_M_Tat_000",
		"MP_Xmas2_M_Tat_001",
		"MP_Xmas2_M_Tat_003",
		"MP_Xmas2_M_Tat_004",
		"MP_Xmas2_M_Tat_005",
		"MP_Xmas2_M_Tat_006",
		"MP_Xmas2_M_Tat_007",
		"MP_Xmas2_M_Tat_008",
		"MP_Xmas2_M_Tat_009",
		"MP_Xmas2_M_Tat_010",
		"MP_Xmas2_M_Tat_011",
		"MP_Xmas2_M_Tat_012",
		"MP_Xmas2_M_Tat_013",
		"MP_Xmas2_M_Tat_014",
		"MP_Xmas2_M_Tat_015",
		"MP_Xmas2_M_Tat_016",
		"MP_Xmas2_M_Tat_017",
		"MP_Xmas2_M_Tat_018",
		"MP_Xmas2_M_Tat_019",
		"MP_Xmas2_M_Tat_022",
		"MP_Xmas2_M_Tat_023",
		"MP_Xmas2_M_Tat_024",
		"MP_Xmas2_M_Tat_025",
		"MP_Xmas2_M_Tat_026",
		"MP_Xmas2_M_Tat_027",
		"MP_Xmas2_M_Tat_028",
		"MP_Xmas2_M_Tat_029",
	},

	["mpgunrunning_overlays"] = {
		"MP_Gunrunning_Tattoo_000_M",
		"MP_Gunrunning_Tattoo_001_M",
		"MP_Gunrunning_Tattoo_002_M",
		"MP_Gunrunning_Tattoo_003_M",
		"MP_Gunrunning_Tattoo_004_M",
		"MP_Gunrunning_Tattoo_005_M",
		"MP_Gunrunning_Tattoo_006_M",
		"MP_Gunrunning_Tattoo_007_M",
		"MP_Gunrunning_Tattoo_008_M",
		"MP_Gunrunning_Tattoo_009_M",
		"MP_Gunrunning_Tattoo_010_M",
		"MP_Gunrunning_Tattoo_011_M",
		"MP_Gunrunning_Tattoo_012_M",
		"MP_Gunrunning_Tattoo_013_M",
		"MP_Gunrunning_Tattoo_014_M",
		"MP_Gunrunning_Tattoo_015_M",
		"MP_Gunrunning_Tattoo_016_M",
		"MP_Gunrunning_Tattoo_017_M",
		"MP_Gunrunning_Tattoo_018_M",
		"MP_Gunrunning_Tattoo_019_M",
		"MP_Gunrunning_Tattoo_020_M",
		"MP_Gunrunning_Tattoo_021_M",
		"MP_Gunrunning_Tattoo_022_M",
		"MP_Gunrunning_Tattoo_023_M",
		"MP_Gunrunning_Tattoo_024_M",
		"MP_Gunrunning_Tattoo_025_M",
		"MP_Gunrunning_Tattoo_026_M",
		"MP_Gunrunning_Tattoo_027_M",
		"MP_Gunrunning_Tattoo_028_M",
		"MP_Gunrunning_Tattoo_029_M",
		"MP_Gunrunning_Tattoo_030_M",
	},

	["mpimportexport_overlays"] = {
		"MP_MP_ImportExport_Tat_000_M",
		"MP_MP_ImportExport_Tat_001_M",
		"MP_MP_ImportExport_Tat_002_M",
		"MP_MP_ImportExport_Tat_003_M",
		"MP_MP_ImportExport_Tat_004_M",
		"MP_MP_ImportExport_Tat_005_M",
		"MP_MP_ImportExport_Tat_006_M",
		"MP_MP_ImportExport_Tat_007_M",
		"MP_MP_ImportExport_Tat_008_M",
		"MP_MP_ImportExport_Tat_009_M",
		"MP_MP_ImportExport_Tat_010_M",
		"MP_MP_ImportExport_Tat_011_M",
	},

	["mplowrider2_overlays"] = {
		"MP_LR_Tat_000_M",
		"MP_LR_Tat_003_M",
		"MP_LR_Tat_006_M",
		"MP_LR_Tat_008_M",
		"MP_LR_Tat_011_M",
		"MP_LR_Tat_012_M",
		"MP_LR_Tat_016_M",
		"MP_LR_Tat_018_M",
		"MP_LR_Tat_019_M",
		"MP_LR_Tat_022_M",
		"MP_LR_Tat_028_M",
		"MP_LR_Tat_029_M",
		"MP_LR_Tat_030_M",
		"MP_LR_Tat_031_M",
		"MP_LR_Tat_032_M",
		"MP_LR_Tat_035_M",
	},

	["mplowrider_overlays"] = {
		"MP_LR_Tat_001_M",
		"MP_LR_Tat_002_M",
		"MP_LR_Tat_004_M",
		"MP_LR_Tat_005_M",
		"MP_LR_Tat_007_M",
		"MP_LR_Tat_009_M",
		"MP_LR_Tat_010_M",
		"MP_LR_Tat_013_M",
		"MP_LR_Tat_014_M",
		"MP_LR_Tat_015_M",
		"MP_LR_Tat_017_M",
		"MP_LR_Tat_020_M",
		"MP_LR_Tat_021_M",
		"MP_LR_Tat_023_M",
		"MP_LR_Tat_026_M",
		"MP_LR_Tat_027_M",
		"MP_LR_Tat_033_M",
	},
}

function GetTattooDataForKeys()
	local retData = {}
	for _, tattoo in ipairs(Tattoos) do
		retData[tattoo.key] = tattoo
	end
	return retData
end

Config.HairOverlays = {
	[`mp_m_freemode_01`] = {
		[1] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
		[2] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
		[3] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_003' },
		[4] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_004' },
		[5] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_005' },
		[6] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_006' },
		[7] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_007' },
		[8] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_008' },
		[9] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_009' },
		[10] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_013' },
		[11] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_002' },
		[12] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_011' },
		[13] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_012' },
		[14] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_014' },
		[15] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_015' },
		[16] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_M_Hair_000' },
		[17] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_M_Hair_001' },
		[18] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_M_Hair_000' },
		[19] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_M_Hair_001' },
		[20] = { collection = 'multiplayer_overlays',  overlay = 'NGHip_M_Hair_000' },
		[21] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		[22] = { collection = 'multiplayer_overlays',  overlay = 'NGInd_M_Hair_000' },
		--[24] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_001' },
		[25] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_001' },
		[26] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_002' },
		[27] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_003' },
		[28] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_004' },
		[29] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_005' },
		[30] = { collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_006' },
		[31] = { collection = 'mplowrider_overlays', overlay = 'MP_Biker_Hair_000_M' },
		[32] = { collection = 'mplowrider_overlays', overlay = 'MP_Biker_Hair_001_M' },
		[33] = { collection = 'mplowrider_overlays', overlay = 'MP_Biker_Hair_002_M' },
		[35] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_M' },
		[36] = { collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_005_M' },
		[37] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_001' },
		[38] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_002' },
		[39] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_003' },
		[40] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_004' },
		[41] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_005' },
		[42] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_006' },
		[43] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_007' },
		[44] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_008' },
		[45] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_009' },
		[46] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_013' },
		[47] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_002' },
		[48] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_011' },
		[49] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_012' },
		[50] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_014' },
		[51] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_015' },
		[52] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_M_Hair_000' },
		[53] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_M_Hair_001' },
		[54] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_M_Hair_000' },
		[55] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_M_Hair_001' },
		[56] = { collection = 'multiplayer_overlays',  overlay = 'NGHip_M_Hair_000' },
		[57] = { collection = 'multiplayer_overlays',  overlay = 'NGHip_M_Hair_001' },
		[58] = { collection = 'multiplayer_overlays',  overlay = 'NGInd_M_Hair_000' },
		[59] = { collection = 'mplowrider_overlays',   overlay = 'LR_M_Hair_000' },
		[60] = { collection = 'mplowrider_overlays',   overlay = 'LR_M_Hair_001' },
		[61] = { collection = 'mplowrider_overlays',   overlay = 'LR_M_Hair_002' },
		[62] = { collection = 'mplowrider_overlays',   overlay = 'LR_M_Hair_003' },
		[63] = { collection = 'mplowrider2_overlays',  overlay = 'LR_M_Hair_004' },
		[64] = { collection = 'mplowrider2_overlays',  overlay = 'LR_M_Hair_005' },
		[65] = { collection = 'mplowrider2_overlays',  overlay = 'LR_M_Hair_006' },
		[66] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_000_M' },
		[67] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_001_M' },
		[68] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_002_M' },
		[69] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_003_M' },
		[70] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_004_M' },
		[71] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_005_M' },
		[72] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_000_M' },
		[73] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_001_M' },
		-- Custom Hair
		[76] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		[77] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		[79] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
		[80] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
		[82] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
		[84] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
		[86] = { collection = 'mplowrider2_overlays',  overlay = 'LR_M_Hair_006' },
		[87] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
		[90] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		[93] = { collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
		[94] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
		[96] = { collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
		[103] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		[106] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		--[108] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		--[109] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
		--[121] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
	},
	[`mp_f_freemode_01`] = {
		[1] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_001' },
		[2] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_002' },
		[3] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_003' },
		[4] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_004' },
		[5] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_005' },
		[6] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_006' },
		[7] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_007' },
		[8] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_008' },
		[9] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_009' },
		[10] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_010' },
		[11] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_011' },
		[12] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_012' },
		[13] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_013' },
		[14] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_014' },
		[15] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_015' },
		[16] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_000' },
		[17] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_001' },
		[18] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_007' },
		[19] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_F_Hair_000' },
		[21] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_F_Hair_001' },
		[22] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_001' },
		[23] = { collection = 'multiplayer_overlays',  overlay = 'NGHip_F_Hair_000' },
		[24] = { collection = 'multiplayer_overlays',  overlay = 'NGInd_F_Hair_000' },
		[25] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_000' },
		[26] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_001' },
		[27] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_002' },
		[28] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_003' },
		[29] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_003' },
		[30] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_004' },
		[31] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_006' },
		[32] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_000_F' },
		[33] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_001_F' },
		[34] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_002_F' },
		[35] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_003_F' },
		[36] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_003' },
		[37] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_006_F' },
		[38] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_004_F' },
		[39] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_001' },
		[40] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_002' },
		[41] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_003' },
		[42] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_004' },
		[43] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_005' },
		[44] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_006' },
		[45] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_007' },
		[46] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_008' },
		[47] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_009' },
		[48] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_010' },
		[49] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_011' },
		[50] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_012' },
		[51] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_013' },
		[52] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_014' },
		[53] = { collection = 'multiplayer_overlays',  overlay = 'NG_M_Hair_015' },
		[54] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_000' },
		[55] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_001' },
		[56] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_007' },
		[57] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_F_Hair_000' },
		[58] = { collection = 'multiplayer_overlays',  overlay = 'NGBus_F_Hair_001' },
		[59] = { collection = 'multiplayer_overlays',  overlay = 'NGBea_F_Hair_001' },
		[60] = { collection = 'multiplayer_overlays',  overlay = 'NGHip_F_Hair_000' },
		[61] = { collection = 'multiplayer_overlays',  overlay = 'NGInd_F_Hair_000' },
		[62] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_000' },
		[63] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_001' },
	   	[64] = { collection = 'mplowrider_overlays',   overlay = 'LR_F_Hair_002' },
		[65] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_003' },
		[66] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_003' },
		[67] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_004' },
		[68] = { collection = 'mplowrider2_overlays',  overlay = 'LR_F_Hair_006' },
		[69] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_000_F' },
		[70] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_001_F' },
		[71] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_002_F' },
		[72] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_003_F' },
		[73] = { collection = 'multiplayer_overlays',  overlay = 'NG_F_Hair_003' },
		[74] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_006_F' },
		[75] = { collection = 'mpbiker_overlays',      overlay = 'MP_Biker_Hair_004_F' },
		[76] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_F_000_F' },
		[77] = { collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_F_001_F' },
		-- Custom Hair
		[126] = { collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
	},
}

Config.CustomHairOverlays = {
	{ collection = 'multiplayer_overlays', overlay = 'NGHip_M_Hair_001' },
	{ collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_003' },
	{ collection = 'mpbeach_overlays', overlay = 'FM_Hair_Fuzz' },
	{ collection = 'mplowrider2_overlays', overlay = 'LR_M_Hair_006' },
	{ collection = 'multiplayer_overlays', overlay = 'NG_M_Hair_001' },
	{ collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_001_M' },
	{ collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_002_M' },
	{ collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_003_M' },
	{ collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_004_M' },
	{ collection = 'mpbiker_overlays', overlay = 'MP_Biker_Hair_005_M' },
	{ collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_000_M' },
	{ collection = 'mpgunrunning_overlays', overlay = 'MP_Gunrunning_Hair_M_001_M' },
	{ collection = 'mplowrider_overlays',   overlay = 'LR_M_Hair_000' },
	{ collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_001' },
	{ collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_002' },
	{ collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_003' },
	{ collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_004' },
	{ collection = 'mplowrider_overlays', overlay = 'LR_M_Hair_005' },
	{ collection = 'mplowrider_overlays', overlay = 'MP_Biker_Hair_000_M' },
}