_bobcatWeapons = {
	`WEAPON_APPISTOL`,
	`WEAPON_MG`,
	`WEAPON_COMBATMG`,
    `WEAPON_ASSAULTRIFLE`,
    `WEAPON_CARBINERIFLE`,
    `WEAPON_COMPACTRIFLE`,
    `WEAPON_SMG`,
    `WEAPON_SMG_MK2`,
    `WEAPON_ASSAULTSHOTGUN`,
    `WEAPON_SAWNOFFSHOTGUN`,

    --`WEAPON_PUMPSHOTGUN`,
}