export const Wallpapers = {
    wallpaper: { file: require('../Wallpapers/1.webp').default, label: 'Wallpaper 1' },
    wallpaper2: { file: require('../Wallpapers/2.webp').default, label: 'Wallpaper 2' },
    wallpaper3: { file: require('../Wallpapers/3.webp').default, label: 'Wallpaper 3' },
    wallpaper4: { file: require('../Wallpapers/4.webp').default, label: 'Wallpaper 4' },
    wallpaper5: { file: require('../Wallpapers/5.webp').default, label: 'Wallpaper 5' },
    wallpaper6: { file: require('../Wallpapers/6.webp').default, label: 'Wallpaper 6' },
    wallpaper7: { file: require('../Wallpapers/7.webp').default, label: 'Wallpaper 7' },
    wallpaper8: { file: require('../Wallpapers/8.webp').default, label: 'Wallpaper 8' },
    wallpaper9: { file: require('../Wallpapers/9.webp').default, label: 'Wallpaper 9' },
    wallpaper10: { file: require('../Wallpapers/10.webp').default, label: 'Wallpaper 10' },
    wallpaper11: { file: require('../Wallpapers/11.webp').default, label: 'Wallpaper 11' },
    wallpaper12: { file: require('../Wallpapers/12.webp').default, label: 'Wallpaper 12' },
    wallpaper13: { file: require('../Wallpapers/13.webp').default, label: 'Wallpaper 13' },
    wallpaper14: { file: require('../Wallpapers/14.webp').default, label: 'Wallpaper 14' },
    wallpaper15: { file: require('../Wallpapers/15.webp').default, label: 'Wallpaper 15' },
    wallpaper16: { file: require('../Wallpapers/16.webp').default, label: 'Wallpaper 16' },
    wallpaper17: { file: require('../Wallpapers/17.webp').default, label: 'Wallpaper 17' },
    wallpaper18: { file: require('../Wallpapers/18.webp').default, label: 'Wallpaper 18' },
    wallpaper19: { file: require('../Wallpapers/19.webp').default, label: 'Wallpaper 19' },
    wallpaper20: { file: require('../Wallpapers/20.webp').default, label: 'Wallpaper 20' },
    wallpaper21: { file: require('../Wallpapers/21.webp').default, label: 'Wallpaper 21' },
    wallpaper22: { file: require('../Wallpapers/22.webp').default, label: 'Wallpaper 22' },
    wallpaper23: { file: require('../Wallpapers/23.webp').default, label: 'Wallpaper 23' },
    wallpaper24: { file: require('../Wallpapers/24.webp').default, label: 'Wallpaper 24' },
    wallpaper25: { file: require('../Wallpapers/25.webp').default, label: 'Wallpaper 25' },
}