_itemsSource["schematics_attachments"] = {
	{
		name = "schematic_weapon_flashlight",
		label = "Schematic: Weapon Flashlight",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.weapon_flashlight,
	},
	{
		name = "schematic_pistol_ext_mag",
		label = "Schematic: Pistol Ext. Mag",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.pistol_ext_mag,
	},
	{
		name = "schematic_smg_ext_mag",
		label = "Schematic: SMG Ext. Mag",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.smg_ext_mag,
	},
	{
		name = "schematic_rifle_ext_mag",
		label = "Schematic: AR Ext. Mag",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.rifle_ext_mag,
	},
	{
		name = "schematic_drum_mag",
		label = "Schematic: Drum Mag",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.drum_mag,
	},
	{
		name = "schematic_box_mag",
		label = "Schematic: Box Mag",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.box_mag,
	},
	{
		name = "schematic_pistol_suppressor",
		label = "Schematic: Pistol Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.pistol_suppressor,
	},
	{
		name = "schematic_adv_pistol_suppressor",
		label = "Schematic: Adv. Pistol Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.adv_pistol_suppressor,
	},
	{
		name = "schematic_smg_suppressor",
		label = "Schematic: SMG Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.smg_suppressor,
	},
	{
		name = "schematic_adv_smg_suppressor",
		label = "Schematic: Adv. SMG Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.adv_smg_suppressor,
	},
	{
		name = "schematic_ar_suppressor",
		label = "Schematic: AR Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.ar_suppressor,
	},
	{
		name = "schematic_adv_ar_suppressor",
		label = "Schematic: Adv. AR Suppressor",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.adv_ar_suppressor,
	},
	{
		name = "schematic_scope_holo",
		label = "Schematic: Holographic Sight",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.scope_holo,
	},
	{
		name = "schematic_scope_reddot",
		label = "Schematic: Red Dot Sight",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.scope_reddot,
	},
	{
		name = "schematic_scope_small",
		label = "Schematic: Small Scope",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.scope_small,
	},
	{
		name = "schematic_scope_med",
		label = "Schematic: Medium Scope",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.scope_med,
	},
	{
		name = "schematic_scope_lrg",
		label = "Schematic: Large Scope",
		iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
		schematic = _schematics.scope_lrg,
	},
}
