_itemsSource["schematics_weapons"] = {
	{
		name = "schematic_mp5",
		label = "Schematic: MP5",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.mp5,
	},
	{
		name = "schematic_miniuzi",
		label = "Schematic: Mini UZI",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.miniuzi,
	},
	{
		name = "schematic_mp9",
		label = "Schematic: MP9a",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.mp9,
	},
	{
		name = "schematic_mpx",
		label = "Schematic: MPX",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.mpx,
	},
	{
		name = "schematic_pp19",
		label = "Schematic: PP-19",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.pp19,
	},
	{
		name = "schematic_appistol",
		label = "Schematic: Glock 18c",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.appistol,
	},
	{
		name = "schematic_tec9",
		label = "Schematic: TEC-9",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.tech9,
	},
	{
		name = "schematic_ak74",
		label = "Schematic: AK-74",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.ak74,
	},
	{
		name = "schematic_ak47",
		label = "Schematic: AK-47",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.ak47,
	},
	{
		name = "schematic_g45",
		label = "Schematic: Glock 45",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.g45,
	},
	{
		name = "schematic_l5",
		label = "Schematic: Desert Eagle L5",
        iconOverride = "schematic",
		price = 5000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		type = 17,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
		durability = (60 * 60 * 24 * 21),
        schematic = _schematics.l5,
	},
}