_itemsSource['crafting'] = {
	{
		name = "plastic",
		label = "Plastic",
		price = 10,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "scrapmetal",
		label = "Scrap Metal",
		price = 10,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "electronic_parts",
		label = "Electronic Parts",
		price = 250,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "rubber",
		label = "Rubber",
		price = 10,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "copperwire",
		label = "Copper Wire",
		price = 10,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "glue",
		label = "Glue",
		price = 150,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "heavy_glue",
		label = "Heavy Duty Glue",
		price = 200,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	
	{
		name = "goldbar",
		label = "Gold Bar",
		price = 500,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "silverbar",
		label = "Silver Bar",
		price = 200,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "ironbar",
		label = "Iron Bar",
		price = 2500,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0,
	},
	{
		name = "gunpowder",
		label = "Gun Powder",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	
	{
		name = "refined_iron",
		label = "Refined Iron",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "refined_copper",
		label = "Refined Copper",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "refined_plastic",
		label = "Refined Plasic",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
	{
		name = "refined_rubber",
		label = "Refined Rubber",
		price = 1000,
		isUsable = false,
		isRemoved = false,
		isStackable = 10000,
		isDestroyed = false,
		type = 4,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0,
	},
}