_itemsSource["loot"] = {
	{
		name = "valuegoods",
		label = "Valuable Goods",
		description = "Potentially Stolen",
		price = 2450,
		isUsable = false,
		isStackable = 10,
		isDestroyed = true,
		type = 4,
		rarity = 4,
		closeUi = false,
		metalic = false,
		weight = 1,
	},
	{
		name = "goldcoins",
		label = "Gold Coins",
		description = "Potentially Stolen",
		price = 90,
		isUsable = false,
		isStackable = 1000,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.1,
	},
	{
		name = "rolex",
		label = "Rolex",
		description = "Potentially Stolen",
		price = 500,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = false,
		weight = 0.75,
	},
	{
		name = "ring",
		label = "Ring",
		description = "Potentially Stolen",
		price = 185,
		isUsable = false,
		isStackable = 100,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 1,
	},
	{
		name = "chain",
		label = "Gold Chain",
		description = "Potentially Stolen",
		price = 215,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "watch",
		label = "Gold Watch",
		description = "Potentially Stolen",
		price = 215,
		isUsable = false,
		isStackable = 50,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 1,
	},
	{
		name = "earrings",
		label = "Gold Earrings",
		description = "Potentially Stolen",
		price = 185,
		isUsable = false,
		isStackable = 100,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 0.8,
	},
	{
		name = "tv",
		label = "Television",
		description = "Potentially Stolen",
		price = 1800,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_tv",
	},
	{
		name = "big_tv",
		label = "Television",
		description = "Potentially Stolen",
		price = 3400,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_bigtv",
	},
	{
		name = "boombox",
		label = "Boom Box",
		description = "Potentially Stolen",
		price = 300,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 50.0,
		state = "ANIM_boombox",
	},
	{
		name = "microwave",
		label = "Microwave",
		description = "Potentially Stolen",
		price = 500,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 1,
		closeUi = false,
		metalic = true,
		weight = 50.0,
		state = "ANIM_microwave",
	},
	{
		name = "golfclubs",
		label = "Golf Club Set",
		price = 450,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 100.0,
		state = "ANIM_golfclubs",
	},
	{
		name = "house_art",
		label = "Painting",
		price = 3600,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = false,
		weight = 100.0,
		state = "ANIM_house_art",
	},
	{
		name = "pc",
		label = "PC",
		price = 1200,
		isUsable = false,
		isStackable = 1,
		type = 6,
		rarity = 2,
		closeUi = false,
		metalic = true,
		weight = 80.0,
		state = "ANIM_pc",
	},
	{
		name = "crushedrock",
		label = "Crushed Rock",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "salvagedparts",
		label = "Salvaged Parts",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "recycledgoods",
		label = "Recycled Goods",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "goldore",
		label = "Gold Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "silverore",
		label = "Silver Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "ironore",
		label = "Iron Ore",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 200,
		isDestroyed = false,
		type = 6,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "diamond",
		label = "Diamond",
		price = 8000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2.5,
	},
	{
		name = "emerald",
		label = "Emerald",
		price = 8000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "sapphire",
		label = "Sapphire",
		price = 6000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "ruby",
		label = "Ruby",
		price = 6000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 3,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "amethyst",
		label = "Amethyst",
		price = 4000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "citrine",
		label = "Citrine",
		price = 4000,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "opal",
		label = "Opal",
		price = 1500,
		isUsable = false,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		type = 11,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.5,
	},
	{
		name = "moneyroll",
		label = "Cash Roll",
		price = 100,
		isUsable = false,
		isStackable = 1000,
		type = 14,
		rarity = 1,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "moneyband",
		label = "Bands of Cash",
		price = 1000,
		isUsable = false,
		isStackable = 1000,
		type = 14,
		rarity = 1,
		metalic = false,
		weight = 0.01,
	},
	{
		name = "moneybag",
		label = "Bag of Cash",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 14,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
		durability = (60 * 60 * 24 * 14),
	},
	{
		name = "hide_tier1",
		label = "Animal Hide (Tier 1)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "hide_tier2",
		label = "Animal Hide (Tier 2)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "hide_tier3",
		label = "Animal Hide (Tier 3)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "hide_tier4",
		label = "Animal Hide (Tier 4)",
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		type = 3,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 3,
	},
	{
		name = "fleeca_card",
		label = "Disposable Access Card",
		description = "This seems like it may be usefull",
		price = 10000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 6),
		type = 14,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
	{
		name = "crypto_voucher",
		label = "Crypto Voucher",
		price = 0,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		type = 7,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0.25,
	},
}
