_itemsSource["unique"] = {
	{
		name = "rlg_chain",
		label = "RLG Chain",
		description = "Redline Gang Gang",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "rlg",
	},
	{
		name = "lss_chain",
		label = "LSS Chain",
		description = "LSS",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lss",
	},
	{
		name = "ferrari_chain",
		label = "Ferrari Chain",
		description = "Ferrari",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ferrari",
	},
	{
		name = "enemigos_chain",
		label = "Enemigos Chain",
		description = "Enemigos",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "enemigos",
	},
	{
		name = "lust_chain",
		label = "Lust Chain",
		description = "Lust",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lust",
	},
	{
		name = "ssf_chain",
		label = "SSF Chain",
		description = "South Side Families",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssf",
	},
}
